### ISSUE TITLE
org.georchestra.security  - Error connecting to client

### ISSUE THREAD

**Issue by fvanderbiest** [georchestra/georchestra#1024]
In https://travis-ci.org/georchestra/georchestra/builds/72803830

```
88 [main] ERROR org.georchestra.security  - Error connecting to client
java.net.MalformedURLException: null is not a valid URL
    at org.georchestra.security.Proxy.handlePathEncodedRequests(Proxy.java:389)
    at org.georchestra.security.Proxy.handleGETRequest(Proxy.java:324)
    at org.georchestra.security.ProxyTest.testGetUrlLegalUrlButTarget(ProxyTest.java:88)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
    at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
    at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
    at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
    at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
    at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
    at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
    at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
    at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
    at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
    at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
    at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
    at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
    at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
    at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:252)
    at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:141)
    at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:112)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
    at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
    at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
    at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
    at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)
91 [main] DEBUG org.georchestra.security  - handlePathEncodedRequests: -- Handling Request: GET:/geonetwork/srv/eng/something from: 127.0.0.1
409 [main] DEBUG org.georchestra.security  - Final request -- http://www.google.com/geonetwork-private/srv/eng/something
410 [main] DEBUG org.georchestra.security  - New request is: http://www.google.com/geonetwork-private/srv/eng/something
Request is GET
420 [main] DEBUG OGCServiceMessageFormatter  - REQUEST: jeichar|2015/07/27|http://www.google.com/geonetwork-private/srv/eng/something||MEM -Current available: 451 Mb  - Max: 6700 Mb  - Free: 418 Mb |CPU - Load Average: 7.01 - Available Processors: 16| DISK (/) - Total: 15643 Mb  - Usable: 5042 Mb  - Free: 5042 Mb |
420 [main] INFO org.georchestra.security.statistics  - jeichar|2015/07/27|http://www.google.com/geonetwork-private/srv/eng/something|
421 [main] DEBUG org.georchestra.security  - Host header set to: null for proxy request.
421 [main] DEBUG org.georchestra.security  - charset not required for contentType: null
421 [main] DEBUG org.georchestra.security  - handlePathEncodedRequests: -- Handling Request: GET:/extractorapp/home from: 127.0.0.1
431 [main] DEBUG org.georchestra.security  - Final request -- http://localhost/extractorapp-private/home
431 [main] DEBUG org.georchestra.security  - New request is: http://localhost/extractorapp-private/home
Request is GET
431 [main] DEBUG OGCServiceMessageFormatter  - REQUEST: jeichar|2015/07/27|http://localhost/extractorapp-private/home||MEM -Current available: 451 Mb  - Max: 6700 Mb  - Free: 415 Mb |CPU - Load Average: 7.01 - Available Processors: 16| DISK (/) - Total: 15643 Mb  - Usable: 5042 Mb  - Free: 5042 Mb |
432 [main] INFO org.georchestra.security.statistics  - jeichar|2015/07/27|http://localhost/extractorapp-private/home|
432 [main] DEBUG org.georchestra.security  - Host header set to: null for proxy request.
432 [main] DEBUG org.georchestra.security  - charset not required for contentType: null
432 [main] DEBUG org.georchestra.security  - handlePathEncodedRequests: -- Handling Request: GET:/unmapped/x from: 127.0.0.1
433 [main] ERROR org.georchestra.security  - Error connecting to client
java.net.MalformedURLException: null is not a valid URL
    at org.georchestra.security.Proxy.handlePathEncodedRequests(Proxy.java:389)
    at org.georchestra.security.Proxy.handleGETRequest(Proxy.java:324)
    at org.georchestra.security.ProxyTest.testGetUrlLegalUrlButTarget(ProxyTest.java:105)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
    at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
    at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
    at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
    at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
    at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
    at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
    at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
    at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
    at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
    at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
    at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
    at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
    at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
    at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:252)
    at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:141)
    at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:112)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
    at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
    at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
    at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
    at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)
```

**Comment by fvanderbiest** [comment]
Bumping to 16.06.

**Comment by fvanderbiest** [comment]
@pmauduit : status for 16.12 ?
