### ISSUE TITLE
[mapfishapp] compatibilité gdal 2.0

### ISSUE THREAD

**Issue by landryb** [georchestra/georchestra#1068]
L'upload de couches shp/gml/kml ne fonctionne pas avec gdal 2.0 - a voir a quel stade est le probleme, entre gdal-jni, gdal.jar et la libgdal... aucun souci avec le gdal 1.10.1 de debian jessie.

Les messages d'erreur sont assez cryptiques, l'erreur SQL vient de geotools (cf https://github.com/geotools/geotools/blob/9.x/modules/unsupported/ogr/ogr-core/src/main/java/org/geotools/data/ogr/OGRFeatureSource.java#L301)

```
==> /srv/log/tomcat/mapfishapp.log <==
2015-09-22 11:25:51 upload [INFO] gdal/ogr is available in the system
2015-09-22 11:25:51 upload [INFO] It was set: org.georchestra.mapfishapp.ws.upload.OGRFeatureReader
2015-09-22 11:25:51 upload [INFO] checkGeoFileExtension returns true
2015-09-22 11:25:51 upload [INFO] checkSingleGeoFile returns true
2015-09-22 11:25:51 upload [INFO] searchGeoFile returns /tmp/geoFileUploadsCache/ed53eaa8-8995-4cf3-824a-c02402b7899f/points_ortho_modifies_2011.shp
2015-09-22 11:25:51 upload [INFO] Using implementation: org.georchestra.mapfishapp.ws.upload.OGRFeatureReader

==> /data/tomcat/georchestra/logs/catalina.out <==
ERROR 1: SQL Expression Parsing Error: syntax error, unexpected end of string, expecting '.'. Occured around :
ID, * FROM 'points_ortho_modifies_2011' 
                                        ^

==> /srv/log/tomcat/mapfishapp.log <==
2015-09-22 11:25:51 upload [ERROR] Failed reading /tmp/geoFileUploadsCache/ed53eaa8-8995-4cf3-824a-c02402b7899f/points_ortho_modifies_2011.shp.  null
java.lang.NullPointerException
        at org.geotools.data.ogr.jni.JniOGR.LayerRelease(JniOGR.java:200)
        at org.geotools.data.ogr.OGRFeatureSource.getReaderInternal(OGRFeatureSource.java:266)
        at org.geotools.data.ogr.OGRFeatureSource.getReaderInternal(OGRFeatureSource.java:167)
        at org.geotools.data.ogr.OGRFeatureStore.getReaderInternal(OGRFeatureStore.java:115)
        at org.geotools.data.store.ContentFeatureSource.getReader(ContentFeatureSource.java:562)
        at org.geotools.data.store.ContentFeatureCollection.features(ContentFeatureCollection.java:165)
        at org.geotools.data.store.ContentFeatureCollection.features(ContentFeatureCollection.java:59)
        at org.georchestra.mapfishapp.ws.upload.FeatureJSON2$FeatureCollectionEncoder.writeJSONString(FeatureJSON2.java:579)
        at org.json.simple.JSONValue.writeJSONString(Unknown Source)
        at org.json.simple.JSONObject.writeJSONString(Unknown Source)
        at org.geotools.geojson.GeoJSONUtil.encode(GeoJSONUtil.java:252)
        at org.georchestra.mapfishapp.ws.upload.FeatureJSON2.writeFeatureCollection(FeatureJSON2.java:292)
        at org.georchestra.mapfishapp.ws.upload.UpLoadFileManagement.writeFeatureCollectionAsJSON(UpLoadFileManagement.java:378)
        at org.georchestra.mapfishapp.ws.UpLoadGeoFileController.writeOKResponse(UpLoadGeoFileController.java:543)
        at org.georchestra.mapfishapp.ws.UpLoadGeoFileController.toGeoJson(UpLoadGeoFileController.java:500)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
```

**Comment by pmauduit** [comment]
Deux pistes:

- Bumper une nouvelle version de geotools dans geOrchestra (mfapp / extractorapp), éventuellement virer la version forkée que l'on a  dans l'arbre des sources (ainsi que epsg-extension, si cela n'est plus pertinent non plus) ; si ogr-jni n'est plus maintenu, voir solution 2.

- Réécrire le code nécessaire pour passer d'une part sur une version de geotools plus récente, et utiliser le binding ogr-bridg (jna), qui sera moins douloureux à configurer correctement que la version JNI ;

- Fixer dans notre fork le module OGR pour geotools

J'ai clairement une préférence pour la deuxième ...

Par contre, en l'état cela fonctionne sur les distribs fournissant encore une "vieille" version de gdal (1.x) ; même en Sid, je ne suis qu'en 1.11 ... Donc +1 pour la priorité du bug

**Comment by landryb** [comment]
GDAL 2.0 est dans
- FreeBSD
- OpenBSD
- archlinux : https://www.archlinux.org/packages/community/i686/gdal/
- masqué dans gentoo: https://packages.gentoo.org/package/sci-libs/gdal
- pas encore dans fedora
- pas encore dans le ppa d'ubuntugis (https://launchpad.net/~ubuntugis/+archive/ubuntu/ubuntugis-unstable)
- pas encore dans debian experimental, uniquement dans http://anonscm.debian.org/cgit/pkg-grass/gdal.git/log/?h=experimental-2.0 (c'est ce que j'ai backporté en jessie)

Donc oui, on a encore un peu le temps, ça urge pas beaucoup.

La première solution me parait bien aussi, depuis le temps il n'y a peut-etre plus besoin d'avoir ces versions forkées :)
