### ISSUE TITLE
store spatialindex in postgis by default

### ISSUE THREAD

**Issue by landryb** [georchestra/georchestra#1139]
Dependency of #1120, since we know we're running on postgresql, might aswell amend the doc to tell the user to load postgis in the geonetwork db/schema and configure gn3 to use it to store the spatialindex in db instead of the bloody shapefiles in the datadir.. 

cf http://osgeo-org.1560.x6.nabble.com/How-to-use-PostGIS-spatial-index-in-3-0-0-Urgent-td5208696.html

**Comment by landryb** [comment]
From what i understand of the doc, it should only be a matter of adding a "Data Source" value to the parameters passed to the jdbcDataSource constructor in ${georchestra.datadir}/geonetwork/config/config-db-georchestra.xml - will have to check.

**Comment by landryb** [comment]
Hm - there's probably more, it cant be that simple :) i'm looking at the diff between https://github.com/geonetwork/core-geonetwork/blob/3.0.x/web/src/main/webapp/WEB-INF/config-db/postgis-shared-datasource.xml and https://github.com/geonetwork/core-geonetwork/blob/3.0.x/web/src/main/webapp/WEB-INF/config-db/postgis-alternate-datasource.xml but i might be totally at the wrong place.

**Comment by landryb** [comment]
https://github.com/geonetwork/core-geonetwork/blob/3.0.x/docs/eng/users/source/admin/advanced-configuration/index.rst has more details on how to configure this.

**Comment by pmauduit** [comment]
+1 We should be able to implement this, just by defining the same beans a the postgis-alternate-datasource.xml into our overrides

**Comment by fvanderbiest** [comment]
+1000

**Comment by landryb** [comment]
Trying the obvious in config-db-georchestra.xml..

```
+  <bean id="datastoreFactory" class="org.geotools.data.postgis.PostgisNGDataStoreFactory"/>
+  <bean id="datastore" factory-bean="datastoreFactory" factory-method="createDataStore">
+    <constructor-arg>
+      <map>
+        <entry key="dbtype" value="postgis"/>
+        <entry key="Loose bbox" value="true"/>
+        <entry key="Estimated extends" value="true"/>
+        <entry key="encode functions" value="true"/>
+        <entry key="Expose primary keys" value="true"/>
+        <entry key="Data Source" value-ref="jdbcDataSource"/>
+      </map>
+    </constructor-arg>
+  </bean>

```
results in..
```
2015-11-27 15:37:08,096 ERROR [jeeves.engine] -    Handler   : org.fao.geonet.Geonetwork
2015-11-27 15:37:08,096 ERROR [jeeves.engine] -    Exception : java.lang.RuntimeException: java.lang.ClassCastException: org.geotools.jdbc.
JDBCFeatureSource cannot be cast to org.geotools.data.FeatureStore
2015-11-27 15:37:08,096 ERROR [jeeves.engine] -    Message   : java.lang.ClassCastException: org.geotools.jdbc.JDBCFeatureSource cannot be 
cast to org.geotools.data.FeatureStore
2015-11-27 15:37:08,097 ERROR [jeeves.engine] -    Stack     : java.lang.RuntimeException: java.lang.ClassCastException: org.geotools.jdbc.
JDBCFeatureSource cannot be cast to org.geotools.data.FeatureStore
        at org.fao.geonet.kernel.search.SearchManager$Spatial.createWriter(SearchManager.java:1745)
        at org.fao.geonet.kernel.search.SearchManager$Spatial.<init>(SearchManager.java:1717)
        at org.fao.geonet.kernel.search.SearchManager.initNonStaticData(SearchManager.java:539)
        at org.fao.geonet.kernel.search.SearchManager.init(SearchManager.java:519)
        at org.fao.geonet.Geonetwork.start(Geonetwork.java:319)
        at jeeves.server.JeevesEngine.initAppHandler(JeevesEngine.java:452)
        at jeeves.server.JeevesEngine.init(JeevesEngine.java:173)
        at jeeves.server.sources.http.JeevesServlet.init(JeevesServlet.java:82)
        at javax.servlet.GenericServlet.init(GenericServlet.java:158)
        at org.apache.catalina.core.StandardWrapper.initServlet(StandardWrapper.java:1241)
        at org.apache.catalina.core.StandardWrapper.loadServlet(StandardWrapper.java:1154)
        at org.apache.catalina.core.StandardWrapper.load(StandardWrapper.java:1041)
        at org.apache.catalina.core.StandardContext.loadOnStartup(StandardContext.java:4969)
        at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5255)
        at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
        at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:724)
        at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:700)
        at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:714)
        at org.apache.catalina.startup.HostConfig.deployDirectory(HostConfig.java:1071)
        at org.apache.catalina.startup.HostConfig$DeployDirectory.run(HostConfig.java:1721)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
        at java.util.concurrent.FutureTask.run(FutureTask.java:262)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.ClassCastException: org.geotools.jdbc.JDBCFeatureSource cannot be cast to org.geotools.data.FeatureStore
        at org.fao.geonet.kernel.search.spatial.SpatialIndexWriter.attemptToCreateSpatialIndexFeatureStore(SpatialIndexWriter.java:494)
        at org.fao.geonet.kernel.search.spatial.SpatialIndexWriter.findSpatialIndexStore(SpatialIndexWriter.java:480)
        at org.fao.geonet.kernel.search.spatial.SpatialIndexWriter.createFeatureStore(SpatialIndexWriter.java:453)
        at org.fao.geonet.kernel.search.spatial.SpatialIndexWriter.<init>(SpatialIndexWriter.java:131)
        at org.fao.geonet.kernel.search.SearchManager$Spatial.createWriter(SearchManager.java:1739)
        ... 24 more
```

I've just enabled postgis on the gn db, not created the spatialindex table - dunno if it's supposed to take care of this.

**Comment by landryb** [comment]
Yep, gn has created the table itself
```
geonetwork=# \d spatialindex
                                      Table "public.spatialindex"
   Column   |            Type             |                         Modifiers                          
------------+-----------------------------+------------------------------------------------------------
 fid        | integer                     | not null default nextval('spatialindex_fid_seq'::regclass)
 geom       | geometry(MultiPolygon,4326) | 
 metadataid | character varying           | 
Indexes:
    "spatialindex_pkey" PRIMARY KEY, btree (fid)
    "spatial_spatialindex_geom" gist (geom)
Check constraints:
    "enforce_dims_geom" CHECK (st_ndims(geom) = 2)
    "enforce_geotype_geom" CHECK (geometrytype(geom) = 'MULTIPOLYGON'::text OR geom IS NULL)
    "enforce_srid_geom" CHECK (st_srid(geom) = 4326)

```

**Comment by landryb** [comment]
http://javamvp.blogspot.fr/2010/05/orggeotoolsdatajdbcjdbcfeaturesource.html says something related to indexes but they're here, so maybe a geotools version update as @pmauduit thinks.

**Comment by landryb** [comment]
I have some postgis jars in the webapp: gt-jdbc-postgis-8.6.jar & postgis-{jdbc,stubs}-1.3.3.jar

**Comment by pmauduit** [comment]
> Trying the obvious in config-db-georchestra.xml..

Did almost the same, works for me ;

> I've just enabled postgis on the gn db, not created the spatialindex table - dunno if it's supposed to take care of this.

From what I observed the table is automatically created and populated (while rebuilding the indexes ?). No need to do it by hand.

**Comment by pmauduit** [comment]
Should be done with https://github.com/georchestra/geonetwork/commit/afe0f47852b04b728bfce891176b26a558903b08

Tested at runtime into my VM, table is properly created / populated

**Comment by landryb** [comment]
Tested with your commit, WFM. I had taken my example from postgis-shared-datasource.xml which seems broken, yours coming from postgis-alternate-datasource.xml works. Filed https://github.com/geonetwork/core-geonetwork/issues/1365 upstream.

No more index/spatialindex.shp in the datadir \o/
