### ISSUE TITLE
ldapadmin - creating account is broken

### ISSUE THREAD

**Issue by pmauduit** [georchestra/georchestra#1152]
On sdi.georchestra.org, getting the following trace when trying to create a new account:

```
org.springframework.ldap.NameNotFoundException: [LDAP: error code 32 - No Such Object]; nested exception is javax.naming.NameNotFoundException: [LDAP: error code 32 - No Such Object]; remaining name 'uid=pmauduit2,ou=users'
	at org.springframework.ldap.support.LdapUtils.convertLdapException(LdapUtils.java:183)
	at org.springframework.ldap.core.LdapTemplate.executeWithContext(LdapTemplate.java:820)
	at org.springframework.ldap.core.LdapTemplate.executeReadOnly(LdapTemplate.java:803)
	at org.springframework.ldap.core.LdapTemplate.lookup(LdapTemplate.java:935)
	at org.georchestra.ldapadmin.ds.AccountDaoImpl.findByUID(AccountDaoImpl.java:311)
	at org.georchestra.ldapadmin.ds.AccountDaoImpl.insert(AccountDaoImpl.java:104)
	at org.georchestra.ldapadmin.ws.newaccount.NewAccountFormController.create(NewAccountFormController.java:153)

```

**Comment by vdorut** [comment]
We need to update PENDING_USERS to PENDING in LDAP directory on sdi.georchestra.org.
After updating my local LDAP directory i dont have this issue anymore.
@pmauduit

**Comment by fvanderbiest** [comment]
> We need to update PENDING_USERS to PENDING in LDAP directory on sdi.georchestra.org.

To my knowledge, this is already the case.

**Comment by fvanderbiest** [comment]
See https://github.com/georchestra/georchestra/pull/1109#issuecomment-166250447

**Comment by Vampouille** [comment]
It seems that sometimes `ldapTemplate.lookup()` does not return `null` but instead throw a `NameNotFoundException`. So I suggest to change exception to `NameNotFoundException` here :

https://github.com/georchestra/georchestra/blob/master/ldapadmin/src/main/java/org/georchestra/ldapadmin/ds/AccountDaoImpl.java#L313

Then we should catch `NameNotFoundException` here : 

https://github.com/georchestra/georchestra/blob/master/ldapadmin/src/main/java/org/georchestra/ldapadmin/ds/AccountDaoImpl.java#L108
