### ISSUE TITLE
gn3, ldapadmin (soon analytics) - Hibernate creates an hibernate_sequence in the public schema

### ISSUE THREAD

**Issue by pmauduit** [georchestra/georchestra#1155]
Hibernate needs to create a `hibernate_sequence` into the database, but in the geOrchestra doc, everything is set into the same postgresql database, which introduces some conflicts between applications using JPA/Hibernate in the same db, below a stacktrace from gn3 for instance:

```
Caused by: org.postgresql.util.PSQLException: ERROR: permission denied for sequence hibernate_sequence
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2102)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:1835)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:257)
	at org.postgresql.jdbc2.AbstractJdbc2Statement.execute(AbstractJdbc2Statement.java:500)
	at org.postgresql.jdbc2.AbstractJdbc2Statement.executeWithFlags(AbstractJdbc2Statement.java:388)
	at org.postgresql.jdbc2.AbstractJdbc2Statement.executeQuery(AbstractJdbc2Statement.java:273)
	at org.apache.commons.dbcp.DelegatingPreparedStatement.executeQuery(DelegatingPreparedStatement.java:96)
	at org.apache.commons.dbcp.DelegatingPreparedStatement.executeQuery(DelegatingPreparedStatement.java:96)
	at org.apache.commons.dbcp.DelegatingPreparedStatement.executeQuery(DelegatingPreparedStatement.java:96)
	at org.hibernate.engine.jdbc.internal.ResultSetReturnImpl.extract(ResultSetReturnImpl.java:82)
	... 64 more
, Exception=OperationAbortedEx : Failed whilst adding the schema information. Exception message if any is could not extract ResultSet; SQL [n/a]; nested exception is org.hibernate.exception.SQLGrammarException: could not extract ResultSet, Message=Failed whilst adding the schema information. Exception message if any is could not extract ResultSet; SQL [n/a]; nested exception is org.hibernate.exception.SQLGrammarException: could not extract ResultSet, Handler=org.fao.geonet.Geonetwork, Error=Raised exception while starting the application. Fix the error and restart.}


```

**Comment by Vampouille** [comment]
We can dedicate one sequence per JPA entity by changing strategy of generated value see 
https://github.com/Vampouille/SpringTemplate/commit/b434b45d993d99e44cbf80ef6ba20c0ee7bd10df

**Comment by Vampouille** [comment]
This should be fixed by https://github.com/georchestra/georchestra/commit/79f83bf93101d5f9dd27aba18b4eb346bdd1a77a

**Comment by landryb** [comment]
That means instead of sharing the hibernate_sequence between all types of objects, a sequence is generated for each table ? nice catch.

**Comment by pmauduit** [comment]
From what we investigated with @Vampouille, each primary key needing a sequence use the same one by default (named `hibernate_sequence`, and begining with a weird first value, sometimes negative ...).

As a result this was causing problems with JPA-based applications using the same db: in my VM, ldapadmin was creating the `hibernate_sequence` before GeoNetwork had the time to initialize, GeoNetwork was unable to create the already created sequence (permission denied on the sequence, because both applications use a different username for schema mismatch).

**Comment by landryb** [comment]
That's nice to have a better understanding on how this is supposed to work. this way now we can decide to have per-schema 'global' sequences and per-table/field sequences..... depending on the usecases. I'm thinking about the 'global' hibernate sequence used in geonetwork3 for requests/logging and at the same time metadata numbers/identifiers.. sigh.
