### ISSUE TITLE
extractorapp - regression with commons FileUpload removal 

### ISSUE THREAD

**Issue by pmauduit** [georchestra/georchestra#1174]
```
extractorapp_1 | Caused by: 
extractorapp_1 | java.lang.ClassNotFoundException: org.apache.commons.fileupload.FileItemFactory
extractorapp_1 | 	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
extractorapp_1 | 	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
extractorapp_1 | 	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
extractorapp_1 | 	at org.eclipse.jetty.webapp.WebAppClassLoader.loadClass(WebAppClassLoader.java:487)
extractorapp_1 | 	at org.eclipse.jetty.webapp.WebAppClassLoader.loadClass(WebAppClassLoader.java:428)
extractorapp_1 | 	at java.lang.Class.getDeclaredConstructors0(Native Method)
extractorapp_1 | 	at java.lang.Class.privateGetDeclaredConstructors(Class.java:2671)
extractorapp_1 | 	at java.lang.Class.getDeclaredConstructors(Class.java:2020)
[...]
```

**Comment by pmauduit** [comment]
Since https://github.com/georchestra/georchestra/pull/1133

What is weird is:
- If the missing class was missing in our code, it should have broken at compilation time
- If it is needed by Spring, it should be available as transitive dependency

**Comment by fvanderbiest** [comment]
Indeed fixed, thanks !
https://sdi.georchestra.org/extractorapp/
