### ISSUE TITLE
Error occurred during a wro4j request handling

### ISSUE THREAD

**Issue by fvanderbiest** [georchestra/georchestra#1196]
In branch ```dockerize```, GN does not load :
```
proxy_1             | 2016-01-26 16:23:32 statistics [INFO] testadmin|2016/01/26|http://geonetwork:8080/geonetwork/static/gn_search_georchestra.js|geOrchestra
geonetwork_1        | 2016-01-26 16:23:32,085 ERROR [geonetwork.wro4j] - Error occurred during a wro4j request handling
geonetwork_1        | ro.isdc.wro.WroRuntimeException: No such group available in the model: srv_custom_style
geonetwork_1        | 	at ro.isdc.wro.model.group.processor.GroupsProcessor.process(GroupsProcessor.java:74)
geonetwork_1        | 	at ro.isdc.wro.cache.support.DefaultSynchronizedCacheStrategyDecorator.loadValue(DefaultSynchronizedCacheStrategyDecorator.java:101)
geonetwork_1        | 	at ro.isdc.wro.cache.support.DefaultSynchronizedCacheStrategyDecorator.loadValue(DefaultSynchronizedCacheStrategyDecorator.java:35)
geonetwork_1        | 	at ro.isdc.wro.cache.support.AbstractSynchronizedCacheStrategyDecorator.get(AbstractSynchronizedCacheStrategyDecorator.java:55)
geonetwork_1        | 	at ro.isdc.wro.manager.ResourceBundleProcessor.serveProcessedBundle(ResourceBundleProcessor.java:63)
geonetwork_1        | 	at ro.isdc.wro.manager.WroManager.process(WroManager.java:159)
geonetwork_1        | 	at ro.isdc.wro.http.WroFilter.processRequest(WroFilter.java:335)
geonetwork_1        | 	at ro.isdc.wro.http.WroFilter.doFilter(WroFilter.java:289)
```

**Comment by fvanderbiest** [comment]
Missing JS dependency.

In the geonetwork folder:
```
git submodule init
git submodule update --recursive
```

This fixed it.

**Comment by landryb** [comment]
https://github.com/georchestra/georchestra/issues/1120#issuecomment-160597655 was the same thing
