### ISSUE TITLE
[geoserver] NPE when accessing a workspace endpoint without args

### ISSUE THREAD

**Issue by landryb** [georchestra/georchestra#1224]
accessing the global endpoint gives a 'user-friendly' message:
```
<ServiceException code="MissingParameterValue" locator="request">
      Could not determine geoserver request from http request org.geoserver.monitor.MonitorServletRequest@6bf93b56
</ServiceException>
```
accessing a workspace endpoint (https://sdi.georchestra.org/geoserver/dem/wms) triggers an NPE..

```
2016-02-08 15:09:47,940 ERROR [geoserver.ows] -
java.lang.NullPointerException
        at org.geoserver.wms.WMSWorkspaceQualifier.qualifyRequest(WMSWorkspaceQualifier.java:28)
        at org.geoserver.ows.WorkspaceQualifyingCallback.serviceDispatched(WorkspaceQualifyingCallback.java:44)
        at org.geoserver.ows.Dispatcher.fireServiceDispatchedCallback(Dispatcher.java:582)
        at org.geoserver.ows.Dispatcher.service(Dispatcher.java:577)
        at org.geoserver.ows.Dispatcher.handleRequestInternal(Dispatcher.java:252)
        at org.springframework.web.servlet.mvc.AbstractController.handleRequest(AbstractController.java:153)

```

Easy to reproduce with 2.8.1 or 2.8.2..

**Comment by fvanderbiest** [comment]
> accessing the global endpoint gives a 'user-friendly' message:

It always did so, to my knowledge.

> accessing a workspace endpoint (https://sdi.georchestra.org/geoserver/dem/wms) triggers an NPE..

This is less than ideal, indeed. 
But this has to be reported upstream...

**Comment by landryb** [comment]
That's https://osgeo-org.atlassian.net/browse/GEOS-5680
