### ISSUE TITLE
Private layers extraction failure

### ISSUE THREAD

**Issue by fvanderbiest** [georchestra/georchestra#1230]
Tested on layer "protected vector layer", eg with this context https://sdi.georchestra.org/mapfishapp/map/41c543fb24044d1c19e71e4d9a9e64db (you should log in to see the layer)

Extraction of this layer yields:
```
Erreur d'accès à la couche: ci:protectedVectorLayer 
  <ul>
    <li>Serveur: https://sdi.georchestra.org/geoserver/wfs?</li>
    <li>Couche: ci:protectedVectorLayer</li>
    <li><pre><code style="font-size: 1.2em;"><![CDATA[java.lang.RuntimeException: java.util.NoSuchElementException: Could not aquire feature:java.io.IOException: org.xml.sax.SAXException: Server returned HTTP response code: 401 for URL: https://sdi.georchestra.org/geoserver/wfs?service=WFS&version=1.0.0&request=DescribeFeatureType&typeName=ci%3AprotectedVectorLayer
java.io.IOException: Server returned HTTP response code: 401 for URL: https://sdi.georchestra.org/geoserver/wfs?service=WFS&version=1.0.0&request=DescribeFeatureType&typeName=ci%3AprotectedVectorLayer
	at org.georchestra.extractorapp.ws.extractor.WfsExtractor$1.exceptionOccurred(WfsExtractor.java:232)
	at org.geotools.data.DataUtilities.visit(DataUtilities.java:2804)
	at org.geotools.data.store.DataFeatureCollection.accepts(DataFeatureCollection.java:458)
	at org.georchestra.extractorapp.ws.extractor.FileFeatureWriter.generateFiles(FileFeatureWriter.java:89)
	at org.georchestra.extractorapp.ws.extractor.WfsExtractor.extract(WfsExtractor.java:259)
	at org.georchestra.extractorapp.ws.extractor.task.ExtractionTask.extractWfsLayer(ExtractionTask.java:413)
	at org.georchestra.extractorapp.ws.extractor.task.ExtractionTask.run(ExtractionTask.java:114)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.util.NoSuchElementException: Could not aquire feature:java.io.IOException: org.xml.sax.SAXException: Server returned HTTP response code: 401 for URL: https://sdi.georchestra.org/geoserver/wfs?service=WFS&version=1.0.0&request=DescribeFeatureType&typeName=ci%3AprotectedVectorLayer
java.io.IOException: Server returned HTTP response code: 401 for URL: https://sdi.georchestra.org/geoserver/wfs?service=WFS&version=1.0.0&request=DescribeFeatureType&typeName=ci%3AprotectedVectorLayer
	at org.geotools.data.store.NoContentIterator.next(NoContentIterator.java:58)
	at org.geotools.data.store.NoContentIterator.next(NoContentIterator.java:43)
	at org.geotools.feature.collection.DelegateFeatureIterator.next(DelegateFeatureIterator.java:71)
	at org.geotools.data.DataUtilities.visit(DataUtilities.java:2798)
	... 10 more
Caused by: java.io.IOException: org.xml.sax.SAXException: Server returned HTTP response code: 401 for URL: https://sdi.georchestra.org/geoserver/wfs?service=WFS&version=1.0.0&request=DescribeFeatureType&typeName=ci%3AprotectedVectorLayer
java.io.IOException: Server returned HTTP response code: 401 for URL: https://sdi.georchestra.org/geoserver/wfs?service=WFS&version=1.0.0&request=DescribeFeatureType&typeName=ci%3AprotectedVectorLayer
	at org.geotools.xml.gml.FCBuffer.hasNext(FCBuffer.java:328)
	at org.geotools.data.wfs.v1_0_0.WFSFeatureReader.loadElement(WFSFeatureReader.java:189)
	at org.geotools.data.wfs.v1_0_0.WFSFeatureReader.hasNext(WFSFeatureReader.java:178)
	at org.geotools.data.wfs.v1_0_0.NonStrictWFSStrategy.createFeatureReaderGET(NonStrictWFSStrategy.java:156)
	at org.geotools.data.wfs.v1_0_0.NonStrictWFSStrategy.createFeatureReader(NonStrictWFSStrategy.java:117)
	at org.geotools.data.wfs.v1_0_0.NonStrictWFSStrategy.getFeatureReader(NonStrictWFSStrategy.java:77)
	at org.geotools.data.wfs.v1_0_0.WFS_1_0_0_DataStore.getFeatureReader(WFS_1_0_0_DataStore.java:856)
	at org.geotools.data.DefaultFeatureResults.reader(DefaultFeatureResults.java:215)
	at org.geotools.data.store.DataFeatureCollection.openIterator(DataFeatureCollection.java:231)
	at org.geotools.data.store.DataFeatureCollection.iterator(DataFeatureCollection.java:199)
	at org.geotools.data.store.DataFeatureCollection.features(DataFeatureCollection.java:188)
	at org.geotools.data.store.DataFeatureCollection.features(DataFeatureCollection.java:79)
	at org.geotools.data.DataUtilities.visit(DataUtilities.java:2794)
	... 10 more
Caused by: org.xml.sax.SAXException: Server returned HTTP response code: 401 for URL: https://sdi.georchestra.org/geoserver/wfs?service=WFS&version=1.0.0&request=DescribeFeatureType&typeName=ci%3AprotectedVectorLayer
java.io.IOException: Server returned HTTP response code: 401 for URL: https://sdi.georchestra.org/geoserver/wfs?service=WFS&version=1.0.0&request=DescribeFeatureType&typeName=ci%3AprotectedVectorLayer
	at org.geotools.xml.SchemaFactory.getRealInstance(SchemaFactory.java:308)
	at org.geotools.xml.SchemaFactory.getInstance(SchemaFactory.java:266)
	at org.geotools.xml.handlers.ElementHandlerFactory.startPrefixMapping(ElementHandlerFactory.java:88)
	at org.geotools.xml.XMLSAXHandler.startElement(XMLSAXHandler.java:371)
	at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.startElement(AbstractSAXParser.java:509)
	at com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl.scanStartElement(XMLNSDocumentScannerImpl.java:380)
	at com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl$NSContentDriver.scanRootElementHook(XMLNSDocumentScannerImpl.java:614)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl$FragmentContentDriver.next(XMLDocumentFragmentScannerImpl.java:3135)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl$PrologDriver.next(XMLDocumentScannerImpl.java:880)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(XMLDocumentScannerImpl.java:606)
	at com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl.next(XMLNSDocumentScannerImpl.java:118)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(XMLDocumentFragmentScannerImpl.java:510)
	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:848)
	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:777)
	at com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(XMLParser.java:141)
	at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(AbstractSAXParser.java:1213)
	at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl$JAXPSAXParser.parse(SAXParserImpl.java:642)
	at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl.parse(SAXParserImpl.java:326)
	at javax.xml.parsers.SAXParser.parse(SAXParser.java:195)
	at org.geotools.xml.DocumentFactory.getInstance(DocumentFactory.java:134)
	at org.geotools.data.wfs.v1_0_0.WFSFeatureReader.run(WFSFeatureReader.java:125)
Caused by: java.io.IOException: Server returned HTTP response code: 401 for URL: https://sdi.georchestra.org/geoserver/wfs?service=WFS&version=1.0.0&request=DescribeFeatureType&typeName=ci%3AprotectedVectorLayer
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1628)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:254)
	at com.sun.org.apache.xerces.internal.impl.XMLEntityManager.setupCurrentEntity(XMLEntityManager.java:646)
	at com.sun.org.apache.xerces.internal.impl.XMLVersionDetector.determineDocVersion(XMLVersionDetector.java:189)
	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:812)
	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:777)
	at com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(XMLParser.java:141)
	at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(AbstractSAXParser.java:1213)
	at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl$JAXPSAXParser.parse(SAXParserImpl.java:642)
	at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl.parse(SAXParserImpl.java:326)
	at javax.xml.parsers.SAXParser.parse(SAXParser.java:274)
	at org.geotools.xml.SchemaFactory.getRealInstance(SchemaFactory.java:306)
```

**Comment by fvanderbiest** [comment]
This is due to the GeoTools WFS store internals, not using the extractorapp-dedicated UA.

**Comment by fvanderbiest** [comment]
Same issue with mapfishapp's SLD service, which returns 
```
{"success":false, "error":"fileupload_error_ioError", "msg": "Could not aquire feature:java.io.IOException: org.xml.sax.SAXException: Server returned HTTP response code: 401 for URL: https://sdi.georchestra.org/geoserver/wfs?service=WFS&version=1.0.0&request=DescribeFeatureType&typeName=o%3Apoints_de_vente
java.io.IOException: Server returned HTTP response code: 401 for URL: https://sdi.georchestra.org/geoserver/wfs?service=WFS&version=1.0.0&request=DescribeFeatureType&typeName=o%3Apoints_de_vente"}
```
on feature classification

**Comment by Vampouille** [comment]
This is not related to user agent. geotools does not send any Authentification so it can't be pass through security proxy. We need to copy user auth as `Authentication : Basic xxxxxxx` header for all  geotools requests.

**Comment by Vampouille** [comment]
Credentials are already set here :

https://github.com/georchestra/georchestra/blob/master/extractorapp/src/main/java/org/georchestra/extractorapp/ws/extractor/WfsExtractor.java#L218-L219

It seem to be a bug in geotools, maybe this can help : https://osgeo-org.atlassian.net/browse/GEOT-2992

**Comment by Vampouille** [comment]
Maybe credentials are left during url reconstruction in this method : 
https://github.com/geotools/geotools/blob/9.2/modules/unsupported/wfs/src/main/java/org/geotools/data/wfs/v1_0_0/WFS_1_0_0_DataStore.java#L512

**Comment by Vampouille** [comment]
When extractor start a job, following request are sent to proxy :
```
GET /geoserver/wfs?request=GetFeature&SERVICE=WFS&VERSION=1.0.0...
Authorization: Basic xxxxxxx
User-Agent: Java/1.8.0_66-internal
```
This request is proxied a get a HTTP 200 OK

Next request : 
```
GET /geoserver/wfs?service=WFS&version=1.0.0&request=DescribeFeatureType...
User-Agent: Java/1.8.0_66-internal
```
This one does not contains credentials from extractor app but used same UA as geotools. This request get a HTTP 401 error.

**Comment by Vampouille** [comment]
Maybe we can add Authentication header in proxy when we detect request from extractor to geoserver

**Comment by pmauduit** [comment]
Kindof related problem in mapfishapp with classification:
https://github.com/georchestra/georchestra/blob/master/mapfishapp/src/main/java/org/georchestra/mapfishapp/ws/classif/SLDClassifier.java#L142 triggers a WFS DescribeFeatureType (authentified)

then https://github.com/georchestra/georchestra/blob/master/mapfishapp/src/main/java/org/georchestra/mapfishapp/ws/classif/SLDClassifier.java#L149-L150 seem to trigger 2 GetFeature (still with a basic-auth provided)

And actually https://github.com/georchestra/georchestra/blob/master/mapfishapp/src/main/java/org/georchestra/mapfishapp/ws/classif/SLDClassifier.java#L186 does another describeFeatureType BUT without the basic-auth provided ...

**Comment by pmauduit** [comment]
What I have found so far: The WFS plugin for GeoTools in 9.2 version is a real nightmare to debug (badly written and unmaintained anyway), there is another module which seems more reliable: wfs-ng. So, these are my thoughts:

- Drop wfs, and try using wfs-ng instead (it also exists in GT 9.2)
- Use ogr jni native bindings which surely use a more proven / stable implementation for WFS (I am personally more confident in the gdal/ogr project than in GeoTools, at least in regards of wfs implementation)
- Release with this current bug and consider migrating to a newer version of GT in extractorapp/mapfishapp, but the wfs code has not evolved so much between 9.2 and 14.x, so we should in addition use one of the 2 previous options even with bumping to a new version.

**Comment by fvanderbiest** [comment]
Fixed with https://github.com/georchestra/georchestra/issues/1267
