### ISSUE TITLE
GeoServer - building with extensions breaks several geoserver features

### ISSUE THREAD

**Issue by fvanderbiest** [georchestra/georchestra#1231]
Shapefile directory repository creation fails when several extensions are built with geoserver.
Tested on sdi.geor.org with GeoServer 2.8.1

```
org.apache.wicket.WicketRuntimeException: Method onFormSubmitted of interface org.apache.wicket.markup.html.form.IFormSubmitListener targeted at component [MarkupContainer [Component id = storeForm]] threw an exception
    at org.apache.wicket.RequestListenerInterface.invoke(RequestListenerInterface.java:193)
    at org.apache.wicket.request.target.component.listener.ListenerInterfaceRequestTarget.processEvents(ListenerInterfaceRequestTarget.java:73)
    at org.apache.wicket.request.AbstractRequestCycleProcessor.processEvents(AbstractRequestCycleProcessor.java:92)
    at org.apache.wicket.RequestCycle.processEventsAndRespond(RequestCycle.java:1250)
    at org.apache.wicket.RequestCycle.step(RequestCycle.java:1329)
    at org.apache.wicket.RequestCycle.steps(RequestCycle.java:1436)
    at org.apache.wicket.RequestCycle.request(RequestCycle.java:545)
    at org.apache.wicket.protocol.http.WicketFilter.doGet(WicketFilter.java:484)
    at org.apache.wicket.protocol.http.WicketServlet.doPost(WicketServlet.java:160)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:637)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:717)
    at org.springframework.web.servlet.mvc.ServletWrappingController.handleRequestInternal(ServletWrappingController.java:159)
    at org.springframework.web.servlet.mvc.AbstractController.handleRequest(AbstractController.java:153)
    at org.springframework.web.servlet.mvc.SimpleControllerHandlerAdapter.handle(SimpleControllerHandlerAdapter.java:48)
    at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:923)
    at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:852)
    at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:882)
    at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:789)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:637)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:717)
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:290)
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
    at org.geoserver.filters.ThreadLocalsCleanupFilter.doFilter(ThreadLocalsCleanupFilter.java:28)
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:235)
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
    at org.geoserver.filters.SpringDelegatingFilter$Chain.doFilter(SpringDelegatingFilter.java:75)
    at org.geoserver.wms.animate.AnimatorFilter.doFilter(AnimatorFilter.java:71)
    at org.geoserver.filters.SpringDelegatingFilter$Chain.doFilter(SpringDelegatingFilter.java:71)
    at org.geoserver.monitor.MonitorFilter.doFilter(MonitorFilter.java:89)
    at org.geoserver.filters.SpringDelegatingFilter$Chain.doFilter(SpringDelegatingFilter.java:71)
    at org.geoserver.flow.controller.IpBlacklistFilter.doFilter(IpBlacklistFilter.java:95)
    at org.geoserver.filters.SpringDelegatingFilter$Chain.doFilter(SpringDelegatingFilter.java:71)
    at org.geoserver.filters.SpringDelegatingFilter.doFilter(SpringDelegatingFilter.java:46)
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:235)
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
    at org.geoserver.platform.AdvancedDispatchFilter.doFilter(AdvancedDispatchFilter.java:50)
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:235)
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
    at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:311)
    at org.geoserver.security.filter.GeoServerCompositeFilter$NestedFilterChain.doFilter(GeoServerCompositeFilter.java:69)
    at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.invoke(FilterSecurityInterceptor.java:116)
    at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.doFilter(FilterSecurityInterceptor.java:83)
    at org.geoserver.security.filter.GeoServerCompositeFilter$NestedFilterChain.doFilter(GeoServerCompositeFilter.java:73)
    at org.geoserver.security.filter.GeoServerCompositeFilter.doFilter(GeoServerCompositeFilter.java:92)
    at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:323)
    at org.geoserver.security.filter.GeoServerCompositeFilter$NestedFilterChain.doFilter(GeoServerCompositeFilter.java:69)
    at org.springframework.security.web.access.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:113)
    at org.geoserver.security.filter.GeoServerCompositeFilter$NestedFilterChain.doFilter(GeoServerCompositeFilter.java:73)
    at org.geoserver.security.filter.GeoServerCompositeFilter.doFilter(GeoServerCompositeFilter.java:92)
    at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:323)
    at org.geoserver.security.filter.GeoServerAnonymousAuthenticationFilter.doFilter(GeoServerAnonymousAuthenticationFilter.java:54)
    at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:323)
    at org.geoserver.security.filter.GeoServerCompositeFilter$NestedFilterChain.doFilter(GeoServerCompositeFilter.java:69)
    at org.springframework.security.web.authentication.AbstractAuthenticationProcessingFilter.doFilter(AbstractAuthenticationProcessingFilter.java:182)
    at org.geoserver.security.filter.GeoServerCompositeFilter$NestedFilterChain.doFilter(GeoServerCompositeFilter.java:73)
    at org.geoserver.security.filter.GeoServerCompositeFilter.doFilter(GeoServerCompositeFilter.java:92)
    at org.geoserver.security.filter.GeoServerUserNamePasswordAuthenticationFilter.doFilter(GeoServerUserNamePasswordAuthenticationFilter.java:116)
    at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:323)
    at org.geoserver.security.filter.GeoServerPreAuthenticationFilter.doFilter(GeoServerPreAuthenticationFilter.java:75)
    at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:323)
    at org.geoserver.security.filter.GeoServerCompositeFilter$NestedFilterChain.doFilter(GeoServerCompositeFilter.java:69)
    at org.springframework.security.web.authentication.rememberme.RememberMeAuthenticationFilter.doFilter(RememberMeAuthenticationFilter.java:146)
    at org.geoserver.security.filter.GeoServerCompositeFilter$NestedFilterChain.doFilter(GeoServerCompositeFilter.java:73)
    at org.geoserver.security.filter.GeoServerCompositeFilter.doFilter(GeoServerCompositeFilter.java:92)
    at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:323)
    at org.geoserver.security.filter.GeoServerCompositeFilter$NestedFilterChain.doFilter(GeoServerCompositeFilter.java:69)
    at org.springframework.security.web.context.SecurityContextPersistenceFilter.doFilter(SecurityContextPersistenceFilter.java:87)
    at org.geoserver.security.filter.GeoServerSecurityContextPersistenceFilter$1.doFilter(GeoServerSecurityContextPersistenceFilter.java:53)
    at org.geoserver.security.filter.GeoServerCompositeFilter$NestedFilterChain.doFilter(GeoServerCompositeFilter.java:73)
    at org.geoserver.security.filter.GeoServerCompositeFilter.doFilter(GeoServerCompositeFilter.java:92)
    at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:323)
    at org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:173)
    at org.geoserver.security.GeoServerSecurityFilterChainProxy.doFilter(GeoServerSecurityFilterChainProxy.java:135)
    at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:346)
    at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:259)
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:235)
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
    at org.geoserver.filters.LoggingFilter.doFilter(LoggingFilter.java:87)
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:235)
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
    at org.geoserver.filters.GZIPFilter.doFilter(GZIPFilter.java:42)
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:235)
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
    at org.geoserver.filters.SessionDebugFilter.doFilter(SessionDebugFilter.java:48)
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:235)
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
    at org.geoserver.filters.FlushSafeFilter.doFilter(FlushSafeFilter.java:44)
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:235)
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
    at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:88)
    at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:76)
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:235)
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
    at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:233)
    at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:191)
    at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:127)
    at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:103)
    at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:109)
    at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:293)
    at org.apache.coyote.http11.Http11AprProcessor.process(Http11AprProcessor.java:879)
    at org.apache.coyote.http11.Http11AprProtocol$Http11ConnectionHandler.process(Http11AprProtocol.java:600)
    at org.apache.tomcat.util.net.AprEndpoint$Worker.run(AprEndpoint.java:1703)
    at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.reflect.InvocationTargetException
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at org.apache.wicket.RequestListenerInterface.invoke(RequestListenerInterface.java:182)
    ... 102 more
Caused by: java.lang.RuntimeException: Cannot instantiate extension point contributor org.geoserver.web.data.store.shape.ShapefileDirectoryEditPanel
    at org.geoserver.web.data.store.StoreExtensionPoints.getStoreEditPanel(StoreExtensionPoints.java:98)
    at org.geoserver.web.data.store.AbstractDataAccessPage.initUI(AbstractDataAccessPage.java:135)
    at org.geoserver.web.data.store.DataAccessNewPage.<init>(DataAccessNewPage.java:70)
    at org.geoserver.web.data.store.NewDataPage$1$1.onSubmit(NewDataPage.java:91)
    at org.apache.wicket.markup.html.form.Form.delegateSubmit(Form.java:1561)
    at org.apache.wicket.markup.html.form.Form.process(Form.java:958)
    at org.apache.wicket.markup.html.form.Form.onFormSubmitted(Form.java:920)
    ... 107 more
Caused by: java.lang.reflect.InvocationTargetException
    at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
    at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
    at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
    at org.geoserver.web.data.store.StoreExtensionPoints.getStoreEditPanel(StoreExtensionPoints.java:94)
    ... 113 more
Caused by: java.lang.NoSuchMethodError: org.slf4j.helpers.MessageFormatter.format(Ljava/lang/String;Ljava/lang/Object;)Lorg/slf4j/helpers/FormattingTuple;
    at org.slf4j.impl.Log4jLoggerAdapter.warn(Log4jLoggerAdapter.java:419)
    at org.apache.wicket.Localizer.getStringIgnoreSettings(Localizer.java:198)
    at org.apache.wicket.Localizer.getString(Localizer.java:313)
    at org.apache.wicket.model.StringResourceModel.getString(StringResourceModel.java:513)
    at org.apache.wicket.model.StringResourceModel.load(StringResourceModel.java:647)
    at org.apache.wicket.model.StringResourceModel.load(StringResourceModel.java:181)
    at org.apache.wicket.model.LoadableDetachableModel.getObject(LoadableDetachableModel.java:120)
    at org.geoserver.web.data.store.panel.FileParamPanel.<init>(FileParamPanel.java:61)
    at org.geoserver.web.data.store.panel.DirectoryParamPanel.<init>(DirectoryParamPanel.java:42)
    at org.geoserver.web.data.store.shape.ShapefileDirectoryEditPanel.buildFileParamPanel(ShapefileDirectoryEditPanel.java:33)
    at org.geoserver.web.data.store.shape.ShapefileStoreEditPanel.<init>(ShapefileStoreEditPanel.java:46)
    at org.geoserver.web.data.store.shape.ShapefileDirectoryEditPanel.<init>(ShapefileDirectoryEditPanel.java:29)
    ... 118 more
```

**Comment by fvanderbiest** [comment]
Same with shapefile repo.

**Comment by fvanderbiest** [comment]
Same with updated geOrchestra GeoServer 2.8.2 (master today)

**Comment by landryb** [comment]
Looks like a wicket-only issue, i had no issue creating datastores via REST

**Comment by fvanderbiest** [comment]
Critical issue ...

**Comment by fvanderbiest** [comment]
Seem to be due to an extension, since the page shows up OK when no extensions are activated in the build.

One of app-schema,arcsde,h2,sqlserver,mysql,db2,jp2k,gdal,feature-pregeneralized,imagemap,excel,charts,control-flow,wps,querylayer,teradata,monitor,security,xslt,inspire,css,csw,dxf,wcs2_0-eo,libjpeg-turbo,app-schema,spatialite,mbtiles,vectortiles,authkey,feature-aggregate,pyramid,sldservice,colormap,geopkg :-(

**Comment by fvanderbiest** [comment]
One of pyramid,inspire,wps,control-flow,monitor,csw

**Comment by fvanderbiest** [comment]
One of pyramid,wps,control-flow :-(

**Comment by fvanderbiest** [comment]
One of pyramid,wps

**Comment by fvanderbiest** [comment]
Fails with single WPS extension. But is it the only one culprit ?

**Comment by fvanderbiest** [comment]
Also fails with pyramid,inspire,control-flow,monitor,csw ...

**Comment by fvanderbiest** [comment]
pyramid is OK

**Comment by pierrejego** [comment]
Hello, this error is due to multiple log4j and slf4j version.
If you remove log4j-1.2.14.jar and slf4j-api-1.5.8.jar for geoserver/WEB-INF/lib/ it works.

Now I have to find how extension are build, and change pom.xml to have the same log4j and slf4j version for all.

**Comment by fvanderbiest** [comment]
> Hello, this error is due to multiple log4j and slf4j version.

Oh, I'm glad to hear you found the reason why it fails !
I did not see your comment before today.

**Comment by pmauduit** [comment]
I got it: the log4j slf4j versions are due to the presence of a runtime dependency in the GeoServer webapp here:

https://github.com/georchestra/georchestra/blob/15.12/geoserver/webapp/pom.xml#L17-L23

If really needed, the dependency should be bumped to `1.2.17`, to be coherent with the expected versions from GeoServer upstream. PR to come.

**Comment by pmauduit** [comment]
I was able to fix the log4j redundancy, but not the slf4j one, still investigating

**Comment by pmauduit** [comment]
Ok, found: https://github.com/apache/wicket/blob/wicket-1.4.12/pom.xml#L395-L404 ; here are the dependencies from GS:

```
[DEBUG]       org.geoserver.web:gs-web-core:jar:2.8.3:compile
[DEBUG]          org.apache.wicket:wicket:jar:1.4.12:compile
[DEBUG]             org.slf4j:slf4j-api:jar:1.5.8:compile
```

I cannot figure out why maven needs to get this version since gs-web-core should already provide the 1.6.4 one, and the only proper way to fix it seems to exclude the problematic version from the WAR at the maven-war-plugin level.
