### ISSUE TITLE
[https] Document how to add letsencrypt roots to tomcat keystore

### ISSUE THREAD

**Issue by landryb** [georchestra/georchestra#1242]
Spun of from https://github.com/georchestra/georchestra/pull/1175#discussion_r49424720 - since we now advertise https-only w/ potentially letsencrypt..

    

> More relevant point (since the doc mentionned letsencrypt above): The letsencrypt certificates might not be trusted by the JVM: http://stackoverflow.com/questions/34110426/does-java-support-lets-encrypt-certificates

Argh. That means if we want everyone to be able to communicate (ie harvest, use wxs services..) with https-only-with-letsencrypt-cert instances, we have to document/explain how to import LE's root cert in their tomcat's keystore, since we cant expect/rely on having java8 ?

I've tried loading https://sdi.georchestra.org/geoserver/wms service in a test instance, and it blows with a 503. Traceback:

```
2016-02-11 16:58:42 security [ERROR] Exception occured when trying to connect to the remote host:
javax.net.ssl.SSLPeerUnverifiedException: peer not authenticated
        at sun.security.ssl.SSLSessionImpl.getPeerCertificates(SSLSessionImpl.java:421)
        at org.apache.http.conn.ssl.AbstractVerifier.verify(AbstractVerifier.java:128)
        at org.apache.http.conn.ssl.SSLSocketFactory.connectSocket(SSLSocketFactory.java:572)
        at org.apache.http.impl.conn.DefaultClientConnectionOperator.openConnection(DefaultClientConnectionOperator.java:180)
        at org.apache.http.impl.conn.ManagedClientConnectionImpl.open(ManagedClientConnectionImpl.java:294)
        at org.apache.http.impl.client.DefaultRequestDirector.tryConnect(DefaultRequestDirector.java:640)
        at org.apache.http.impl.client.DefaultRequestDirector.execute(DefaultRequestDirector.java:479)
        at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:906)
        at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:805)
        at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:784)
        at org.georchestra.security.Proxy.executeHttpRequest(Proxy.java:754)
```

I think that's different from the SNI issue i had with GN3, it's more we need to find a way to add letsencrypt validation chain to the keystore.... tried various things that failed so far, but will try harder now.

**Comment by landryb** [comment]
Note that our proxy uses httpclient-4.2.1, mapfishapp uses 4.2.5, might be worth updating it to 4.3.2 to fix at least the SNI issue..

**Comment by landryb** [comment]
Hm. After *adding* the locally-generated/signed cert to a copy of the regular cacerts keystore file shipped in /etc/ssl/certs/java/cacerts by the debian package containing the proper signer for LE:
```
debian:dst_root_ca_x3.pem, Nov 9, 2015, trustedCertEntry,
Certificate fingerprint (SHA1): DA:C9:02:4F:54:D8:F6:DF:94:93:5F:B1:73:26:38:CA:6A:D7:7C:13
```
, i can browse sdi.georchestra.ogr/geoserver/wms from mfapp. Will recheck our documentation about that ...

**Comment by landryb** [comment]
Okay, 39f68e8e67bc7cdefc1996bec2e8f676787d5d44 actually took care of explaining how to properly do this. I feel stupid now :)
