### ISSUE TITLE
ldapadmin - nested groups might break the app

### ISSUE THREAD

**Issue by fvanderbiest** [georchestra/georchestra#1299]
In case one creates a group named `MOD` or `SV` in the default georchestra LDAP tree, privateui is broken.

This is because groups such as `MOD_ANALYTICS` or `SV_USER` already exist.

```
TypeError: Cannot read property 'push' of undefined
    at addNode (https://georchestra1512.mutu.local/ldapadmin/privateui/js/controllers.js:494:17)
    at https://georchestra1512.mutu.local/ldapadmin/privateui/js/controllers.js:32:9
    at Array.forEach (native)
    at Object.n [as forEach] (https://ajax.googleapis.com/ajax/libs/angularjs/1.1.5/angular.min.js:6:470)
    at Restangular.all.getList.then.flash.error (https://georchestra1512.mutu.local/ldapadmin/privateui/js/controllers.js:31:15)
    at i (https://ajax.googleapis.com/ajax/libs/angularjs/1.1.5/angular.min.js:79:437)
    at https://ajax.googleapis.com/ajax/libs/angularjs/1.1.5/angular.min.js:80:485
    at Object.e.$eval (https://ajax.googleapis.com/ajax/libs/angularjs/1.1.5/angular.min.js:92:272)
    at Object.e.$digest (https://ajax.googleapis.com/ajax/libs/angularjs/1.1.5/angular.min.js:90:142)
    at Object.e.$apply (https://ajax.googleapis.com/ajax/libs/angularjs/1.1.5/angular.min.js:92:431)
```

**Comment by fvanderbiest** [comment]
This is critical if one wants to have the console webapp and ldapadmin privateui with the same LDAP tree.

**Comment by tonio** [comment]
See https://github.com/georchestra/georchestra/pull/1387/commits/790c337515bab366f73a76b3fa82f31ee5aa1624 (part of #1387).

**Comment by fvanderbiest** [comment]
Merged to master, deployed to demo, works great.
Thanks @tonio 

![capture du 2016-06-07 11 44 13](https://cloud.githubusercontent.com/assets/265319/15853407/2f1671d0-2ca5-11e6-971e-3ab4756bd6bc.png)
