### ISSUE TITLE
GeoNetwork - Missing repository

### ISSUE THREAD

**Issue by GuillaumeSmaha** [georchestra/georchestra#1359]
Hi,
On the branch 15.12, there are missing these repository in GeoNetwork : https://raw.githubusercontent.com/geonetwork/core-maven-repo/master

The link returns "400: Invalid request"

**Comment by fvanderbiest** [comment]
Hi Guillaume, thanks for the report.

The main pom indeed refrences this repo (see https://github.com/georchestra/geonetwork/blob/georchestra-gn3-15.12/pom.xml#L1100-L1110)

... but it seems OK to me, see eg https://raw.githubusercontent.com/geonetwork/core-maven-repo/master/README.md

Can you explain what is your problem ? Thanks.

**Comment by GuillaumeSmaha** [comment]
Maven can't resolve a dependence in this repository https://raw.githubusercontent.com/geonetwork/core-maven-repo/master/

    [ERROR] Failed to execute goal on project core: Could not resolve dependencies for project org.geonetwork-opensource:core:jar:3.0.4-SNAPSHOT: Could not find artifact org.geonetwork-opensource:domain:jar:tests:3.0.4-SNAPSHOT in core-maven-repo (https://raw.githubusercontent.com/geonetwork/core-maven-repo/master) -> [Help 1]

The error in debug mode :

    [INFO] ------------------------------------------------------------------------
    [INFO] BUILD FAILURE
    [INFO] ------------------------------------------------------------------------
    [INFO] Total time: 02:59 min
    [INFO] Finished at: 2016-04-14T10:33:51+00:00
    [INFO] Final Memory: 247M/4272M
    [INFO] ------------------------------------------------------------------------
    [ERROR] Failed to execute goal on project core: Could not resolve dependencies for project org.geonetwork-opensource:core:jar:3.0.4-SNAPSHOT: Failure to find org.geonetwork-opensource:domain:jar:tests:3.0.4-SNAPSHOT in https://raw.githubusercontent.com/geonetwork/core-maven-repo/master was cached in the local repository, resolution will not be reattempted until the update interval of core-maven-repo has elapsed or updates are forced -> [Help 1]
    org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal on project core: Could not resolve dependencies for project org.geonetwork-opensource:core:jar:3.0.4-SNAPSHOT: Failure to find org.geonetwork-opensource:domain:jar:tests:3.0.4-SNAPSHOT in https://raw.githubusercontent.com/geonetwork/core-maven-repo/master was cached in the local repository, resolution will not be reattempted until the update interval of core-maven-repo has elapsed or updates are forced
        at org.apache.maven.lifecycle.internal.LifecycleDependencyResolver.getDependencies(LifecycleDependencyResolver.java:220)
        at org.apache.maven.lifecycle.internal.LifecycleDependencyResolver.resolveProjectDependencies(LifecycleDependencyResolver.java:127)
        at org.apache.maven.lifecycle.internal.MojoExecutor.ensureDependenciesAreResolved(MojoExecutor.java:257)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:200)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
        at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
        at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:120)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:355)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:155)
        at org.apache.maven.cli.MavenCli.execute(MavenCli.java:584)
        at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:216)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:160)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
    Caused by: org.apache.maven.project.DependencyResolutionException: Could not resolve dependencies for project org.geonetwork-opensource:core:jar:3.0.4-SNAPSHOT: Failure to find org.geonetwork-opensource:domain:jar:tests:3.0.4-SNAPSHOT in https://raw.githubusercontent.com/geonetwork/core-maven-repo/master was cached in the local repository, resolution will not be reattempted until the update interval of core-maven-repo has elapsed or updates are forced
        at org.apache.maven.project.DefaultProjectDependenciesResolver.resolve(DefaultProjectDependenciesResolver.java:211)
        at org.apache.maven.lifecycle.internal.LifecycleDependencyResolver.getDependencies(LifecycleDependencyResolver.java:195)
        ... 22 more
    Caused by: org.eclipse.aether.resolution.DependencyResolutionException: Failure to find org.geonetwork-opensource:domain:jar:tests:3.0.4-SNAPSHOT in https://raw.githubusercontent.com/geonetwork/core-maven-repo/master was cached in the local repository, resolution will not be reattempted until the update interval of core-maven-repo has elapsed or updates are forced
        at org.eclipse.aether.internal.impl.DefaultRepositorySystem.resolveDependencies(DefaultRepositorySystem.java:384)
        at org.apache.maven.project.DefaultProjectDependenciesResolver.resolve(DefaultProjectDependenciesResolver.java:205)
        ... 23 more
    Caused by: org.eclipse.aether.resolution.ArtifactResolutionException: Failure to find org.geonetwork-opensource:domain:jar:tests:3.0.4-SNAPSHOT in https://raw.githubusercontent.com/geonetwork/core-maven-repo/master was cached in the local repository, resolution will not be reattempted until the update interval of core-maven-repo has elapsed or updates are forced
        at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:444)
        at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolveArtifacts(DefaultArtifactResolver.java:246)
        at org.eclipse.aether.internal.impl.DefaultRepositorySystem.resolveDependencies(DefaultRepositorySystem.java:367)
        ... 24 more
    Caused by: org.eclipse.aether.transfer.ArtifactNotFoundException: Failure to find org.geonetwork-opensource:domain:jar:tests:3.0.4-SNAPSHOT in https://raw.githubusercontent.com/geonetwork/core-maven-repo/master was cached in the local repository, resolution will not be reattempted until the update interval of core-maven-repo has elapsed or updates are forced
        at org.eclipse.aether.internal.impl.DefaultUpdateCheckManager.newException(DefaultUpdateCheckManager.java:231)
        at org.eclipse.aether.internal.impl.DefaultUpdateCheckManager.checkArtifact(DefaultUpdateCheckManager.java:206)
        at org.eclipse.aether.internal.impl.DefaultArtifactResolver.gatherDownloads(DefaultArtifactResolver.java:585)
        at org.eclipse.aether.internal.impl.DefaultArtifactResolver.performDownloads(DefaultArtifactResolver.java:503)
        at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:421)
        ... 26 more
    [ERROR] 
    [ERROR] 
    [ERROR] For more information about the errors and possible solutions, please read the following articles:
    [ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException
    [ERROR] 
    [ERROR] After correcting the problems, you can resume the build with the command
    [ERROR]   mvn <goals> -rf :core

**Comment by fvanderbiest** [comment]
Did you build with -DskipTests=true or -Dmaven.test.skip=true ?

**Comment by GuillaumeSmaha** [comment]
I build with /mvn -X -Dmaven.test.skip=true -Dserver=myprofile install

**Comment by fvanderbiest** [comment]
Give it a try with `-DskipTests=true`

**Comment by jdenisgiguere** [comment]
See https://github.com/georchestra/georchestra/blob/15.12/doc/build.md#build-the-modules .

**Comment by GuillaumeSmaha** [comment]
When I execute

    cd geonetwork
    ../mvn -DskipTests clean install

I obtain this error :

    [INFO] GeoNetwork Web module .............................. SUCCESS [ 40.897 s]
    [INFO] GeoNetwork E2E Javascript Tests .................... SUCCESS [  0.014 s]
    [INFO] GeoServer module ................................... FAILURE [01:00 min]
    [INFO] ------------------------------------------------------------------------
    [ERROR] Failed to execute goal on project geoserver: Could not resolve dependencies for project org.geonetwork-opensource:geoserver:war:3.0.4-SNAPSHOT: Could not transfer artifact org.geoserver:geoserver:war:2.5.2 from/to core-maven-repo (https://raw.githubusercontent.com/geonetwork/core-maven-repo/master): Failed to transfer file: https://raw.githubusercontent.com/geonetwork/core-maven-repo/master/org/geoserver/geoserver/2.5.2/geoserver-2.5.2.war. Return code is: 503 , ReasonPhrase:backend read error. -> [Help 1]

But if I run :

    cd ..
    ./mvn -Dmaven.test.skip=true -Dserver=myprofile clean install

All build success.
Thank for your help =)
