### ISSUE TITLE
Error after docker image upgrade

### ISSUE THREAD

**Issue by fvanderbiest** [georchestra/georchestra#1441]
```
HTTP ERROR 500

Problem accessing /mapfishapp/. Reason:

    Server Error
Caused by:

org.apache.jasper.JasperException: java.lang.ClassNotFoundException: org.apache.jsp.WEB_002dINF.jsp.index_jsp
    at org.apache.jasper.servlet.JspServletWrapper.getServlet(JspServletWrapper.java:176)
    at org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:375)
    at org.apache.jasper.servlet.JspServlet.serviceJspFile(JspServlet.java:396)
    at org.apache.jasper.servlet.JspServlet.service(JspServlet.java:340)
    at org.eclipse.jetty.jsp.JettyJspServlet.service(JettyJspServlet.java:108)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
    at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:845)
    at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:583)
[...]
    at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.executeProduceConsume(ExecuteProduceConsume.java:303)
    at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.produceConsume(ExecuteProduceConsume.java:148)
    at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.run(ExecuteProduceConsume.java:136)
    at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:671)
    at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:589)
    at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.ClassNotFoundException: org.apache.jsp.WEB_002dINF.jsp.index_jsp
    at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
    at org.apache.jasper.servlet.JasperLoader.loadClass(JasperLoader.java:131)
    at org.apache.jasper.servlet.JasperLoader.loadClass(JasperLoader.java:62)
    at org.apache.tomcat.SimpleInstanceManager.newInstance(SimpleInstanceManager.java:51)
    at org.apache.jasper.servlet.JspServletWrapper.getServlet(JspServletWrapper.java:171)
    ... 69 more
Caused by:

java.lang.ClassNotFoundException: org.apache.jsp.WEB_002dINF.jsp.index_jsp
    at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
    at org.apache.jasper.servlet.JasperLoader.loadClass(JasperLoader.java:131)
    at org.apache.jasper.servlet.JasperLoader.loadClass(JasperLoader.java:62)
    at org.apache.tomcat.SimpleInstanceManager.newInstance(SimpleInstanceManager.java:51)
    at org.apache.jasper.servlet.JspServletWrapper.getServlet(JspServletWrapper.java:171)
    at org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:375)
    at org.apache.jasper.servlet.JspServlet.serviceJspFile(JspServlet.java:396)
[...]
    at org.eclipse.jetty.io.SelectChannelEndPoint$2.run(SelectChannelEndPoint.java:93)
    at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.executeProduceConsume(ExecuteProduceConsume.java:303)
    at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.produceConsume(ExecuteProduceConsume.java:148)
    at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.run(ExecuteProduceConsume.java:136)
    at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:671)
    at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:589)
    at java.lang.Thread.run(Thread.java:745)
Powered by Jetty:// 9.3.10.v20160621
```

**Comment by fvanderbiest** [comment]
java.lang.ClassNotFoundException often means that the jsp file failed to compile. 
Might be because Java code in scriptlets <% %> contains syntax errors.
To be checked ...

**Comment by Vampouille** [comment]
I have same issue in production, but restarting docker container fix http 500 error. We need to investigate.

**Comment by fvanderbiest** [comment]
> Might be because Java code in scriptlets <% %> contains syntax errors.

File to watch for syntax errors : https://github.com/georchestra/georchestra/blob/15.12/mapfishapp/src/main/filtered-resources/WEB-INF/jsp/index.jsp

@Vampouille @pmauduit do you spot errors in this file ?

**Comment by pmauduit** [comment]
> I have same issue in production, but restarting docker container fix http 500 error. We need to investigate.

Just a random thought on this issue: I wonder if when we activate the extra modules for jetty, a deploy process of the webapps is still launched, then killed when the module activation finishes, leaving the deploy in an inconsistant state jetty-side. It might explain the observed behaviour.

**Comment by Vampouille** [comment]
> @Vampouille @pmauduit can you spot errors in this file ?

My ide complain about incompatible cast between Boolean and boolean, but it's valid in a test class run with java8...

**Comment by fvanderbiest** [comment]
> My ide complain about incompatible cast between Boolean and boolean,

OK, thanks for testing.
Feel free to update the file if needed...

**Comment by pmauduit** [comment]
> @Vampouille @pmauduit can you spot errors in this file ?

Files nested in filtered-resources are supposed to be copied / replaced at build time (into target/). This comes with the config.jar process. So the file is probably invalid (because of missing maven substitutions)

**Comment by Vampouille** [comment]
J'ai ajouté une erreur de syntaxe et j'obtient : 
```
org.apache.jasper.JasperException: Unable to compile class for JSP: 
An error occurred at line: [20] in the generated java file:
```
L'erreur est explicite

**Comment by fvanderbiest** [comment]
Might be related with package renaming error in index.jsp, see a comparison between mapfishapp's index.jsp and extractorapp's index.jsp:
![capture du 2016-10-11 11 43 48](https://cloud.githubusercontent.com/assets/265319/19266067/28013c34-8fa8-11e6-84f8-47f2ba843cde.png)

**Comment by fvanderbiest** [comment]
Trying with https://github.com/georchestra/georchestra/commit/8ff15eef7a0b91bde0743cca3dab61062774cf5e

**Comment by pmauduit** [comment]
Should not fix the current issue: the reason because it was still `mapfishapp.i18n.index` in the jsp code was that the path `mapfishapp/i18n/index_*.properties` is coherent in mapfishapp:

https://github.com/georchestra/georchestra/tree/15.12/mapfishapp/src/main/resources/mapfishapp/i18n

In extractorapp, it has been moved onto `org/georchestra/extractorapp/`:

https://github.com/georchestra/georchestra/tree/15.12/extractorapp/src/main/resources/org/georchestra/extractorapp

**Comment by fvanderbiest** [comment]
Also to consider ...
![capture du 2016-10-11 13 38 08](https://cloud.githubusercontent.com/assets/265319/19268977/fb8b2bdc-8fb7-11e6-8836-60ea273be661.png)

**Comment by fvanderbiest** [comment]
Happening again on current master & annoying because it delays a lot upgrades...

**Comment by pmauduit** [comment]
Can you point the docker image tag where you encountered the issue ? I just tried with the last one from the c2c private repository and I was not able to reproduce

**Comment by fvanderbiest** [comment]
STR: Delete the mapfishapp container on GGE then, while rancher says it is initializing, load https://GGE/mapfishapp/ and you will see this:
![screenshot from 2018-06-21 11-48-01](https://user-images.githubusercontent.com/265319/41711680-fa463a64-7548-11e8-9b99-98fd75f846e2.png)

Juste tested at the moment.

**Comment by pmauduit** [comment]
Things that comes to my mind:

* /tmp/jetty might be persisted in a volume, a previous deploy from an older docker image could pollute a newer one
* is the mapfishapp webapp dezipped or available as a directory in /var/lib/jetty/webapps ? (related to previous point)

**Comment by fvanderbiest** [comment]
> /tmp/jetty might be persisted in a volume, a previous deploy from an older docker image could pollute a newer one

Also [true](https://github.com/georchestra/georchestra/blob/a36911b28ec2a6cd539481958fadcddab20972f8/extractorapp/src/docker/Dockerfile#L24) for extractorapp 17.12, but we do not witness the same behavior

**Comment by fvanderbiest** [comment]
> is the mapfishapp webapp dezipped or available as a directory in /var/lib/jetty/webapps ? (related to the previous point)

Yes on master, https://github.com/georchestra/georchestra/blob/666c0f917567f5d220a6c5368c47f1b5867fe89d/mapfishapp/src/docker/Dockerfile#L16-L18

**Comment by fvanderbiest** [comment]
Issue has not shown up for a long time, closing.
