### ISSUE TITLE
doc - how to upgrade database

### ISSUE THREAD

**Issue by fvanderbiest** [georchestra/georchestra#1595]
eg for analytics / extractorapp :
```
Caused by: org.postgresql.util.PSQLException: ERROR: relation &quot;extractorapp.extractor_layer_log&quot; does not exist
  Position: 60
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2182)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:1911)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:173)
	at org.postgresql.jdbc2.AbstractJdbc2Statement.execute(AbstractJdbc2Statement.java:645)
	at org.postgresql.jdbc2.AbstractJdbc2Statement.executeWithFlags(AbstractJdbc2Statement.java:495)
	at org.postgresql.jdbc2.AbstractJdbc2Statement.executeQuery(AbstractJdbc2Statement.java:380)
	at org.apache.commons.dbcp.DelegatingPreparedStatement.executeQuery(DelegatingPreparedStatement.java:93)
	at org.apache.commons.dbcp.DelegatingPreparedStatement.executeQuery(DelegatingPreparedStatement.java:93)
	at org.hibernate.engine.jdbc.internal.ResultSetReturnImpl.extract(ResultSetReturnImpl.java:70)
	... 105 more
</pre>
<h3>Caused by:</h3><pre>org.springframework.dao.InvalidDataAccessResourceUsageException: could not extract ResultSet; SQL [n/a]; nested exception is org.hibernate.exception.SQLGrammarException: could not extract ResultSet
	at org.springframework.orm.jpa.vendor.HibernateJpaDialect.convertHibernateAccessException(HibernateJpaDialect.java:238)
```

**Comment by Vampouille** [comment]
We need to add this file for migration : 
https://github.com/georchestra/georchestra/blob/master/postgresql/09-extractor-app.sql

**Comment by Vampouille** [comment]
We need to compare : 
* https://github.com/georchestra/georchestra/tree/15.12/postgresql
* https://github.com/georchestra/georchestra/tree/master/postgresql

**Comment by Vampouille** [comment]
After looking difference between 15.12 and master, I found : 

* 07-atlas.sql
* 09-extractor-app.sql

So upgrade instruction should looks like : 

> In order to update database schema between 15.12 and 16.12, you need to run 2 sql files into your current database : 07-atlas.sql and 09-extractor-app.sql
> Some tables will also be created by ldapadmin webapps : ldapadmin.admin_attachments, ldapadmin.admin_emails, ldapadmin.admin_emails_attachments, ldapadmin.admin_log, ldapadmin.email_template.

**Comment by fvanderbiest** [comment]
The migration script is provided in the `migrations` folder: https://github.com/georchestra/georchestra/blob/97efd350a4ab192bf39701232a9c1c58bfc16103/migrations/16.12/upgrade_database_from_15.12_to_16.12.sql

The upgrade notes will mention it.
