### ISSUE TITLE
console - org.apache.jasper.JasperException - /WEB-INF/views/consoleUi.jsp - File /index.html not found

### ISSUE THREAD

**Issue by fvanderbiest** [georchestra/georchestra#1617]
while testing the docker composition on master, on http://localhost:8080/ldapadmin/console/
```
** Root cause is: /WEB-INF/views/consoleUi.jsp (line: 1, column: 2) File [../../console/public/index.html] not found
org.apache.jasper.JasperException: /WEB-INF/views/consoleUi.jsp (line: 1, column: 2) File [../../console/public/index.html] not found
	at org.apache.jasper.compiler.DefaultErrorHandler.jspError(DefaultErrorHandler.java:41)
	at org.apache.jasper.compiler.ErrorDispatcher.dispatch(ErrorDispatcher.java:275)
	at org.apache.jasper.compiler.ErrorDispatcher.jspError(ErrorDispatcher.java:91)
	at org.apache.jasper.compiler.Parser.processIncludeDirective(Parser.java:333)
	at org.apache.jasper.compiler.Parser.parseIncludeDirective(Parser.java:368)
	at org.apache.jasper.compiler.Parser.parseDirective(Parser.java:471)
	at org.apache.jasper.compiler.Parser.parseFileDirectives(Parser.java:1787)
	at org.apache.jasper.compiler.Parser.parse(Parser.java:136)
	at org.apache.jasper.compiler.ParserController.doParse(ParserController.java:227)
	at org.apache.jasper.compiler.ParserController.parseDirectives(ParserController.java:117)
	at org.apache.jasper.compiler.Compiler.generateJava(Compiler.java:194)
	at org.apache.jasper.compiler.Compiler.compile(Compiler.java:356)
	at org.apache.jasper.compiler.Compiler.compile(Compiler.java:336)
	at org.apache.jasper.compiler.Compiler.compile(Compiler.java:323)
	at org.apache.jasper.JspCompilationContext.compile(JspCompilationContext.java:585)
	at org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:363)
	at org.apache.jasper.servlet.JspServlet.serviceJspFile(JspServlet.java:396)
	at org.apache.jasper.servlet.JspServlet.service(JspServlet.java:340)
	at org.eclipse.jetty.jsp.JettyJspServlet.service(JettyJspServlet.java:112)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
```

**Comment by fvanderbiest** [comment]
looks like an issue with the new CI (missing packages to build ?) because index.html cannot be found in the docker image:

```
$ docker exec -it georchestra_ldapadmin_1 bash
root@ec9f1134199e:/var/lib/jetty# find / -name index.html
/tmp/jetty/jetty-0.0.0.0-8080-ldapadmin.war-_ldapadmin-any-4895180604041945012.dir/webapp/console/app/assets/index.html
/tmp/jetty/jetty-0.0.0.0-8080-ldapadmin.war-_ldapadmin-any-4895180604041945012.dir/webapp/privateui/lib/angular/docs/partials/guide/index.html
/tmp/jetty/jetty-0.0.0.0-8080-ldapadmin.war-_ldapadmin-any-4895180604041945012.dir/webapp/privateui/lib/angular/docs/partials/api/index.html
/tmp/jetty/jetty-0.0.0.0-8080-ldapadmin.war-_ldapadmin-any-4895180604041945012.dir/webapp/privateui/lib/angular/docs/partials/cookbook/index.html
/tmp/jetty/jetty-0.0.0.0-8080-ldapadmin.war-_ldapadmin-any-4895180604041945012.dir/webapp/privateui/lib/angular/docs/partials/tutorial/index.html
/tmp/jetty/jetty-0.0.0.0-8080-ldapadmin.war-_ldapadmin-any-4895180604041945012.dir/webapp/privateui/lib/angular/docs/index.html
/tmp/jetty/jetty-0.0.0.0-8080-ldapadmin.war-_ldapadmin-any-4895180604041945012.dir/webapp/privateui/index.html
/usr/share/doc/adduser/examples/adduser.local.conf.examples/skel.other/index.html
/usr/share/doc/java-common/debian-java-faq/index.html
/usr/share/doc/java-common/debian-java-policy/index.html
```

**Comment by pmauduit** [comment]
Fixed with previous commit:

```
root@0b40f8e79953:/var/lib/jetty/webapps# find . -name index.html
./console/app/assets/index.html
./console/public/index.html
./privateui/lib/angular/docs/partials/guide/index.html
./privateui/lib/angular/docs/partials/api/index.html
./privateui/lib/angular/docs/partials/cookbook/index.html
./privateui/lib/angular/docs/partials/tutorial/index.html
./privateui/lib/angular/docs/index.html
./privateui/index.html
```
