### ISSUE TITLE
Erreur avec addon extraction

### ISSUE THREAD

**Issue by jusabatier** [georchestra/georchestra#1783]
En voulant utiliser l'addon d'extraction de mapfishapp, l'xtraction de la couche a échoué avec ceci dans les logs extractorapp : 

> 2017-09-22 09:08:01 task [ERROR] Exception occurred while extracting data
> java.lang.RuntimeException: org.geotools.data.DataSourceException: could not determine namespace bound to element prefix null (position: START_TAG seen ...<gml:featureMembers><null:cameras gml:id="cameras.23">... @1:1396) 
> 	at org.geotools.data.store.ContentFeatureCollection.size(ContentFeatureCollection.java:251)
> 	at org.georchestra.extractorapp.ws.extractor.WfsExtractor.extract(WfsExtractor.java:286)
> 	at org.georchestra.extractorapp.ws.extractor.task.ExtractionTask.extractWfsLayer(ExtractionTask.java:365)
> 	at org.georchestra.extractorapp.ws.extractor.task.ExtractionTask.run(ExtractionTask.java:132)
> 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
> 	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
> 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
> 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
> 	at java.lang.Thread.run(Thread.java:745)
> Caused by: org.geotools.data.DataSourceException: could not determine namespace bound to element prefix null (position: START_TAG seen ...<gml:featureMembers><null:cameras gml:id="cameras.23">... @1:1396) 
> 	at org.geotools.data.wfs.internal.parsers.XmlSimpleFeatureParser.parse(XmlSimpleFeatureParser.java:214)
> 	at org.geotools.data.wfs.impl.WFSFeatureReader.<init>(WFSFeatureReader.java:43)
> 	at org.geotools.data.wfs.impl.WFSContentFeatureSource.getReaderInternal(WFSContentFeatureSource.java:216)
> 	at org.geotools.data.store.ContentFeatureSource.getReader(ContentFeatureSource.java:562)
> 	at org.geotools.data.store.ContentFeatureCollection.size(ContentFeatureCollection.java:242)
> 	... 8 more
> Caused by: org.xmlpull.v1.XmlPullParserException: could not determine namespace bound to element prefix null (position: START_TAG seen ...<gml:featureMembers><null:cameras gml:id="cameras.23">... @1:1396) 
> 	at org.xmlpull.mxp1.MXParser.parseStartTag(MXParser.java:1816)
> 	at org.xmlpull.mxp1.MXParser.nextImpl(MXParser.java:1259)
> 	at org.xmlpull.mxp1.MXParser.next(MXParser.java:1093)
> 	at org.geotools.data.wfs.internal.parsers.XmlSimpleFeatureParser.seekFeature(XmlSimpleFeatureParser.java:850)
> 	at org.geotools.data.wfs.internal.parsers.XmlSimpleFeatureParser.parse(XmlSimpleFeatureParser.java:184)
> 	... 12 more

Visiblement un problème avec le namespace qui est à null.
Une idée de ce qui peut provoquer ça ? Bug ?

**Comment by fvanderbiest** [comment]
Je n'ai plus la référence en tête, mais c'est très probablement un bug geoserver qui a été corrigé dans les versions les plus récentes.

**Comment by fvanderbiest** [comment]
![capture du 2018-03-19 09-37-10](https://user-images.githubusercontent.com/265319/37585444-6324d034-2b59-11e8-98e3-25c97a284b5f.png)

https://www.slideshare.net/geosolutions/state-of-geoserver-21geoservernodeopts2
