### ISSUE TITLE
mapfishapp - remove test_windmill

### ISSUE THREAD

**Issue by pmauduit** [georchestra/georchestra#1804]
I am not sure anybody still knows how to use this tool, which does not seem to work anymore:

```
% python go-windmill.py env
New python executable in env/bin/python
Traceback (most recent call last):
  File "/home/pmauduit/projects/georchestra/georchestra/mapfishapp/test_windmill/env/lib/python2.7/site.py", line 67, in <module>
    import os
  File "/home/pmauduit/projects/georchestra/georchestra/mapfishapp/test_windmill/env/lib/python2.7/os.py", line 49, in <module>
    import posixpath as path
  File "/home/pmauduit/projects/georchestra/georchestra/mapfishapp/test_windmill/env/lib/python2.7/posixpath.py", line 17, in <module>
    import warnings
ImportError: No module named warnings
ERROR: The executable env/bin/python is not functioning
```
I think we can safely remove it from the repository.

**Comment by fvanderbiest** [comment]
+1
