### ISSUE TITLE
console JS build - TypeError: Cannot read property 'close' of undefined

### ISSUE THREAD

**Issue by fvanderbiest** [georchestra/georchestra#1895]
```
[INFO] 06 Feb 16:55:52 - info: compiling
[ERROR] 06 Feb 16:55:52 - error: { [Error: watch app/services/logs.es6 ENOSPC]
[ERROR]   code: 'ENOSPC',
[ERROR]   errno: 'ENOSPC',
[ERROR]   syscall: 'watch app/services/logs.es6',
[ERROR]   filename: 'app/services/logs.es6' }
[ERROR] /home/fvanderbiest/workspace/georchestra/georchestra/ldapadmin/src/main/webapp/console/node_modules/brunch/node_modules/chokidar/lib/nodefs-handler.js:77
[ERROR]     return watcher.close.bind(watcher);
[ERROR]                   ^
[ERROR] 
[ERROR] TypeError: Cannot read property 'close' of undefined
[ERROR]   at setFsWatchListener (/home/fvanderbiest/workspace/georchestra/georchestra/ldapadmin/src/main/webapp/console/node_modules/brunch/node_modules/chokidar/lib/nodefs-handler.js:77:19)
[ERROR]   at FSWatcher.NodeFsHandler._watchWithNodeFs (/home/fvanderbiest/workspace/georchestra/georchestra/ldapadmin/src/main/webapp/console/node_modules/brunch/node_modules/chokidar/lib/nodefs-handler.js:228:14)
[ERROR]   at FSWatcher.NodeFsHandler._handleFile (/home/fvanderbiest/workspace/georchestra/georchestra/ldapadmin/src/main/webapp/console/node_modules/brunch/node_modules/chokidar/lib/nodefs-handler.js:255:21)
[ERROR]   at FSWatcher.<anonymous> (/home/fvanderbiest/workspace/georchestra/georchestra/ldapadmin/src/main/webapp/console/node_modules/brunch/node_modules/chokidar/lib/nodefs-handler.js:473:21)
[ERROR]   at FSReqWrap.oncomplete (fs.js:82:15)
[ERROR] 
[ERROR] 
[ERROR] npm ERR! Linux 4.4.0-109-generic
[ERROR] npm ERR! argv "/home/fvanderbiest/workspace/georchestra/georchestra/ldapadmin/node/node" "/home/fvanderbiest/workspace/georchestra/georchestra/ldapadmin/node/node_modules/npm/bin/npm-cli.js" "install" "--unsafe-perm"
[ERROR] npm ERR! node v4.6.0
[ERROR] npm ERR! npm  v2.15.11
[ERROR] npm ERR! code ELIFECYCLE
[ERROR] npm ERR! admin_console@0.0.1 postinstall: `standard app/**/*.{js,es6} && ./node_modules/.bin/brunch build --production`
[ERROR] npm ERR! Exit status 1
[ERROR] npm ERR! 
[ERROR] npm ERR! Failed at the admin_console@0.0.1 postinstall script 'standard app/**/*.{js,es6} && ./node_modules/.bin/brunch build --production'.
[ERROR] npm ERR! This is most likely a problem with the admin_console package,
[ERROR] npm ERR! not with npm itself.
[ERROR] npm ERR! Tell the author that this fails on your system:
[ERROR] npm ERR!     standard app/**/*.{js,es6} && ./node_modules/.bin/brunch build --production
[ERROR] npm ERR! You can get information on how to open an issue for this project with:
[ERROR] npm ERR!     npm bugs admin_console
[ERROR] npm ERR! Or if that isn't available, you can get their info via:
[ERROR] npm ERR! 
[ERROR] npm ERR!     npm owner ls admin_console
[ERROR] npm ERR! There is likely additional logging output above.
[ERROR] 
[ERROR] npm ERR! Please include the following file with any support request:
[ERROR] npm ERR!     /home/fvanderbiest/workspace/georchestra/georchestra/ldapadmin/src/main/webapp/console/npm-debug.log
```

**Comment by fvanderbiest** [comment]
`package.json` sets version numbers, but not those of the 2nd level dependencies => we need a `package-lock.json` file to set those.

**Comment by fvanderbiest** [comment]
Building again for tests, with #1897 being merged.

**Comment by fvanderbiest** [comment]
Success !
