### ISSUE TITLE
console - No message found under code 'resourceNotFound.title' for locale 'fr_FR'

### ISSUE THREAD

**Issue by fvanderbiest** [georchestra/georchestra#1949]
javax.servlet.ServletException: javax.servlet.jsp.JspTagException: No message found under code 'resourceNotFound.title' for locale 'fr_FR'.
	at org.apache.jasper.runtime.PageContextImpl.doHandlePageException(PageContextImpl.java:905)
	at org.apache.jasper.runtime.PageContextImpl.handlePageException(PageContextImpl.java:834)
	at org.apache.jsp.WEB_002dINF.views.resourceNotFound_jsp._jspService(resourceNotFound_jsp.java:249)
	at org.apache.jasper.runtime.HttpJspBase.service(HttpJspBase.java:70)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)

**Comment by fvanderbiest** [comment]
Yet
```
src/main/webapp/WEB-INF/i18n/application.properties:resourceNotFound.title=Resource not found
src/main/webapp/WEB-INF/i18n/application_de.properties:resourceNotFound.title=Ressource wurde nicht gefunden
src/main/webapp/WEB-INF/i18n/application_es.properties:resourceNotFound.title=Recurso no encontrado
src/main/webapp/WEB-INF/i18n/application_fr.properties:resourceNotFound.title=Ressource introuvable
src/main/webapp/WEB-INF/views/resourceNotFound.jsp:     <title><s:message code="resourceNotFound.title"/></title>
src/main/webapp/WEB-INF/views/resourceNotFound.jsp:                     <h1><s:message code="resourceNotFound.title"/></h1>
```
