### ISSUE TITLE
SP - 17.12 & master build fails due testNetworkIPv6(org.georchestra.security.PermissionsTest)

### ISSUE THREAD

**Issue by fvanderbiest** [georchestra/georchestra#2017]
```
testNetworkIPv6(org.georchestra.security.PermissionsTest)  Time elapsed: 0.007 sec  <<< FAILURE!
java.lang.AssertionError
	at org.junit.Assert.fail(Assert.java:86)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at org.junit.Assert.assertTrue(Assert.java:52)
	at org.georchestra.security.PermissionsTest.testNetworkIPv6(PermissionsTest.java:122)
```

**Comment by pmauduit** [comment]
related github issue: https://github.com/isaacs/github/issues/354#issuecomment-385147137

**Comment by pmauduit** [comment]
Should also be ported back to 16.12 ...
