### ISSUE TITLE
console: allow an org member to view its org details, and request changes

### ISSUE THREAD

**Issue by landryb** [georchestra/georchestra#2101]
per https://github.com/georchestra/georchestra/issues/2080#issuecomment-401335376

right now the console only shows a string to the user for the org he's part of. It would be nice to allow a regular user to see his org details (mostly the coverage). An example is https://www.craig.fr/node/3303

In a second time we'd need a procedure (with admin validation, ofc) for the user to be able to request changes, mostly for the org coverage (this is linked with #2100). We'd want the user to be allowed to 'send/select' a new coverage (stored in a temporary ldap attr?) and the admin would validate it/switch it with the current 'production' coverage.

**Comment by landryb** [comment]
as admin, going to a user page already fetches his org details, there's an XHR call to console/private/orgs/<org>, but manually calling that url as regular user via curl triggers an NPE:

```
$curl -H 'sec-roles: ROLE_USER' -H 'sec-user: testuser' http://localhost:8280/console/private/orgs/psc

2018-07-02 17:30:18 GlobalExceptionHandler [ERROR] java.lang.NullPointerException
        at org.georchestra.console.ws.backoffice.orgs.OrgsController.checkOrgAuthorization(OrgsController.java:405)
        at org.georchestra.console.ws.backoffice.orgs.OrgsController.getOrgInfos(OrgsController.java:114)
```

**Comment by fvanderbiest** [comment]
> but manually calling that url as regular user via curl triggers an NPE

Funnily, I cannot reproduce on master (though querying through the SP)

**Comment by fvanderbiest** [comment]
Since #2125 already exists, let's rename this one to the second part of the job, ie "we'd need a procedure for the user to be able to request changes, mostly for the org coverage".
