### ISSUE TITLE
[console] invalid address mail in new account page triggers NPE

### ISSUE THREAD

**Issue by landryb** [georchestra/georchestra#2332]
submit a new user with an invalid email (user fatfingered, etc) actually creates the account in ldap, but the user is greeted by an error page with just this line:
```
java.io.IOException: javax.mail.SendFailedException: No recipient addresses
```
coming from this trace:
```
Caused by: javax.mail.SendFailedException: No recipient addresses
        at javax.mail.Transport.send0(Transport.java:148)
        at javax.mail.Transport.send(Transport.java:118)
        at org.georchestra.console.mailservice.Email.send(Email.java:172)

```
should be gracefully handled, ie something along the lines of "your account request was logged, but your e-mail address seems invalid" ?

**Comment by landryb** [comment]
Got fixed at some point it seems, tried registering on 18.12 tip with `nonexistent@aha.com` - `inetorgperson` properly created under `ou=pendingusers` and no traceback in the logs.

`test@foo.bar.none` or `test@foo.barz` triggered `Invalid format` validation for the email field. So i guess the NPE is gone and error case is properly handled.
