### ISSUE TITLE
console - postgres jdbc driver is unable to select a schema

### ISSUE THREAD

**Issue by pmauduit** [georchestra/georchestra#2339]
Encountered with a fairly recent console from master:

```
Caused by: 
org.postgresql.util.PSQLException: ERROR: no schema has been selected to create in|  Position: 14
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2182)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:1911)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:173)
	at org.postgresql.jdbc2.AbstractJdbc2Statement.execute(AbstractJdbc2Statement.java:645)
	at org.postgresql.jdbc2.AbstractJdbc2Statement.executeWithFlags(AbstractJdbc2Statement.java:495)
	at org.postgresql.jdbc2.AbstractJdbc2Statement.executeUpdate(AbstractJdbc2Statement.java:441)
	at com.mchange.v2.c3p0.impl.NewProxyPreparedStatement.executeUpdate(NewProxyPreparedStatement.java:384)

```

A workaround can be to modify the following line:
https://github.com/georchestra/datadir/blob/master/console/console.properties#L70

Appending a `defaultSchema=console`.

**Comment by fvanderbiest** [comment]
Is is still witnessed ? I'm not sure.
