### ISSUE TITLE
console - java.io.IOException: Invalid org name

### ISSUE THREAD

**Issue by fvanderbiest** [georchestra/georchestra#2401]
After #2184 , creating a new account linked to a new org on master fails with `java.io.IOException: Invalid org name`
Both the new account and org are supposed to be PENDING in this case.

```
 2019-01-23 14:21:24 GlobalExceptionHandler [ERROR] java.io.IOException: java.io.IOException: Invalid org name
 	at org.georchestra.console.ws.newaccount.NewAccountFormController.create(NewAccountFormController.java:238)
[...]
 Caused by: java.io.IOException: Invalid org name
 	at org.georchestra.console.ds.OrgsDao.generateId(OrgsDao.java:304)
 	at org.georchestra.console.ws.newaccount.NewAccountFormController.create(NewAccountFormController.java:210)
 	... 94 more
```

**Comment by fvanderbiest** [comment]
Short name for ORG is required, but the field does not mention it.

**Comment by landryb** [comment]
dupe #2451 ? Tried creating an account linked to an existing org here with master, and it was created in `ou=pendingusers` as expected - added as member of the existing `cn=org,ou=orgs`

**Comment by severo** [comment]
I didn't experience the exception when creating the user, after creating the org, be it through the console with testadmin (-> users), or from console/account/new (-> pendingusers).
I think we can close.
