### ISSUE TITLE
console - /console/account/userdetails java.lang.IndexOutOfBoundsException

### ISSUE THREAD

**Issue by fvanderbiest** [georchestra/georchestra#2410]
On master, currently:
```
$ curl -ksu testadmin:testadmin https://georchestra.mydomain.org/console/account/userdetails
java.io.IOException: java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
```

Probably a regression after #2184

**Comment by fvanderbiest** [comment]
```
 Caused by: java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
 	at java.util.LinkedList.checkElementIndex(LinkedList.java:555)
 	at java.util.LinkedList.get(LinkedList.java:476)
 	at org.georchestra.console.ds.OrgsDao.findForUser(OrgsDao.java:196)
 	at org.georchestra.console.ws.edituserdetails.EditUserDetailsFormController.setupForm(EditUserDetailsFormController.java:102)
```

**Comment by landryb** [comment]
Tested ok with #2408 merged

**Comment by fvanderbiest** [comment]
yep
