### ISSUE TITLE
SP - org.springframework.security.web.firewall.RequestRejectedException

### ISSUE THREAD

**Issue by fvanderbiest** [georchestra/georchestra#2462]
Navigating the docker composition leads to https://georchestra.mydomain.org/geoserver/web/;jsessionid=node012l7tnwtustnl5gb6patggaor2.node0?0 which fails with

```
org.springframework.security.web.firewall.RequestRejectedException: The request was rejected because the URL contained a potentially malicious String ";"
	at org.springframework.security.web.firewall.StrictHttpFirewall.rejectedBlacklistedUrls(StrictHttpFirewall.java:265)
	at org.springframework.security.web.firewall.StrictHttpFirewall.getFirewalledRequest(StrictHttpFirewall.java:245)
	at org.springframework.security.web.FilterChainProxy.doFilterInternal(FilterChainProxy.java:193)
	at org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:177)
	at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:347)
	at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:263)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1642)
	at org.georchestra.security.UTF8Filter.doFilter(UTF8Filter.java:33)
```

**Comment by pmauduit** [comment]
servlet 3.0 allows to deactivate passing the jsessionid in the url (servlet containers do that when they detect they cannot use cookies for this). This requires to add the following in each `web.xml` files:

```xml
<session-config>
     <tracking-mode>COOKIE</tracking-mode>
</session-config>
```

**Comment by groldan** [comment]
Related GeoServer issue: https://osgeo-org.atlassian.net/browse/GEOS-8913
 and  patch: https://github.com/geoserver/geoserver/pull/3355

**Comment by groldan** [comment]
Note to self: `curl -L` = follow redirects, `curl -c` = save cookies to a file and reuse

At the geoserver side (exposed docker-compose's 8080 port) I get this:
```
$ curl -v http://localhost:8080/geoserver/web/ > /dev/null
< HTTP/1.1 302 Found
< Set-Cookie: JSESSIONID=node0vrc1uvel4zfji54t7qf5mnpt0.node0;Path=/geoserver;Secure;HttpOnly
< Location: http://localhost:8080/geoserver/web/;jsessionid=node0vrc1uvel4zfji54t7qf5mnpt0.node0?0
```
And `curl -L ...` ends in too many redirects.

After upgrading `web.xml` to servlet 3.0 and adding `<session-config><tracking-mode>COOKIE</tracking-mode></session-config>`, get this:

```
$ curl -v http://localhost:8080/geoserver/web > /dev/null
< HTTP/1.1 302 Found
< Set-Cookie: JSESSIONID=node01shj4xigsvgnnqc1h272j7wgp244.node0;Path=/geoserver
< Location: http://localhost:8080/geoserver/web/
```
And following redirects:

```
$ curl -c cookes.txt -vL "http://localhost:8080/geoserver/web/">/dev/null
< HTTP/1.1 302 Found
< Set-Cookie: JSESSIONID=node01bftdeqchs2b41azu8yqgb3qy0312.node0;Path=/geoserver
< Location: http://localhost:8080/geoserver/web/?0
...
> GET /geoserver/web/?0 HTTP/1.1
> Accept: */*
> Cookie: JSESSIONID=node01bftdeqchs2b41azu8yqgb3qy0312.node0
> 
< HTTP/1.1 200 OK
< Content-Type: text/html;charset=utf-8
```

So as for geoserver, that'd be it.
Going through the proxy though I get  `curl: (47) Maximum (50) redirects followed`

```
curl -kLv -c cookies.txt https://georchestra.mydomain.org/geoserver/web/ > /dev/null
...
< HTTP/2 302 
< location: https://georchestra.mydomain.org/geoserver/web/?0
{ [0 bytes data]
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
* Connection #0 to host georchestra.mydomain.org left intact
* Maximum (50) redirects followed
curl: (47) Maximum (50) redirects followed
```

Which lends me to suspect of how `security-proxy` handles cookies.
To be continued...

**Comment by groldan** [comment]
Two PR's to fix this, one in geoserver and one in security-proxy:

- https://github.com/georchestra/geoserver/pull/17
- https://github.com/georchestra/georchestra/pull/2516
