### ISSUE TITLE
console - sql syntax error

### ISSUE THREAD

**Issue by fvanderbiest** [georchestra/georchestra#2464]
On master
```
console_1                   | 2019-02-06 14:44:58 GlobalExceptionHandler [ERROR] org.springframework.dao.InvalidDataAccessResourceUsageException: could not extract ResultSet; SQL [n/a]; nested exception is org.hibernate.exception.SQLGrammarException: could not extract ResultSet
console_1                   | 	at org.springframework.orm.jpa.vendor.HibernateJpaDialect.convertHibernateAccessException(HibernateJpaDialect.java:261)
console_1                   | 	at org.springframework.orm.jpa.vendor.HibernateJpaDialect.translateExceptionIfPossible(HibernateJpaDialect.java:244)
console_1                   | 	at org.springframework.orm.jpa.AbstractEntityManagerFactoryBean.translateExceptionIfPossible(AbstractEntityManagerFactoryBean.java:525)
console_1                   | 	at org.springframework.dao.support.ChainedPersistenceExceptionTranslator.translateExceptionIfPossible(ChainedPersistenceExceptionTranslator.java:59)
console_1                   | 	at org.springframework.dao.support.DataAccessUtils.translateIfNecessary(DataAccessUtils.java:209)
console_1                   | 	at org.springframework.dao.support.PersistenceExceptionTranslationInterceptor.invoke(PersistenceExceptionTranslationInterceptor.java:147)
console_1                   | 	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
console_1                   | 	at org.springframework.data.jpa.repository.support.CrudMethodMetadataPostProcessor$CrudMethodMetadataPopulatingMethodInterceptor.invoke(CrudMethodMetadataPostProcessor.java:133)
console_1                   | 	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
console_1                   | 	at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:92)
console_1                   | 	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
console_1                   | 	at org.springframework.data.repository.core.support.SurroundingTransactionDetectorMethodInterceptor.invoke(SurroundingTransactionDetectorMethodInterceptor.java:57)
console_1                   | 	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
console_1                   | 	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:213)
console_1                   | 	at com.sun.proxy.$Proxy51.myFindByTargets(Unknown Source)
console_1                   | 	at org.georchestra.console.ws.backoffice.log.LogController.find(LogController.java:125)
console_1                   | 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
console_1                   | 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
console_1                   | 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
console_1                   | 	at java.lang.reflect.Method.invoke(Method.java:498)
console_1                   | 	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:205)
console_1                   | 	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:133)
console_1                   | 	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:97)
console_1                   | 	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:849)
console_1                   | 	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:760)
console_1                   | 	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:85)
console_1                   | 	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:967)
console_1                   | 	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:901)
console_1                   | 	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:970)
console_1                   | 	at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:861)
console_1                   | 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:687)
console_1                   | 	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:846)
console_1                   | 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
console_1                   | 	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:865)
console_1                   | 	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1655)
console_1                   | 	at org.eclipse.jetty.websocket.server.WebSocketUpgradeFilter.doFilter(WebSocketUpgradeFilter.java:215)
console_1                   | 	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1642)
console_1                   | 	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:197)
console_1                   | 	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
console_1                   | 	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1642)
console_1                   | 	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:317)
console_1                   | 	at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.invoke(FilterSecurityInterceptor.java:127)
console_1                   | 	at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.doFilter(FilterSecurityInterceptor.java:91)
console_1                   | 	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
console_1                   | 	at org.springframework.security.web.access.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:114)
console_1                   | 	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
console_1                   | 	at org.springframework.security.web.session.SessionManagementFilter.doFilter(SessionManagementFilter.java:137)
console_1                   | 	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
console_1                   | 	at org.springframework.security.web.authentication.AnonymousAuthenticationFilter.doFilter(AnonymousAuthenticationFilter.java:111)
console_1                   | 	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
console_1                   | 	at org.springframework.security.web.servletapi.SecurityContextHolderAwareRequestFilter.doFilter(SecurityContextHolderAwareRequestFilter.java:170)
console_1                   | 	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
console_1                   | 	at org.springframework.security.web.savedrequest.RequestCacheAwareFilter.doFilter(RequestCacheAwareFilter.java:63)
console_1                   | 	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
console_1                   | 	at org.springframework.security.web.authentication.www.BasicAuthenticationFilter.doFilterInternal(BasicAuthenticationFilter.java:158)
console_1                   | 	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
console_1                   | 	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
console_1                   | 	at org.springframework.security.web.authentication.ui.DefaultLoginPageGeneratingFilter.doFilter(DefaultLoginPageGeneratingFilter.java:177)
console_1                   | 	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
console_1                   | 	at org.springframework.security.web.authentication.AbstractAuthenticationProcessingFilter.doFilter(AbstractAuthenticationProcessingFilter.java:200)
console_1                   | 	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
console_1                   | 	at org.springframework.security.web.authentication.preauth.AbstractPreAuthenticatedProcessingFilter.doFilter(AbstractPreAuthenticatedProcessingFilter.java:121)
console_1                   | 	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
console_1                   | 	at org.springframework.security.web.authentication.logout.LogoutFilter.doFilter(LogoutFilter.java:116)
console_1                   | 	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
console_1                   | 	at org.springframework.security.web.header.HeaderWriterFilter.doFilterInternal(HeaderWriterFilter.java:66)
console_1                   | 	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
console_1                   | 	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
console_1                   | 	at org.springframework.security.web.context.request.async.WebAsyncManagerIntegrationFilter.doFilterInternal(WebAsyncManagerIntegrationFilter.java:56)
console_1                   | 	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
console_1                   | 	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
console_1                   | 	at org.springframework.security.web.context.SecurityContextPersistenceFilter.doFilter(SecurityContextPersistenceFilter.java:105)
console_1                   | 	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
console_1                   | 	at org.springframework.security.web.FilterChainProxy.doFilterInternal(FilterChainProxy.java:214)
console_1                   | 	at org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:177)
console_1                   | 	at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:347)
console_1                   | 	at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:263)
console_1                   | 	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1634)
console_1                   | 	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:533)
console_1                   | 	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:146)
console_1                   | 	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:548)
console_1                   | 	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
console_1                   | 	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:257)
console_1                   | 	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1595)
console_1                   | 	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:255)
console_1                   | 	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1340)
console_1                   | 	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:203)
console_1                   | 	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:473)
console_1                   | 	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1564)
console_1                   | 	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:201)
console_1                   | 	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1242)
console_1                   | 	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:144)
console_1                   | 	at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:220)
console_1                   | 	at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:126)
console_1                   | 	at org.eclipse.jetty.server.handler.StatisticsHandler.handle(StatisticsHandler.java:174)
console_1                   | 	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
console_1                   | 	at org.eclipse.jetty.server.Server.handle(Server.java:503)
console_1                   | 	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:364)
console_1                   | 	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:260)
console_1                   | 	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:305)
console_1                   | 	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:103)
console_1                   | 	at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:118)
console_1                   | 	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:333)
console_1                   | 	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:310)
console_1                   | 	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:168)
console_1                   | 	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:126)
console_1                   | 	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:366)
console_1                   | 	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:765)
console_1                   | 	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:683)
console_1                   | 	at java.lang.Thread.run(Thread.java:748)
console_1                   | Caused by: org.hibernate.exception.SQLGrammarException: could not extract ResultSet
console_1                   | 	at org.hibernate.exception.internal.SQLStateConversionDelegate.convert(SQLStateConversionDelegate.java:106)
console_1                   | 	at org.hibernate.exception.internal.StandardSQLExceptionConverter.convert(StandardSQLExceptionConverter.java:42)
console_1                   | 	at org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHelper.java:109)
console_1                   | 	at org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHelper.java:95)
console_1                   | 	at org.hibernate.engine.jdbc.internal.ResultSetReturnImpl.extract(ResultSetReturnImpl.java:79)
console_1                   | 	at org.hibernate.loader.Loader.getResultSet(Loader.java:2117)
console_1                   | 	at org.hibernate.loader.Loader.executeQueryStatement(Loader.java:1900)
console_1                   | 	at org.hibernate.loader.Loader.executeQueryStatement(Loader.java:1876)
console_1                   | 	at org.hibernate.loader.Loader.doQuery(Loader.java:919)
console_1                   | 	at org.hibernate.loader.Loader.doQueryAndInitializeNonLazyCollections(Loader.java:336)
console_1                   | 	at org.hibernate.loader.Loader.doList(Loader.java:2617)
console_1                   | 	at org.hibernate.loader.Loader.doList(Loader.java:2600)
console_1                   | 	at org.hibernate.loader.Loader.listIgnoreQueryCache(Loader.java:2429)
console_1                   | 	at org.hibernate.loader.Loader.list(Loader.java:2424)
console_1                   | 	at org.hibernate.loader.hql.QueryLoader.list(QueryLoader.java:501)
console_1                   | 	at org.hibernate.hql.internal.ast.QueryTranslatorImpl.list(QueryTranslatorImpl.java:371)
console_1                   | 	at org.hibernate.engine.query.spi.HQLQueryPlan.performList(HQLQueryPlan.java:216)
console_1                   | 	at org.hibernate.internal.SessionImpl.list(SessionImpl.java:1326)
console_1                   | 	at org.hibernate.internal.QueryImpl.list(QueryImpl.java:87)
console_1                   | 	at org.hibernate.jpa.internal.QueryImpl.list(QueryImpl.java:606)
console_1                   | 	at org.hibernate.jpa.internal.QueryImpl.getResultList(QueryImpl.java:483)
console_1                   | 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
console_1                   | 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
console_1                   | 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
console_1                   | 	at java.lang.reflect.Method.invoke(Method.java:498)
console_1                   | 	at org.springframework.orm.jpa.SharedEntityManagerCreator$DeferredQueryInvocationHandler.invoke(SharedEntityManagerCreator.java:375)
console_1                   | 	at com.sun.proxy.$Proxy50.getResultList(Unknown Source)
console_1                   | 	at org.springframework.data.jpa.repository.query.JpaQueryExecution$CollectionExecution.doExecute(JpaQueryExecution.java:125)
console_1                   | 	at org.springframework.data.jpa.repository.query.JpaQueryExecution.execute(JpaQueryExecution.java:89)
console_1                   | 	at org.springframework.data.jpa.repository.query.AbstractJpaQuery.doExecute(AbstractJpaQuery.java:128)
console_1                   | 	at org.springframework.data.jpa.repository.query.AbstractJpaQuery.execute(AbstractJpaQuery.java:118)
console_1                   | 	at org.springframework.data.repository.core.support.RepositoryFactorySupport$QueryExecutorMethodInterceptor.doInvoke(RepositoryFactorySupport.java:494)
console_1                   | 	at org.springframework.data.repository.core.support.RepositoryFactorySupport$QueryExecutorMethodInterceptor.invoke(RepositoryFactorySupport.java:477)
console_1                   | 	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
console_1                   | 	at org.springframework.data.projection.DefaultMethodInvokingMethodInterceptor.invoke(DefaultMethodInvokingMethodInterceptor.java:56)
console_1                   | 	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
console_1                   | 	at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:99)
console_1                   | 	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:282)
console_1                   | 	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:96)
console_1                   | 	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
console_1                   | 	at org.springframework.dao.support.PersistenceExceptionTranslationInterceptor.invoke(PersistenceExceptionTranslationInterceptor.java:136)
console_1                   | 	... 104 more
console_1                   | Caused by: org.postgresql.util.PSQLException: ERROR: syntax error at or near ")"
console_1                   |   Position: 230
console_1                   | 	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2440)
console_1                   | 	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2183)
console_1                   | 	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:308)
console_1                   | 	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:441)
console_1                   | 	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:365)
console_1                   | 	at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:143)
console_1                   | 	at org.postgresql.jdbc.PgPreparedStatement.executeQuery(PgPreparedStatement.java:106)
console_1                   | 	at com.mchange.v2.c3p0.impl.NewProxyPreparedStatement.executeQuery(NewProxyPreparedStatement.java:353)
console_1                   | 	at org.hibernate.engine.jdbc.internal.ResultSetReturnImpl.extract(ResultSetReturnImpl.java:70)
console_1                   | 	... 140 more
console_1                   | 
database_1                  | 2019-02-06 14:45:11.755 UTC [38] ERROR:  syntax error at or near ")" at character 230
database_1                  | 2019-02-06 14:45:11.755 UTC [38] STATEMENT:  select adminlogen0_.id as id1_3_, adminlogen0_.admin as admin2_3_, adminlogen0_.date as date3_3_, adminlogen0_.target as target4_3_, adminlogen0_.type as type5_3_ from console.admin_log adminlogen0_ where adminlogen0_.target in () order by adminlogen0_.date DESC limit $1
console_1                   | 2019-02-06 14:45:11 SqlExceptionHelper [WARN] SQL Error: 0, SQLState: 42601
console_1                   | 2019-02-06 14:45:11 SqlExceptionHelper [ERROR] ERROR: syntax error at or near ")"
console_1                   |   Position: 230
console_1                   | 2019-02-06 14:45:11 GlobalExceptionHandler [ERROR] org.springframework.dao.InvalidDataAccessResourceUsageException: could not extract ResultSet; SQL [n/a]; nested exception is org.hibernate.exception.SQLGrammarException: could not extract ResultSet
console_1                   | 	at org.springframework.orm.jpa.vendor.HibernateJpaDialect.convertHibernateAccessException(HibernateJpaDialect.java:261)
console_1                   | 	at org.springframework.orm.jpa.vendor.HibernateJpaDialect.translateExceptionIfPossible(HibernateJpaDialect.java:244)
console_1                   | 	at org.springframework.orm.jpa.AbstractEntityManagerFactoryBean.translateExceptionIfPossible(AbstractEntityManagerFactoryBean.java:525)
console_1                   | 	at org.springframework.dao.support.ChainedPersistenceExceptionTranslator.translateExceptionIfPossible(ChainedPersistenceExceptionTranslator.java:59)
console_1                   | 	at org.springframework.dao.support.DataAccessUtils.translateIfNecessary(DataAccessUtils.java:209)
console_1                   | 	at org.springframework.dao.support.PersistenceExceptionTranslationInterceptor.invoke(PersistenceExceptionTranslationInterceptor.java:147)
console_1                   | 	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
console_1                   | 	at org.springframework.data.jpa.repository.support.CrudMethodMetadataPostProcessor$CrudMethodMetadataPopulatingMethodInterceptor.invoke(CrudMethodMetadataPostProcessor.java:133)
console_1                   | 	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
console_1                   | 	at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:92)
console_1                   | 	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
console_1                   | 	at org.springframework.data.repository.core.support.SurroundingTransactionDetectorMethodInterceptor.invoke(SurroundingTransactionDetectorMethodInterceptor.java:57)
console_1                   | 	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
console_1                   | 	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:213)
console_1                   | 	at com.sun.proxy.$Proxy51.myFindByTargets(Unknown Source)
console_1                   | 	at org.georchestra.console.ws.backoffice.log.LogController.find(LogController.java:125)
```

**Comment by fvanderbiest** [comment]
45:11.755 UTC [38] ERROR:  syntax error at or near ")" at character 230
2019-02-06 14:45:11.755 UTC [38] STATEMENT:  select adminlogen0_.id as id1_3_, adminlogen0_.admin as admin2_3_, adminlogen0_.date as date3_3_, adminlogen0_.target as target4_3_, adminlogen0_.type as type5_3_ from console.admin_log adminlogen0_ where adminlogen0_.target in () order by adminlogen0_.date DESC limit $1

**Comment by fvanderbiest** [comment]
I renamed login `testdelegatedadmin` into `delegatedadmin` from http://localhost:8080/console/manager/#!/users/testdelegatedadmin/infos

**Comment by fvanderbiest** [comment]
This is critical since it breaks user registration with org.springframework.ldap.NameNotFoundException: Cannot find user with uid : testdelegatedadmin in LDAP server

**Comment by pmauduit** [comment]
Related to https://github.com/georchestra/georchestra/pull/2473

**Comment by fvanderbiest** [comment]
Tested, working fine.
Thanks Christophe & Pierre.
