### ISSUE TITLE
geonetwork - ro.isdc.wro.WroRuntimeException: No such group available in the model: gn_search_georchestra

### ISSUE THREAD

**Issue by fvanderbiest** [georchestra/georchestra#2518]
Witnessed on 18.12
```
proxy_1                     | 2019-02-19 08:40:42 security [WARN] Downstream server returned a status code which could be an error. Statuscode: 404, reason: Not Found
proxy_1                     | 2019-02-19 08:40:42 statistics [INFO] testadmin|2019/02/19 08:40:42|http://geonetwork:8080/geonetwork/static/gn_search_georchestra.js|Project Steering Committee|ROLE_SUPERUSER,ROLE_USER,ROLE_ADMINISTRATOR,ROLE_EXTRACTORAPP,ROLE_GN_ADMIN
geonetwork_1                | 2019-02-19 08:40:42,329 ERROR [geonetwork.wro4j] - Error occurred during a wro4j request handling
geonetwork_1                | ro.isdc.wro.WroRuntimeException: No such group available in the model: gn_search_georchestra
geonetwork_1                | 	at ro.isdc.wro.model.group.processor.GroupsProcessor.process(GroupsProcessor.java:74)
geonetwork_1                | 	at ro.isdc.wro.cache.support.DefaultSynchronizedCacheStrategyDecorator.loadValue(DefaultSynchronizedCacheStrategyDecorator.java:101)
geonetwork_1                | 	at ro.isdc.wro.cache.support.DefaultSynchronizedCacheStrategyDecorator.loadValue(DefaultSynchronizedCacheStrategyDecorator.java:35)
geonetwork_1                | 	at ro.isdc.wro.cache.support.AbstractSynchronizedCacheStrategyDecorator.get(AbstractSynchronizedCacheStrategyDecorator.java:55)
geonetwork_1                | 	at ro.isdc.wro.manager.ResourceBundleProcessor.serveProcessedBundle(ResourceBundleProcessor.java:63)
geonetwork_1                | 	at ro.isdc.wro.manager.WroManager.process(WroManager.java:159)
geonetwork_1                | 	at ro.isdc.wro.http.WroFilter.processRequest(WroFilter.java:335)
geonetwork_1                | 	at ro.isdc.wro.http.WroFilter.doFilter(WroFilter.java:289)
```

**Comment by fvanderbiest** [comment]
One must not forget to `git submodule update --init --recursive` when switching branches !

**Comment by fvanderbiest** [comment]
I was essentially missing the ``--recursive`` part here...
