### ISSUE TITLE
extractorapp - PropertyAccessException 1: org.springframework.beans.MethodInvocationException: Property 'publicUrl' threw exception

### ISSUE THREAD

**Issue by fvanderbiest** [georchestra/georchestra#2519]
Witnessed with the docker composition with an up to date data dir
```
Caused by: 
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'extractor-controller' defined in ServletContext resource [/WEB-INF/ws-servlet.xml]: Error setting property values; nested exception is org.springframework.beans.PropertyBatchUpdateException; nested PropertyAccessExceptions (1) are:|PropertyAccessException 1: org.springframework.beans.MethodInvocationException: Property 'publicUrl' threw exception; nested exception is java.lang.NullPointerException
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyPropertyValues(AbstractAutowireCapableBeanFactory.java:1571)
[...]
	at org.eclipse.jetty.start.Main.start(Main.java:490)
	at org.eclipse.jetty.start.Main.main(Main.java:77)
Caused by: 
org.springframework.beans.PropertyBatchUpdateException; nested PropertyAccessExceptions (1) are:|PropertyAccessException 1: org.springframework.beans.MethodInvocationException: Property 'publicUrl' threw exception; nested exception is java.lang.NullPointerException
	at org.springframework.beans.AbstractPropertyAccessor.setPropertyValues(AbstractPropertyAccessor.java:121)
```

**Comment by severo** [comment]
Also thrown with:

```
cd extractorapp
mvn jetty:run
```

**Comment by severo** [comment]
See #2524.
