### ISSUE TITLE
security-proxy - the request was rejected because the URL contained a potentially malicious String ";"

### ISSUE THREAD

**Issue by fvanderbiest** [georchestra/georchestra#2616]
Witnessed on `master`, while it works on `18.06`. 
Probably affects `19.04` too.

```
Problem accessing /ckan/fanstatic/theme/:version:2019-05-09T11:47:13/:bundle:font.css;main.css;styles.css;theme.css. Reason:

    Server Error
Caused by:
org.springframework.security.web.firewall.RequestRejectedException: The request was rejected because the URL contained a potentially malicious String ";"
	at org.springframework.security.web.firewall.StrictHttpFirewall.rejectedBlacklistedUrls(StrictHttpFirewall.java:265)
	at org.springframework.security.web.firewall.StrictHttpFirewall.getFirewalledRequest(StrictHttpFirewall.java:245)
	at org.springframework.security.web.FilterChainProxy.doFilterInternal(FilterChainProxy.java:193)
	at org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:177)
	at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:347)
	at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:263)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1610)
	at org.georchestra.security.UTF8Filter.doFilter(UTF8Filter.java:33)
```

**Comment by groldan** [comment]
Fixed by #2636

**Comment by pmauduit** [comment]
Should also be ported to 19.04

**Comment by groldan** [comment]
Closing, it was backported on July 15 as of #2650
