### ISSUE TITLE
Kakadu with some valid JPEG2000 files errors "envelope" should not be null

### ISSUE THREAD

**Issue by groldan** [georchestra/georchestra#2640]
A file with the following structure cannot be read, leading to the exception at the bottom:

```
gdalinfo /data/tmp/test_good_kdu.jp2 
Driver: JP2OpenJPEG/JPEG-2000 driver based on OpenJPEG library
Files: /data/tmp/test_good_kdu.jp2
Size is 10000, 10000
Coordinate System is:
PROJCS["unnamed",
    GEOGCS["unnamed ellipse",
        DATUM["unknown",
            SPHEROID["unnamed",6378137,298.257222101],
            TOWGS84[0,0,0,0,0,0,0]],
        PRIMEM["Greenwich",0],
        UNIT["degree",0.0174532925199433]],
    PROJECTION["Lambert_Conformal_Conic_2SP"],
    PARAMETER["standard_parallel_1",44],
    PARAMETER["standard_parallel_2",49],
    PARAMETER["latitude_of_origin",46.5],
    PARAMETER["central_meridian",3],
    PARAMETER["false_easting",700000],
    PARAMETER["false_northing",6600000],
    UNIT["metre",1,
        AUTHORITY["EPSG","9001"]]]
Origin = (570000.000000000000000,6280000.000000000000000)
Pixel Size = (0.500000000000000,-0.500000000000000)
Metadata:
  TIFFTAG_RESOLUTIONUNIT=3 (pixels/cm)
  TIFFTAG_XRESOLUTION=0.393707
  TIFFTAG_YRESOLUTION=0.393707
Image Structure Metadata:
  INTERLEAVE=PIXEL
Corner Coordinates:
Upper Left  (  570000.000, 6280000.000) (  1d23'24.59"E, 43d36'25.65"N)
Lower Left  (  570000.000, 6275000.000) (  1d23'29.13"E, 43d33'43.73"N)
Upper Right (  575000.000, 6280000.000) (  1d27' 7.43"E, 43d36'28.89"N)
Lower Right (  575000.000, 6275000.000) (  1d27'11.79"E, 43d33'46.97"N)
Center      (  572500.000, 6277500.000) (  1d25'18.23"E, 43d35' 6.33"N)
Band 1 Block=1024x1024 Type=Byte, ColorInterp=Red
  Overviews: 5000x5000, 2500x2500, 1250x1250, 625x625, 312x312, 156x156, 78x78
  Overviews: arbitrary
  Image Structure Metadata:
    COMPRESSION=JPEG2000
Band 2 Block=1024x1024 Type=Byte, ColorInterp=Green
  Overviews: 5000x5000, 2500x2500, 1250x1250, 625x625, 312x312, 156x156, 78x78
  Overviews: arbitrary
  Image Structure Metadata:
    COMPRESSION=JPEG2000
Band 3 Block=1024x1024 Type=Byte, ColorInterp=Blue
  Overviews: 5000x5000, 2500x2500, 1250x1250, 625x625, 312x312, 156x156, 78x78
  Overviews: arbitrary
  Image Structure Metadata:
    COMPRESSION=JPEG2000
```

```
Caused by: java.lang.IllegalArgumentException: Argument "envelope" should not be null.
at org.geotools.geometry.GeneralEnvelope.ensureNonNull(GeneralEnvelope.java:305)
at org.geotools.geometry.GeneralEnvelope.<init>(GeneralEnvelope.java:183)
at org.geotools.coverage.grid.io.AbstractGridCoverage2DReader.getOriginalEnvelope(AbstractGridCoverage2DReader.java:890)
at org.geotools.coverage.grid.io.AbstractGridCoverage2DReader.getOriginalEnvelope(AbstractGridCoverage2DReader.java:876)
at org.geotools.coverageio.jp2k.RasterManager.<init>(RasterManager.java:424)
at org.geotools.coverageio.jp2k.JP2KReader.<init>(JP2KReader.java:722)
at org.geotools.coverageio.jp2k.JP2KFormat.getReader(JP2KFormat.java:111)
at org.geoserver.catalog.ResourcePool.getGridCoverageReader(ResourcePool.java:1490)
at org.geoserver.catalog.ResourcePool.getGridCoverageReader(ResourcePool.java:1410)
at org.geoserver.catalog.impl.CoverageInfoImpl.getGridCoverageReader(CoverageInfoImpl.java:157)
at org.geoserver.catalog.CatalogBuilder.getNativeBounds(CatalogBuilder.java:585)
at org.geoserver.catalog.CatalogBuilder.getNativeBounds(CatalogBuilder.java:537)
at org.geoserver.web.data.resource.BasicResourceConfig$1.onSubmit(BasicResourceConfig.java:138)

```

**Comment by groldan** [comment]
quick fix: `gdal_edit.py -a_srs EPSG:2154 test_good_kdu.jp2`

**Comment by fvanderbiest** [comment]
Thanks Gabriel, works indeed :-)
