### ISSUE TITLE
console: build broken, integration tests fail on 19.04

### ISSUE THREAD

**Issue by groldan** [georchestra/georchestra#2680]
On 19.04, the travis build was broken, lacking backports of #2658 and #2669
PR #2679 backport those fixes, and exposes a new problem: the integration test for `console` are failing.

**Comment by groldan** [comment]
Tests failing:
```
[ERROR] Errors: 
[ERROR]   AdvancedDelegationDaoIT.testConnectionTimeoutSet » IllegalState Failed to load...
[ERROR]   AdvancedDelegationDaoIT.testFindByOrg_closesJdbcResources » IllegalState Faile...
[ERROR]   AdvancedDelegationDaoIT.testFindByRole_closesJdbcResources » IllegalState Fail...
[ERROR]   AdvancedDelegationDaoIT.testFindUsersUnderDelegation_closesJdbcResources » IllegalState
[ERROR]   ConnectionPoolBehaviorIT.testConnectionPoolDiscardsServerSideClosedConnections » IllegalState
[ERROR]   RolesIT.testCreate » IllegalState Failed to load ApplicationContext
[ERROR]   RolesIT.testCreateBadUser » IllegalState Failed to load ApplicationContext
[ERROR]   RolesIT.testUpdateIsFavorite » IllegalState Failed to load ApplicationContext
[ERROR]   RolesIT.testUpdateIsFavoriteNoOp » IllegalState Failed to load ApplicationCont...
[ERROR]   UsersIT.changeOrgAndUid » IllegalState Failed to load ApplicationContext
[ERROR]   UsersIT.profile » IllegalState Failed to load ApplicationContext
[ERROR]   UsersIT.updateUsers » IllegalState Failed to load ApplicationContext
[ERROR]   UsersIT.userDetail » IllegalState Failed to load ApplicationContext
[ERROR]   UsersIT.users » IllegalState Failed to load ApplicationContext
[ERROR]   PasswordRecoverySurvivesDatabaseRestartIT.testSurvivesDatabaseRestartPOST » IllegalState
[INFO] 
[ERROR] Tests run: 15, Failures: 0, Errors: 15, Skipped: 0
```
All with the following error:

````
Caused by: java.lang.IllegalArgumentException: Could not resolve placeholder 'ldapScheme' in value "${ldapScheme}://${ldapHost}:${ldapPort}"
	at org.springframework.util.PropertyPlaceholderHelper.parseStringValue(PropertyPlaceholderHelper.java:174)
	at org.springframework.util.PropertyPlaceholderHelper.replacePlaceholders(PropertyPlaceholderHelper.java:126)
	at org.springframework.core.env.AbstractPropertyResolver.doResolvePlaceholders(AbstractPropertyResolver.java:236)
	at org.springframework.core.env.AbstractPropertyResolver.resolveRequiredPlaceholders(AbstractPropertyResolver.java:210)
	at org.springframework.context.support.PropertySourcesPlaceholderConfigurer$2.resolveStringValue(PropertySourcesPlaceholderConfigurer.java:172)
	at org.springframework.beans.factory.config.BeanDefinitionVisitor.resolveStringValue(BeanDefinitionVisitor.java:282)
	at org.springframework.beans.factory.config.BeanDefinitionVisitor.resolveValue(BeanDefinitionVisitor.java:204)
	at org.springframework.beans.factory.config.BeanDefinitionVisitor.visitPropertyValues(BeanDefinitionVisitor.java:141)
	at org.springframework.beans.factory.config.BeanDefinitionVisitor.visitBeanDefinition(BeanDefinitionVisitor.java:82)
	at org.springframework.beans.factory.config.PlaceholderConfigurerSupport.doProcessProperties(PlaceholderConfigurerSupport.java:220)
	... 39 more
```

**Comment by fvanderbiest** [comment]
Ouch, indeed.
`ldapScheme` was introduced with #2656
