### ISSUE TITLE
mapfishapp print - mini-map printing generates a NullPointerException

### ISSUE THREAD

**Issue by fvanderbiest** [georchestra/georchestra#2686]
Witnessed on 18.06
```
Error while generating PDF:
java.lang.NullPointerException
at org.mapfish.print.map.MapChunkDrawer.renderImpl(MapChunkDrawer.java:86)
at org.mapfish.print.ChunkDrawer.render(ChunkDrawer.java:55)
at org.mapfish.print.ChunkDrawer.tableLayout(ChunkDrawer.java:49)
at com.itextpdf.text.pdf.PdfPTable.writeSelectedRows(PdfPTable.java:786)
at com.itextpdf.text.pdf.ColumnText.goComposite(ColumnText.java:1765)
at com.itextpdf.text.pdf.ColumnText.go(ColumnText.java:882)
at com.itextpdf.text.pdf.ColumnText.go(ColumnText.java:877)
at com.itextpdf.text.pdf.ColumnText.go(ColumnText.java:866)
at com.itextpdf.text.pdf.PdfPRow.writeCells(PdfPRow.java:549)
at com.itextpdf.text.pdf.PdfPTable.writeSelectedRows(PdfPTable.java:764)
at com.itextpdf.text.pdf.ColumnText.goComposite(ColumnText.java:1765)
at com.itextpdf.text.pdf.ColumnText.go(ColumnText.java:882)
at com.itextpdf.text.pdf.ColumnText.go(ColumnText.java:877)
at com.itextpdf.text.pdf.ColumnText.go(ColumnText.java:866)
at com.itextpdf.text.pdf.PdfPRow.writeCells(PdfPRow.java:549)
at com.itextpdf.text.pdf.PdfPTable.writeSelectedRows(PdfPTable.java:764)
at com.itextpdf.text.pdf.PdfPTable.writeSelectedRows(PdfPTable.java:889)
at com.itextpdf.text.pdf.PdfPTable.writeSelectedRows(PdfPTable.java:837)
at com.itextpdf.text.pdf.PdfPTable.writeSelectedRows(PdfPTable.java:815)
at org.mapfish.print.config.layout.ColumnsBlock$1.render(ColumnsBlock.java:67)
at org.mapfish.print.PDFCustomBlocks.addAbsoluteDrawer(PDFCustomBlocks.java:183)
at org.mapfish.print.config.layout.ColumnsBlock.render(ColumnsBlock.java:56)
at org.mapfish.print.config.layout.Page.render(Page.java:73)
at org.mapfish.print.config.layout.MainPage.render(MainPage.java:63)
at org.mapfish.print.config.layout.Layout.render(Layout.java:59)
at org.mapfish.print.output.AbstractOutputFormat.doPrint(AbstractOutputFormat.java:30)
at org.mapfish.print.output.PdfOutputFactory.print(PdfOutputFactory.java:58)
at org.mapfish.print.MapPrinter.print(MapPrinter.java:173)
at org.mapfish.print.servlet.MapPrinterServlet.doCreatePDFFile(MapPrinterServlet.java:366)
at org.mapfish.print.servlet.MapPrinterServlet.createPDF(MapPrinterServlet.java:184)
at org.mapfish.print.servlet.MapPrinterServlet.doPost(MapPrinterServlet.java:112)
```

**Comment by pmauduit** [comment]
https://github.com/mapfish/mapfish-print/issues/133

**Comment by pmauduit** [comment]
"A quick workaround is to use the name param for all the !map block in the yaml file, both for the main map and overview (same value for both)."

We either backport his fix into our custom georchestra version, or we hack around the config.yaml to use his workaround

**Comment by fvanderbiest** [comment]
https://github.com/georchestra/datadir/pull/172

**Comment by fvanderbiest** [comment]
The patch on datadir has not been ported to branches 19.04 and master.
Doing it.
