### ISSUE TITLE
geonetwork - groups are not synchronized when > 32 char

### ISSUE THREAD

**Issue by fvanderbiest** [georchestra/georchestra#2687]
https://github.com/georchestra/datadir/pull/62 introduced and https://github.com/georchestra/datadir/pull/166 fixed sync of geOrchestra Orgs into GeoNetwork groups

The issue is that, if the Org name is longer than 32 characters, GeoNetwork fails to sync with 
```
21/08/2019 17:52:002019-08-21 15:52:00,109 ERROR [geonetwork.ldap] - Unexpected error while synchronizing LDAP user in database
21/08/2019 17:52:00org.springframework.dao.DataIntegrityViolationException: could not execute batch; SQL [insert into geonetwork.Groups (defaultCategory_id, description, email, enableCategoriesRestriction, logo, name, referrer, website, id) values (?, ?, ?, ?, ?, ?, ?, ?, ?)]; nested exception is org.hibernate.exception.DataException: could not execute batch
21/08/2019 17:52:00 at org.springframework.orm.jpa.vendor.HibernateJpaDialect.convertHibernateAccessException(HibernateJpaDialect.java:263)
21/08/2019 17:52:00 at org.springframework.orm.jpa.vendor.HibernateJpaDialect.translateExceptionIfPossible(HibernateJpaDialect.java:225)
21/08/2019 17:52:00 at org.springframework.orm.jpa.JpaTransactionManager.doCommit(JpaTransactionManager.java:521)
21/08/2019 17:52:00 at org.springframework.transaction.support.AbstractPlatformTransactionManager.processCommit(AbstractPlatformTransactionManager.java:761)
21/08/2019 17:52:00 at org.springframework.transaction.support.AbstractPlatformTransactionManager.commit(AbstractPlatformTransactionManager.java:730)
21/08/2019 17:52:00 at org.springframework.transaction.interceptor.TransactionAspectSupport.commitTransactionAfterReturning(TransactionAspectSupport.java:485)
21/08/2019 17:52:00 at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:291)
21/08/2019 17:52:00 at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:96)
21/08/2019 17:52:00 at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
21/08/2019 17:52:00 at org.springframework.dao.support.PersistenceExceptionTranslationInterceptor.invoke(PersistenceExceptionTranslationInterceptor.java:136)
21/08/2019 17:52:00 at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
21/08/2019 17:52:00 at org.springframework.data.jpa.repository.support.LockModeRepositoryPostProcessor$LockModePopulatingMethodIntercceptor.invoke(LockModeRepositoryPostProcessor.java:92)
21/08/2019 17:52:00 at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
21/08/2019 17:52:00 at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:92)
21/08/2019 17:52:00 at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
21/08/2019 17:52:00 at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:208)
21/08/2019 17:52:00 at com.sun.proxy.$Proxy158.save(Unknown Source)
21/08/2019 17:52:00 at org.fao.geonet.kernel.security.ldap.LDAPSynchronizerJob.synchronizeGroup(LDAPSynchronizerJob.java:244)
21/08/2019 17:52:00 at org.fao.geonet.kernel.security.ldap.LDAPSynchronizerJob.runInTransaction(LDAPSynchronizerJob.java:131)
21/08/2019 17:52:00 at org.fao.geonet.kernel.security.ldap.LDAPSynchronizerJob.executeInternal(LDAPSynchronizerJob.java:95)
21/08/2019 17:52:00 at org.springframework.scheduling.quartz.QuartzJobBean.execute(QuartzJobBean.java:75)
21/08/2019 17:52:00 at org.quartz.core.JobRunShell.run(JobRunShell.java:213)
21/08/2019 17:52:00 at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:557)
21/08/2019 17:52:00Caused by: org.hibernate.exception.DataException: could not execute batch
21/08/2019 17:52:00 at org.hibernate.exception.internal.SQLStateConversionDelegate.convert(SQLStateConversionDelegate.java:135)
21/08/2019 17:52:00 at org.hibernate.exception.internal.StandardSQLExceptionConverter.convert(StandardSQLExceptionConverter.java:49)
21/08/2019 17:52:00 at org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHelper.java:126)
21/08/2019 17:52:00 at org.hibernate.engine.jdbc.batch.internal.BatchingBatch.performExecution(BatchingBatch.java:132)
21/08/2019 17:52:00 at org.hibernate.engine.jdbc.batch.internal.BatchingBatch.doExecuteBatch(BatchingBatch.java:111)
21/08/2019 17:52:00 at org.hibernate.engine.jdbc.batch.internal.AbstractBatchImpl.execute(AbstractBatchImpl.java:163)
21/08/2019 17:52:00 at org.hibernate.engine.jdbc.internal.JdbcCoordinatorImpl.executeBatch(JdbcCoordinatorImpl.java:226)
21/08/2019 17:52:00 at org.hibernate.engine.spi.ActionQueue.executeActions(ActionQueue.java:482)
21/08/2019 17:52:00 at org.hibernate.engine.spi.ActionQueue.executeActions(ActionQueue.java:349)
21/08/2019 17:52:00 at org.hibernate.event.internal.AbstractFlushingEventListener.performExecutions(AbstractFlushingEventListener.java:350)
21/08/2019 17:52:00 at org.hibernate.event.internal.DefaultFlushEventListener.onFlush(DefaultFlushEventListener.java:56)
21/08/2019 17:52:00 at org.hibernate.internal.SessionImpl.flush(SessionImpl.java:1222)
21/08/2019 17:52:00 at org.hibernate.internal.SessionImpl.managedFlush(SessionImpl.java:425)
21/08/2019 17:52:00 at org.hibernate.engine.transaction.internal.jdbc.JdbcTransaction.beforeTransactionCommit(JdbcTransaction.java:101)
21/08/2019 17:52:00 at org.hibernate.engine.transaction.spi.AbstractTransactionImpl.commit(AbstractTransactionImpl.java:177)
21/08/2019 17:52:00 at org.hibernate.jpa.internal.TransactionImpl.commit(TransactionImpl.java:77)
21/08/2019 17:52:00 at org.springframework.orm.jpa.JpaTransactionManager.doCommit(JpaTransactionManager.java:517)
21/08/2019 17:52:00 ... 20 more
21/08/2019 17:52:00Caused by: java.sql.BatchUpdateException: Batch entry 0 insert into geonetwork.Groups (defaultCategory_id, description, email, enableCategoriesRestriction, logo, name, referrer, website, id) values (NULL, NULL, NULL, 'n', NULL, 'Communauté d''agglomération Amiens Métropole', NULL, NULL, 4510) was aborted: ERROR: value too long for type character varying(32) Call getNextException to see other errors in the batch.
21/08/2019 17:52:00 at org.postgresql.jdbc.BatchResultHandler.handleError(BatchResultHandler.java:151)
21/08/2019 17:52:00 at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2159)
21/08/2019 17:52:00 at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:463)
21/08/2019 17:52:00 at org.postgresql.jdbc.PgStatement.executeBatch(PgStatement.java:794)
21/08/2019 17:52:00 at org.postgresql.jdbc.PgPreparedStatement.executeBatch(PgPreparedStatement.java:1662)
21/08/2019 17:52:00 at org.apache.commons.dbcp.DelegatingStatement.executeBatch(DelegatingStatement.java:297)
21/08/2019 17:52:00 at org.apache.commons.dbcp.DelegatingStatement.executeBatch(DelegatingStatement.java:297)
21/08/2019 17:52:00 at org.apache.commons.dbcp.DelegatingStatement.executeBatch(DelegatingStatement.java:297)
21/08/2019 17:52:00 at org.hibernate.engine.jdbc.batch.internal.BatchingBatch.performExecution(BatchingBatch.java:123)
21/08/2019 17:52:00 ... 33 more
21/08/2019 17:52:00Caused by: org.postgresql.util.PSQLException: ERROR: value too long for type character varying(32)
21/08/2019 17:52:00 at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2458)
21/08/2019 17:52:00 at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2158)
21/08/2019 17:52:00 ... 40 more
```

**Comment by landryb** [comment]
well i guess that means filing a bug upstream to bump the field to a larger size in the hibernate spaghetti ?

**Comment by fvanderbiest** [comment]
Agreed. I leave it to our GN commiters ;-)

**Comment by RemiDesgrange** [comment]
>well i guess that means filing a bug upstream to bump the field to a larger size in the hibernate spaghetti ?

Or simply using a `TEXT` field ;-)

**Comment by fvanderbiest** [comment]
Of course, as pointed by @cmangeat , if we could sync not only a label but also an identifier for the group, that would be awesome.
