### ISSUE TITLE
#2713 broke saving user in console

### ISSUE THREAD

**Issue by landryb** [georchestra/georchestra#2725]
Since the addition of the ssh pubkey attr, saving an user in the console blows, cf trace in https://github.com/georchestra/georchestra/pull/2713#issuecomment-534095703

Now looking a bit at the code, i think the `ldapPublicKey` objectclass should be added to https://github.com/georchestra/georchestra/blob/master/console/src/main/java/org/georchestra/console/ds/AccountDaoImpl.java#L423 - testing it here fixes the crash.

**Comment by landryb** [comment]
I think a bit more is needed somewhere, as trying to add a user to an org (ie modifying the user, as it does a POST on users/testusers ?) also blows:
```
2019-09-27 10:18:23 GlobalExceptionHandler [ERROR] org.springframework.ldap.SchemaViolationException: [LDAP: error code 65 - object class 'ldapPublicKey' requires attribute 'sshPublicKey']; nested exception is javax.naming.directory.SchemaViolationException: [LDAP: error code 65 - object class 'ldapPublicKey' requires attribute 'sshPublicKey']; remaining name 'uid=testuser,ou=users'
        at org.springframework.ldap.support.LdapUtils.convertLdapException(LdapUtils.java:219)
        at org.springframework.ldap.core.LdapTemplate.executeWithContext(LdapTemplate.java:820)
        at org.springframework.ldap.core.LdapTemplate.executeReadWrite(LdapTemplate.java:812)
        at org.springframework.ldap.core.LdapTemplate.modifyAttributes(LdapTemplate.java:964)
        at org.springframework.ldap.core.LdapTemplate.modifyAttributes(LdapTemplate.java:1317)
        at org.georchestra.console.ds.AccountDaoImpl.update(AccountDaoImpl.java:205)
        at org.georchestra.console.ds.AccountDaoImpl.update(AccountDaoImpl.java:215)
        at org.georchestra.console.ws.backoffice.users.UsersController.update(UsersController.java:455)
        at org.georchestra.console.ws.backoffice.users.UsersController$$FastClassBySpringCGLIB$$dc097845.invoke(<generated>)
        at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204)
        at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:667)
        at org.georchestra.console.ws.backoffice.users.UsersController$$EnhancerBySpringCGLIB$$a50410f7.update(<generated>)
```

my guess is that the backend needs to map the `sshPublicKey` attribute to a java property with a getter/setter, like the other attributes in the `mapToContext()` method ? @pmauduit ?

**Comment by pmauduit** [comment]
> my guess is that the backend needs to map the `sshPublicKey` attribute to a java property with a getter/setter, like the other attributes in the `mapToContext()` method ? @pmauduit ?

When I PR'd, I was pretty sure it was acceptable not to have every possible fields mapped, and I thought that when the fields were not mapped to the POJO, they would just be ignored, but it seems that I was wrong, sorry about that.

**Comment by landryb** [comment]
to trigger this other crash i had to go on the member list of an org and try to add a member to the org - that does the POST on  users/testusers, and blows.

Modifying the org on the user page (ie setting/dropping/changing) doesnt trigger this crash.
