### ISSUE TITLE
SP - missing return after sendError()

### ISSUE THREAD

**Issue by pmauduit** [georchestra/georchestra#3151]
In this particular case:
https://github.com/georchestra/georchestra/blob/master/security-proxy/src/main/java/org/georchestra/security/Proxy.java#L461-L465

calling sendError() is the last thing we can do with the response, trying to write afterwards will fail.

**Comment by landryb** [comment]
oh that's what is filling my s-p catalina.log ?
```
30-Sep-2020 12:27:01.611 GRAVE [http-nio-8180-exec-4] org.apache.catalina.core.StandardWrapperValve.invoke Servlet.service() du Servlet [proxy] dans le contexte au chemin [] a retourné une exception [Request processing failed; nested exception is java.lang.IllegalStateException: Impossible d'appeler "sendError()" après que la réponse ait été envoyée] avec la cause
        java.lang.IllegalStateException: Impossible d'appeler "sendError()" après que la réponse ait été envoyée
                at org.apache.catalina.connector.ResponseFacade.sendError(ResponseFacade.java:472)
                at javax.servlet.http.HttpServletResponseWrapper.sendError(HttpServletResponseWrapper.java:129)
                at javax.servlet.http.HttpServletResponseWrapper.sendError(HttpServletResponseWrapper.java:129)
                at org.springframework.security.web.util.OnCommittedResponseWrapper.sendError(OnCommittedResponseWrapper.java:109)
                at javax.servlet.http.HttpServletResponseWrapper.sendError(HttpServletResponseWrapper.java:129)
                at org.springframework.security.web.util.OnCommittedResponseWrapper.sendError(OnCommittedResponseWrapper.java:109)
                at org.georchestra.security.Proxy.handleRequest(Proxy.java:751)
                at org.georchestra.security.Proxy.handlePathEncodedRequests(Proxy.java:540)
                at org.georchestra.security.Proxy.handleRequest(Proxy.java:376)
                at sun.reflect.GeneratedMethodAccessor106.invoke(Unknown Source)
                at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
                at java.lang.reflect.Method.invoke(Method.java:498)
                at org.springframework.web.bind.annotation.support.HandlerMethodInvoker.invokeHandlerMethod(HandlerMethodInvoker.java:181)
                at org.springframework.web.servlet.mvc.annotation.AnnotationMethodHandlerAdapter.invokeHandlerMethod(AnnotationMethodHandlerAdapter.java:440)
                at org.springframework.web.servlet.mvc.annotation.AnnotationMethodHandlerAdapter.handle(AnnotationMethodHandlerAdapter.java:428)
                at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:967)
                at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:901)
                at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:970)
                at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:861)
                at javax.servlet.http.HttpServlet.service(HttpServlet.java:634)
                at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:846)
                at javax.servlet.http.HttpServlet.service(HttpServlet.java:741)
                at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
                at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
                at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
                at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
                at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
                at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:317)
                at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.invoke(FilterSecurityInterceptor.java:116)
                at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.doFilter(FilterSecurityInterceptor.java:91)
                at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
                at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.invoke(FilterSecurityInterceptor.java:127)
                at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.doFilter(FilterSecurityInterceptor.java:91)
                at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
                at org.springframework.security.web.access.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:114)
                at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
                at org.springframework.security.web.session.SessionManagementFilter.doFilter(SessionManagementFilter.java:137)
                at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
                at org.springframework.security.web.authentication.AnonymousAuthenticationFilter.doFilter(AnonymousAuthenticationFilter.java:111)
                at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
                at org.springframework.security.web.servletapi.SecurityContextHolderAwareRequestFilter.doFilter(SecurityContextHolderAwareRequestFilter.java:170)
                at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
                at org.springframework.security.web.savedrequest.RequestCacheAwareFilter.doFilter(RequestCacheAwareFilter.java:63)
                at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
                at org.springframework.security.web.authentication.AbstractAuthenticationProcessingFilter.doFilter(AbstractAuthenticationProcessingFilter.java:200)
                at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
                at org.georchestra.security.BasicAuthChallengeByUserAgent.doFilterInternal(BasicAuthChallengeByUserAgent.java:100)
```

**Comment by landryb** [comment]
line numbers are from 20.0.x, and it seems this sendError() call is the only one lacking a return after it (or a direct function exit) - but that particular case or 'recursive call' feels weird - i'll see if i can figure out the request which triggers it.

**Comment by RemiDesgrange** [comment]
You have to have a SP behind another SP. This is niche usercase. But have one of those :-)

**Comment by RemiDesgrange** [comment]
https://github.com/georchestra/georchestra/blob/2b1761d881350db31f04637f985c94766a649917/security-proxy/README.md#sp-trust-sp-feature

**Comment by landryb** [comment]
well, i'm seeing the aforementioned traceback in my sp logs, and i dont have an SP behind another SP, only nginx->SP->nginx->otherwebapp (nginxes are here for load balancing/routing purposes)

**Comment by landryb** [comment]
the 'second call' to `sendError()` is here https://github.com/georchestra/georchestra/blob/20.0.x/security-proxy/src/main/java/org/georchestra/security/Proxy.java#L751 - but i dunno what would give me the first call..
