### ISSUE TITLE
[datafeeder] failure to publish a layer to GS

### ISSUE THREAD

**Issue by landryb** [georchestra/georchestra#3393]
managed to publish a point layer with EPSG:4236, a polygon layer with EPSG:2154, but another layer fails -datafeeder log:
```
2021-05-12 14:45:58.798  INFO 30518 --- [         task-9] o.g.datafeeder.batch.service.JobManager  : Launching publishing job f63b44cb-7739-4f13-802c-00489ec096d6
2021-05-12 14:45:58.805  INFO 30518 --- [         task-9] o.s.b.c.l.support.SimpleJobLauncher      : Job: [SimpleJob: [name=publishJob]] launched with the following parameters: [{uploadId=f63b44cb-7739-4f13-802c-00489ec096d6, user={"username":"testadmin","roles":["ROLE_SUPERUSER","ROLE_MAPSTORE_ADMIN","ROLE_USER","ROLE_ADMINISTRATOR","ROLE_CKAN_SYSADMIN","ROLE_EXTRACTORAPP","ROLE_GN_ADMIN","ROLE_EMAILPROXY"],"firstName":"Test","lastName":"ADMIN","organization":{"id":"psc","name":"Project Steering Committee","linkage":null,"postalAddress":null,"category":null,"description":null,"notes":null},"email":"psc+testadmin@georchestra.org","postalAddress":null,"telephoneNumber":null,"title":null,"notes":null}}]
2021-05-12 14:45:58.808  INFO 30518 --- [         task-9] o.g.d.b.service.PublishingBatchService   : Publish f63b44cb-7739-4f13-802c-00489ec096d6: Initialize job status to RUNNING
2021-05-12 14:45:58.821  INFO 30518 --- [         task-9] o.s.batch.core.job.SimpleStepHandler     : Executing step: [preparePostGisStep]
2021-05-12 14:45:58.825  INFO 30518 --- [         task-9] o.g.d.b.service.PublishingBatchService   : Publish f63b44cb-7739-4f13-802c-00489ec096d6: Prepare target store for uploaded datasets
2021-05-12 14:45:58.886  INFO 30518 --- [         task-9] o.s.batch.core.step.AbstractStep         : Step: [preparePostGisStep] executed in 64ms
2021-05-12 14:45:58.892  INFO 30518 --- [         task-9] o.s.batch.core.job.SimpleStepHandler     : Executing step: [postGisStep]
2021-05-12 14:45:58.894  INFO 30518 --- [         task-9] o.g.d.b.service.PublishingBatchService   : Publish f63b44cb-7739-4f13-802c-00489ec096d6: importing datasets to target database
2021-05-12 14:45:58.984  INFO 30518 --- [         task-9] o.g.datafeeder.service.DatasetsService   : Creating FeatureType craig_couverture_pcrs_ain_isere
2021-05-12 14:45:59.057  WARN 30518 --- [         task-9] org.geotools.jdbc                        : Fetching fields from Database
2021-05-12 14:45:59.130  INFO 30518 --- [         task-9] o.g.datafeeder.service.DatasetsService   : FeatureType craig_couverture_pcrs_ain_isere created successfully
2021-05-12 14:45:59.161  INFO 30518 --- [         task-9] o.g.datafeeder.service.DatasetsService   : Uploading data to craig_couverture_pcrs_ain_isere
2021-05-12 14:45:59.197  INFO 30518 --- [         task-9] o.g.datafeeder.service.DatasetsService   : Data imported to craig_couverture_pcrs_ain_isere in 36.48 ms
2021-05-12 14:45:59.211  INFO 30518 --- [         task-9] o.s.batch.core.step.AbstractStep         : Step: [postGisStep] executed in 319ms
2021-05-12 14:45:59.217  INFO 30518 --- [         task-9] o.s.batch.core.job.SimpleStepHandler     : Executing step: [geoserverStep]
2021-05-12 14:45:59.219  INFO 30518 --- [         task-9] o.g.d.b.service.PublishingBatchService   : Publish f63b44cb-7739-4f13-802c-00489ec096d6: Publish datasets to GeoServer
2021-05-12 14:45:59.508  INFO 30518 --- [         task-9] o.s.batch.core.step.AbstractStep         : Step: [geoserverStep] executed in 291ms
2021-05-12 14:45:59.511  INFO 30518 --- [         task-9] o.s.batch.core.job.SimpleStepHandler     : Executing step: [geonetworkStep]
2021-05-12 14:45:59.513  INFO 30518 --- [         task-9] o.g.d.b.service.PublishingBatchService   : Publish f63b44cb-7739-4f13-802c-00489ec096d6: Publish datasets metadata to GeoNetwork
2021-05-12 14:45:59.522  INFO 30518 --- [         task-9] o.s.batch.core.step.AbstractStep         : Step: [geonetworkStep] executed in 9ms
2021-05-12 14:45:59.524  INFO 30518 --- [         task-9] o.s.batch.core.job.SimpleStepHandler     : Executing step: [geoserverGeonetworkUpdateStep]
2021-05-12 14:45:59.526  INFO 30518 --- [         task-9] o.g.d.b.service.PublishingBatchService   : Publish f63b44cb-7739-4f13-802c-00489ec096d6: Add metadata links to GeoServer layer infos
2021-05-12 14:45:59.535  INFO 30518 --- [         task-9] o.s.batch.core.step.AbstractStep         : Step: [geoserverGeonetworkUpdateStep] executed in 11ms
2021-05-12 14:45:59.537  INFO 30518 --- [         task-9] .PublishJobLifeCycleStatusUpdateListener : publish job id: f63b44cb-7739-4f13-802c-00489ec096d6, status: COMPLETED
2021-05-12 14:45:59.537  INFO 30518 --- [         task-9] o.g.d.b.service.PublishingBatchService   : Publish f63b44cb-7739-4f13-802c-00489ec096d6: summarize status
2021-05-12 14:45:59.546  INFO 30518 --- [         task-9] o.g.d.b.service.PublishingBatchService   : Publish f63b44cb-7739-4f13-802c-00489ec096d6: summarized status is ERROR 'Error publishing the following datasets:
CRAIG_Couverture_PCRS_Ain_Isere: Status 400: 
Request: POST http://localhost:8380/geoserver/rest/workspaces/psc/datastores/datafeeder/featuretypes HTTP/1.1
Accept: application/json
Content-Length: 517
Content-Type: application/json
sec-roles: ROLE_ADMINISTRATOR
sec-username: datafeeder-application

{"featureType":"name":"CRAIG_Couverture_PCRS_Ain_Isere","nativeName":"CRAIG_Couverture_PCRS_Ain_Isere","namespace":{"prefix":"psc"},"title":"Couverture PCRS Ain et Isère","abstract":"Couverture du fond de plan orthophoto 5 cm réalisée et prévue sur les départements de l'Ain et de l'Isère.","enabled":true,"nativeBoundingBox":{"minx":828600.0,"maxx":965200.0000000003,"miny":6403399.99999999,"maxy":6604600.0},"projectionPolicy":"FORCE_DECLARED","advertised":true,"store":{"name":"datafeeder","enabled":true}}}'
2021-05-12 14:45:59.549  INFO 30518 --- [         task-9] o.s.b.c.l.support.SimpleJobLauncher      : Job: [SimpleJob: [name=publishJob]] completed with the following parameters: [{uploadId=f63b44cb-7739-4f13-802c-00489ec096d6, user={"username":"testadmin","roles":["ROLE_SUPERUSER","ROLE_MAPSTORE_ADMIN","ROLE_USER","ROLE_ADMINISTRATOR","ROLE_CKAN_SYSADMIN","ROLE_EXTRACTORAPP","ROLE_GN_ADMIN","ROLE_EMAILPROXY"],"firstName":"Test","lastName":"ADMIN","organization":{"id":"psc","name":"Project Steering Committee","linkage":null,"postalAddress":null,"category":null,"description":null,"notes":null},"email":"psc+testadmin@georchestra.org","postalAddress":null,"telephoneNumber":null,"title":null,"notes":null}}] and the following status: [COMPLETED] in 732ms
2021-05-12 14:45:59.549  INFO 30518 --- [         task-9] o.g.datafeeder.batch.service.JobManager  : Publishing job f63b44cb-7739-4f13-802c-00489ec096d6 finished with status COMPLETED

```
the layer is properly pushed to postgis, and has attributes.

traceback gs-side:
```
2021-05-12 14:45:59,242 INFO [rest.catalog] - GET psc
2021-05-12 14:45:59,242 INFO [rest.catalog] - got psc
2021-05-12 14:45:59,481 ERROR [geoserver.rest] - Trying to create new feature type inside the store, but no attributes were specified
org.geoserver.rest.RestException 400 BAD_REQUEST: Trying to create new feature type inside the store, but no attributes were specified
        at org.geoserver.rest.catalog.FeatureTypeController.buildFeatureType(FeatureTypeController.java:458)
        at org.geoserver.rest.catalog.FeatureTypeController.featureTypePost(FeatureTypeController.java:229)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:190)
        at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:138)
```

**Comment by landryb** [comment]
afaict datafeeder log seems to say that things were pushed to GS and GN, while there are no evidence of such things in GS and GN datadirs. previous tries with other datasets were fine though..

**Comment by landryb** [comment]
retrying after cleaning up tries/db:
```
2021-05-12 16:00:55.274  INFO 30518 --- [        task-19] o.s.batch.core.job.SimpleStepHandler     : Executing step: [geoserverStep]
2021-05-12 16:00:55.275  INFO 30518 --- [        task-19] o.g.d.b.service.PublishingBatchService   : Publish bf13edc4-c49a-489d-9990-aab58e3b3e70: Publish datasets to GeoServer

==> /srv/log/geoserver.log <==
2021-05-12 16:00:55,286 INFO [rest.catalog] - GET psc
2021-05-12 16:00:55,286 INFO [rest.catalog] - got psc

==> /tmp/datafeeder.log <==
2021-05-12 16:00:55.583 ERROR 30518 --- [      Finalizer] org.geotools.jdbc                        : State finalized with open connection.
2021-05-12 16:00:55.587 ERROR 30518 --- [      Finalizer] org.geotools.data                        : There's code leaving transaction unclosed. Call Transaction.close() after using them to ensure they do not hold state such as JDBC connections or file handles
2021-05-12 16:00:55.587 ERROR 30518 --- [      Finalizer] org.geotools.data                        : Unclosed transaction handle is 'org.georchestra.datafeeder.service.DatasetsService.importData Transaction'
2021-05-12 16:00:55.588 ERROR 30518 --- [      Finalizer] org.geotools.jdbc                        : There's code using JDBC based datastore and not disposing them. This may lead to temporary loss of database connections. Please make sure all data access code calls DataStore.dispose() before freeing all references to it
2021-05-12 16:00:55.589 ERROR 30518 --- [      Finalizer] org.geotools.jdbc                        : There's code using JDBC based datastore and not disposing them. This may lead to temporary loss of database connections. Please make sure all data access code calls DataStore.dispose() before freeing all references to it
2021-05-12 16:00:55.589 ERROR 30518 --- [      Finalizer] org.geotools.jdbc                        : State finalized with open connection.
2021-05-12 16:00:55.592 ERROR 30518 --- [      Finalizer] org.geotools.data                        : There's code leaving transaction unclosed. Call Transaction.close() after using them to ensure they do not hold state such as JDBC connections or file handles
2021-05-12 16:00:55.592 ERROR 30518 --- [      Finalizer] org.geotools.data                        : Unclosed transaction handle is 'org.georchestra.datafeeder.service.DatasetsService.importData Transaction'
2021-05-12 16:00:55.592 ERROR 30518 --- [      Finalizer] org.geotools.jdbc                        : State finalized with open connection.
2021-05-12 16:00:55.595 ERROR 30518 --- [      Finalizer] org.geotools.data                        : There's code leaving transaction unclosed. Call Transaction.close() after using them to ensure they do not hold state such as JDBC connections or file handles
2021-05-12 16:00:55.595 ERROR 30518 --- [      Finalizer] org.geotools.data                        : Unclosed transaction handle is 'org.georchestra.datafeeder.service.DatasetsService.importData Transaction'
2021-05-12 16:00:55.595 ERROR 30518 --- [      Finalizer] org.geotools.jdbc                        : There's code using JDBC based datastore and not disposing them. This may lead to temporary loss of database connections. Please make sure all data access code calls DataStore.dispose() before freeing all references to it
2021-05-12 16:00:55.595 ERROR 30518 --- [      Finalizer] org.geotools.jdbc                        : There's code using JDBC based datastore and not disposing them. This may lead to temporary loss of database connections. Please make sure all data access code calls DataStore.dispose() before freeing all references to it
2021-05-12 16:00:55.596 ERROR 30518 --- [      Finalizer] org.geotools.jdbc                        : State finalized with open connection.
2021-05-12 16:00:55.599 ERROR 30518 --- [      Finalizer] org.geotools.data                        : There's code leaving transaction unclosed. Call Transaction.close() after using them to ensure they do not hold state such as JDBC connections or file handles
2021-05-12 16:00:55.599 ERROR 30518 --- [      Finalizer] org.geotools.data                        : Unclosed transaction handle is 'org.georchestra.datafeeder.service.DatasetsService.importData Transaction'

==> /srv/log/geoserver.log <==
2021-05-12 16:00:55,611 ERROR [geoserver.rest] - Trying to create new feature type inside the store, but no attributes were specified
org.geoserver.rest.RestException 400 BAD_REQUEST: Trying to create new feature type inside the store, but no attributes were specified
        at org.geoserver.rest.catalog.FeatureTypeController.buildFeatureType(FeatureTypeController.java:458)
        at org.geoserver.rest.catalog.FeatureTypeController.featureTypePost(FeatureTypeController.java:229)
```

puzzling.. here's the testing file
[CRAIG_Couverture_PCRS_Ain_Isere.zip](https://github.com/georchestra/georchestra/files/6466676/CRAIG_Couverture_PCRS_Ain_Isere.zip)

**Comment by landryb** [comment]
Btw this is *outside* of docker, in a regular environment, deployed by georchestra/ansible#77

**Comment by groldan** [comment]
I can reproduce. Yet there's no difference with other datasets using the same projection that do work.
I'm going to have to debug geoserver itself.

**Comment by groldan** [comment]
This should fix it: #3409

**Comment by landryb** [comment]
nice one, thanks @groldan !

**Comment by fvanderbiest** [comment]
Thanks for testing @landryb !
