### ISSUE TITLE
[datafeeder] make it compatible with GN4

### ISSUE THREAD

**Issue by landryb** [georchestra/georchestra#3495]
GN4 will land soon (#3218), i've tested datafeeder against it and it seems it fails at some point when talking to GN4 API:
```
2021-08-27 15:48:51.824 ERROR 16352 --- [         task-4] o.g.d.b.service.PublishingBatchService   : <!doctype html><html lang="fr"><head><title>État HTTP 404 – Non trouvé</title><style type="text/css">body {font-family:Tahoma,Arial,sans-serif;} h1, h2, h3, b {color:white;background-color:#525D76;} h1 {font-size:22px;} h2 {font-size:16px;} h3 {font-size:14px;} p {font-size:12px;} a {color:black;} .line {height:1px;background-color:#525D76;border:none;}</style></head><body><h1>État HTTP 404 – Non trouvé</h1><hr class="line" /><p><b>Type</b> Rapport d'état</p><p><b>description</b> La ressource demandée n'est pas disponible.</p><hr class="line" /><h3>Apache Tomcat/9.0.31 (Debian)</h3></body></html>

org.fao.geonet.client.ApiException: <!doctype html><html lang="fr"><head><title>État HTTP 404 – Non trouvé</title><style type="text/css">body {font-family:Tahoma,Arial,sans-serif;} h1, h2, h3, b {color:white;background-color:#525D76;} h1 {font-size:22px;} h2 {font-size:16px;} h3 {font-size:14px;} p {font-size:12px;} a {color:black;} .line {height:1px;background-color:#525D76;border:none;}</style></head><body><h1>État HTTP 404 – Non trouvé</h1><hr class="line" /><p><b>Type</b> Rapport d'état</p><p><b>description</b> La ressource demandée n'est pas disponible.</p><hr class="line" /><h3>Apache Tomcat/9.0.31 (Debian)</h3></body></html>
        at org.fao.geonet.client.ApiClient.invokeAPI(ApiClient.java:719) ~[classes!/:na]
        at org.fao.geonet.client.GroupsApi.getGroupsWithHttpInfo(GroupsApi.java:348) ~[classes!/:na]
        at org.fao.geonet.client.GroupsApi.getGroups(GroupsApi.java:308) ~[classes!/:na]
        at org.georchestra.datafeeder.service.geonetwork.DefaultGeoNetworkClient.findGroupId(DefaultGeoNetworkClient.java:167) ~[classes!/:na]
        at org.georchestra.datafeeder.service.geonetwork.DefaultGeoNetworkClient.putXmlRecord(DefaultGeoNetworkClient.java:121) ~[classes!/:na]
        at org.georchestra.datafeeder.service.geonetwork.GeoNetworkRemoteService.publish(GeoNetworkRemoteService.java:120) ~[classes!/:na]
        at org.georchestra.datafeeder.service.publish.impl.GeorchestraMetadataPublicationService.publish(GeorchestraMetadataPublicationService.java:91) ~[classes!/:na]
        at org.georchestra.datafeeder.batch.service.PublishingBatchService.lambda$step3_publishDatasetsMetadataToGeoNetwork$4(PublishingBatchService.java:190) [classes!/:na]
        at org.georchestra.datafeeder.batch.service.PublishingBatchService.doOnEachRunningDataset(PublishingBatchService.java:218) [classes!/:na]
        at org.georchestra.datafeeder.batch.service.PublishingBatchService.step3_publishDatasetsMetadataToGeoNetwork(PublishingBatchService.java:186) [classes!/:na]
        at org.georchestra.datafeeder.batch.service.PublishingBatchService$$FastClassBySpringCGLIB$$23b074cb.invoke(<generated>) [classes!/:na]
        at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218) [spring-core-5.2.8.RELEASE.jar!/:5.2.8.RELEASE]
        at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:687) [spring-aop-5.2.8.RELEASE.jar!/:5.2.8.RELEASE]
        at org.georchestra.datafeeder.batch.service.PublishingBatchService$$EnhancerBySpringCGLIB$$c61e20bc.step3_publishDatasetsMetadataToGeoNetwork(<generated>) [classes!/:na]
        at org.georchestra.datafeeder.batch.publish.GeoNetworkTasklet.execute(GeoNetworkTasklet.java:52) [classes!/:na]
        at org.georchestra.datafeeder.batch.publish.GeoNetworkTasklet$$FastClassBySpringCGLIB$$bfb1936.invoke(<generated>) [classes!/:na]
        at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218) [spring-core-5.2.8.RELEASE.jar!/:5.2.8.RELEASE]

```

**Comment by landryb** [comment]
yes, that's more or less what i have - so we can close this issue when #3497 is merged (and someone tests datafeeder import on top :) ).

**Comment by landryb** [comment]
master still doesnt build, but at least this issue can be closed
