### ISSUE TITLE
extractorapp - extraction fails if metadata is not available

### ISSUE THREAD

**Issue by severo** [georchestra/georchestra#357]
If metadata is not available, the following logs appear in extractorapp.log

```
java.io.IOException: java.lang.SecurityException: The metadata is not available: http://www.geopicardie.fr/geonetwork/srv/fre/xml.metadata.get?uuid=c3bf8ed4-2967-4800-ad9c-33d9bf87ab94
        at org.georchestra.extractorapp.ws.extractor.csw.CSWExtractor.checkPermission(CSWExtractor.java:95)
        at org.georchestra.extractorapp.ws.extractor.task.ExtractionTask.extractMetadata(ExtractionTask.java:415)
        at org.georchestra.extractorapp.ws.extractor.task.ExtractionTask.run(ExtractionTask.java:104)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
        at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:334)
        at java.util.concurrent.FutureTask.run(FutureTask.java:166)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:724)
Caused by: java.lang.SecurityException: The metadata is not available: http://www.geopicardie.fr/geonetwork/srv/fre/xml.metadata.get?uuid=c3bf8ed4-2967-4800-ad9c-33d9bf87ab94
        at org.georchestra.extractorapp.ws.extractor.csw.CSWExtractor.checkPermission(CSWExtractor.java:91)
        ... 8 more
```

and the following mail is sent

```
The extraction job you submitted to the geOrchestra platform has finished.

Download your file at http://vm-georchestra/extractorapp/extractor/package?uuid=02721c12-5369-4d9c-983d-30dbbff2d665. It will be available during 10 days.

The following layers have been extracted successfully:

None


The following layers could not be extracted. The failures.html file contains more informations:

* www.geopicardie.fr__reg22:lycees_adresses



The following layers' extraction has been canceled. The requested area is too large:

None


---
Sent by geOrchestra (http://vm-georchestra/)
```

with no `failures.html` file joined (maybe due to https://github.com/georchestra/georchestra/commit/6a17ccf0fa5176d4ad34219f64fe7b41b1b00c08).

**Comment by fvanderbiest** [comment]
fixed with #1650
