### ISSUE TITLE
geonetwork 4.0.6

### ISSUE THREAD

**Issue by fvanderbiest** [georchestra/georchestra#3607]
The release contains numerous fixes !
Upgrading is probably a good idea

**Comment by pmauduit** [comment]
I did a rebase with the following branch:
https://github.com/georchestra/geonetwork/tree/rebased-onto-upstream-4.0.6

We could consider replacing the georchestra-gn4.x branch by this one, testsuite OK, needs to be tested at runtime. A docker image as well as a war have been produced:
* https://github.com/georchestra/geonetwork/actions/runs/1790642290 
* https://hub.docker.com/layers/georchestra/geonetwork/4.x-rebased/images/sha256-8e7645edca33e17eeff1c47cb93fa37099dc490c42dbe54902a41bf06b6b4742?context=explore

to be tested at runtime.

**Comment by landryb** [comment]
tested here, starts fine after fiddling a bit with some spring XML.

sadly, it still fails to properly *reload* (eg `touch web.xml`, already failing with 4.0.5, used to work with 3.8):
```
2022-02-04 09:37:12,678 ERROR [jeeves] - JeevesContextLoaderListener: Error creating bean with name 'org.fao.geonet.camelPeriodicProducer.MessageProducerFactory#0': Invocation of init method failed; nested exception is org.quartz.SchedulerException: Unable to register scheduler with MBeanServer. [See nested exception: javax.management.InstanceAlreadyExistsException: quartz:type=QuartzScheduler,name=DefaultQuartzScheduler-harvest-wfs,instance=NON_CLUSTERED]
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'org.fao.geonet.camelPeriodicProducer.MessageProducerFactory#0': Invocation of init method failed; nested exception is org.quartz.SchedulerException: Unable to register scheduler with MBeanServer. [See nested exception: javax.management.InstanceAlreadyExistsException: quartz:type=QuartzScheduler,name=DefaultQuartzScheduler-harvest-wfs,instance=NON_CLUSTERED]
        at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor.postProcessBeforeInitialization(InitDestroyAnnotationBeanPostProcessor.java:160)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyBeanPostProcessorsBeforeInitialization(AbstractAutowireCapableBeanFactory.java:416)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1788)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:595)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:517)
        at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:323)
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:226)
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:321)
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:202)
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:895)
        at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:878)
        at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:550)
        at jeeves.config.springutil.JeevesContextLoaderListener.contextInitialized(JeevesContextLoaderListener.java:80)
        at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:4716)
        at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5177)
        at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
        at org.apache.catalina.core.StandardContext.reload(StandardContext.java:3792)
        at org.apache.catalina.startup.HostConfig.reload(HostConfig.java:1347)
        at org.apache.catalina.startup.HostConfig.checkResources(HostConfig.java:1320)
        at org.apache.catalina.startup.HostConfig.check(HostConfig.java:1555)
        at org.apache.catalina.startup.HostConfig.lifecycleEvent(HostConfig.java:305)
        at org.apache.catalina.util.LifecycleBase.fireLifecycleEvent(LifecycleBase.java:123)
        at org.apache.catalina.core.ContainerBase.backgroundProcess(ContainerBase.java:1151)
        at org.apache.catalina.core.ContainerBase$ContainerBackgroundProcessor.processChildren(ContainerBase.java:1353)
        at org.apache.catalina.core.ContainerBase$ContainerBackgroundProcessor.processChildren(ContainerBase.java:1357)
        at org.apache.catalina.core.ContainerBase$ContainerBackgroundProcessor.run(ContainerBase.java:1335)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
        at java.lang.Thread.run(Thread.java:748)
Caused by: org.quartz.SchedulerException: Unable to register scheduler with MBeanServer. [See nested exception: javax.management.InstanceAlreadyExistsException: quartz:type=QuartzScheduler,name=DefaultQuartzScheduler-harvest-wfs,instance=NON_CLUSTERED]
        at org.quartz.core.QuartzScheduler.initialize(QuartzScheduler.java:245)
        at org.quartz.impl.StdSchedulerFactory.instantiate(StdSchedulerFactory.java:1372)
        at org.quartz.impl.StdSchedulerFactory.getScheduler(StdSchedulerFactory.java:1579)
        at org.apache.camel.component.quartz2.QuartzComponent.createScheduler(QuartzComponent.java:339)
        at org.apache.camel.component.quartz2.QuartzComponent.createAndInitScheduler(QuartzComponent.java:321)
        at org.apache.camel.component.quartz2.QuartzComponent.doStart(QuartzComponent.java:315)
        at org.apache.camel.support.ServiceSupport.start(ServiceSupport.java:72)
        at org.fao.geonet.camelPeriodicProducer.MessageProducerFactory.init(MessageProducerFactory.java:47)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor$LifecycleElement.invoke(InitDestroyAnnotationBeanPostProcessor.java:389)
        at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor$LifecycleMetadata.invokeInitMethods(InitDestroyAnnotationBeanPostProcessor.java:333)
        at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor.postProcessBeforeInitialization(InitDestroyAnnotationBeanPostProcessor.java:157)
        ... 33 more
Caused by: javax.management.InstanceAlreadyExistsException: quartz:type=QuartzScheduler,name=DefaultQuartzScheduler-harvest-wfs,instance=NON_CLUSTERED
        at com.sun.jmx.mbeanserver.Repository.addMBean(Repository.java:437)
        at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.registerWithRepository(DefaultMBeanServerInterceptor.java:1898)
        at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.registerDynamicMBean(DefaultMBeanServerInterceptor.java:966)
        at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.registerObject(DefaultMBeanServerInterceptor.java:900)
        at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.registerMBean(DefaultMBeanServerInterceptor.java:324)
        at com.sun.jmx.mbeanserver.JmxMBeanServer.registerMBean(JmxMBeanServer.java:522)
        at org.quartz.core.QuartzScheduler.registerJMX(QuartzScheduler.java:343)
        at org.quartz.core.QuartzScheduler.initialize(QuartzScheduler.java:243)
        ... 47 more
2022-02-04 09:37:12,682 FATAL [jeeves.engine] - Raised exception during init
2022-02-04 09:37:12,682 FATAL [jeeves.engine] -    Exception : org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'org.fao.geonet.camelPeriodicProducer.MessageProducerFactory#0': Invocation of init method failed; nested exception is org.quartz.SchedulerException: Unable to register scheduler with MBeanServer. [See nested exception: javax.management.InstanceAlreadyExistsException: quartz:type=QuartzScheduler,name=DefaultQuartzScheduler-harvest-wfs,instance=NON_CLUSTERED]
2022-02-04 09:37:12,682 FATAL [jeeves.engine] -    Message   : Error creating bean with name 'org.fao.geonet.camelPeriodicProducer.MessageProducerFactory#0': Invocation of init method failed; nested exception is org.quartz.SchedulerException: Unable to register scheduler with MBeanServer. [See nested exception: javax.management.InstanceAlreadyExistsException: quartz:type=QuartzScheduler,name=DefaultQuartzScheduler-harvest-wfs,instance=NON_CLUSTERED]
2022-02-04 09:37:12,684 FATAL [jeeves.engine] -    Stack     : org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'org.fao.geonet.camelPeriodicProducer.MessageProducerFactory#0': Invocation of init method failed; nested exception is org.quartz.SchedulerException: Unable to register scheduler with MBeanServer. [See nested exception: javax.management.InstanceAlreadyExistsException: quartz:type=QuartzScheduler,name=DefaultQuartzScheduler-harvest-wfs,instance=NON_CLUSTERED]
        at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor.postProcessBeforeInitialization(InitDestroyAnnotationBeanPostProcessor.java:160)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyBeanPostProcessorsBeforeInitialization(AbstractAutowireCapableBeanFactory.java:416)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1788)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:595)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:517)
        at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:323)
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:226)
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:321)
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:202)
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:895)
        at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:878)
        at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:550)
        at jeeves.config.springutil.JeevesContextLoaderListener.contextInitialized(JeevesContextLoaderListener.java:80)
        at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:4716)
        at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5177)
        at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
        at org.apache.catalina.core.StandardContext.reload(StandardContext.java:3792)
        at org.apache.catalina.startup.HostConfig.reload(HostConfig.java:1347)
        at org.apache.catalina.startup.HostConfig.checkResources(HostConfig.java:1320)
        at org.apache.catalina.startup.HostConfig.check(HostConfig.java:1555)
        at org.apache.catalina.startup.HostConfig.lifecycleEvent(HostConfig.java:305)
        at org.apache.catalina.util.LifecycleBase.fireLifecycleEvent(LifecycleBase.java:123)
        at org.apache.catalina.core.ContainerBase.backgroundProcess(ContainerBase.java:1151)
        at org.apache.catalina.core.ContainerBase$ContainerBackgroundProcessor.processChildren(ContainerBase.java:1353)
        at org.apache.catalina.core.ContainerBase$ContainerBackgroundProcessor.processChildren(ContainerBase.java:1357)
        at org.apache.catalina.core.ContainerBase$ContainerBackgroundProcessor.run(ContainerBase.java:1335)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
        at java.lang.Thread.run(Thread.java:748)
Caused by: org.quartz.SchedulerException: Unable to register scheduler with MBeanServer. [See nested exception: javax.management.InstanceAlreadyExistsException: quartz:type=QuartzScheduler,name=DefaultQuartzScheduler-harvest-wfs,instance=NON_CLUSTERED]
        at org.quartz.core.QuartzScheduler.initialize(QuartzScheduler.java:245)
        at org.quartz.impl.StdSchedulerFactory.instantiate(StdSchedulerFactory.java:1372)
        at org.quartz.impl.StdSchedulerFactory.getScheduler(StdSchedulerFactory.java:1579)
        at org.apache.camel.component.quartz2.QuartzComponent.createScheduler(QuartzComponent.java:339)
        at org.apache.camel.component.quartz2.QuartzComponent.createAndInitScheduler(QuartzComponent.java:321)
        at org.apache.camel.component.quartz2.QuartzComponent.doStart(QuartzComponent.java:315)
        at org.apache.camel.support.ServiceSupport.start(ServiceSupport.java:72)
        at org.fao.geonet.camelPeriodicProducer.MessageProducerFactory.init(MessageProducerFactory.java:47)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor$LifecycleElement.invoke(InitDestroyAnnotationBeanPostProcessor.java:389)
        at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor$LifecycleMetadata.invokeInitMethods(InitDestroyAnnotationBeanPostProcessor.java:333)
        at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor.postProcessBeforeInitialization(InitDestroyAnnotationBeanPostProcessor.java:157)
        ... 33 more
Caused by: javax.management.InstanceAlreadyExistsException: quartz:type=QuartzScheduler,name=DefaultQuartzScheduler-harvest-wfs,instance=NON_CLUSTERED
        at com.sun.jmx.mbeanserver.Repository.addMBean(Repository.java:437)
        at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.registerWithRepository(DefaultMBeanServerInterceptor.java:1898)
        at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.registerDynamicMBean(DefaultMBeanServerInterceptor.java:966)
        at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.registerObject(DefaultMBeanServerInterceptor.java:900)
        at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.registerMBean(DefaultMBeanServerInterceptor.java:324)
        at com.sun.jmx.mbeanserver.JmxMBeanServer.registerMBean(JmxMBeanServer.java:522)
        at org.quartz.core.QuartzScheduler.registerJMX(QuartzScheduler.java:343)
        at org.quartz.core.QuartzScheduler.initialize(QuartzScheduler.java:243)
        ... 47 more

<2>Exception lors de l'envoi de l'évènement contexte initialisé (context initialized) à l'instance de classe d'écoute (listener) [jeeves.config.springutil.JeevesContextLoaderListener]
<2>java.lang.RuntimeException: Exception raised
<2>    at jeeves.server.JeevesEngine.handleStartupError(JeevesEngine.java:108)
<2>    at jeeves.config.springutil.JeevesContextLoaderListener.contextInitialized(JeevesContextLoaderListener.java:94)
<2>    at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:4716)
<2>    at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5177)
<2>    at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
<2>    at org.apache.catalina.core.StandardContext.reload(StandardContext.java:3792)
<2>    at org.apache.catalina.startup.HostConfig.reload(HostConfig.java:1347)
<2>    at org.apache.catalina.startup.HostConfig.checkResources(HostConfig.java:1320)
<2>    at org.apache.catalina.startup.HostConfig.check(HostConfig.java:1555)
<2>    at org.apache.catalina.startup.HostConfig.lifecycleEvent(HostConfig.java:305)
<2>    at org.apache.catalina.util.LifecycleBase.fireLifecycleEvent(LifecycleBase.java:123)
<2>    at org.apache.catalina.core.ContainerBase.backgroundProcess(ContainerBase.java:1151)
<2>    at org.apache.catalina.core.ContainerBase$ContainerBackgroundProcessor.processChildren(ContainerBase.java:1353)
<2>    at org.apache.catalina.core.ContainerBase$ContainerBackgroundProcessor.processChildren(ContainerBase.java:1357)
<2>    at org.apache.catalina.core.ContainerBase$ContainerBackgroundProcessor.run(ContainerBase.java:1335)
<2>    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
<2>    at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
<2>    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
<2>    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
<2>    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
<2>    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
<2>    at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
<2>    at java.lang.Thread.run(Thread.java:748)
<2>Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'org.fao.geonet.camelPeriodicProducer.MessageProducerFactory#0': Invocation of init method failed; nested exception is org.quartz.SchedulerException: Unable to register scheduler with MBeanServer. [See nested exception: javax.management.InstanceAlreadyExistsException: quartz:type=QuartzScheduler,name=DefaultQuartzScheduler-harvest-wfs,instance=NON_CLUSTERED]
<2>    at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor.postProcessBeforeInitialization(InitDestroyAnnotationBeanPostProcessor.java:160)
<2>    at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyBeanPostProcessorsBeforeInitialization(AbstractAutowireCapableBeanFactory.java:416)
<2>    at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1788)
<2>    at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:595)
<2>    at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:517)
<2>    at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:323)
<2>    at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:226)
<2>    at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:321)
<2>    at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:202)
<2>    at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:895)
<2>    at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:878)
<2>    at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:550)
<2>    at jeeves.config.springutil.JeevesContextLoaderListener.contextInitialized(JeevesContextLoaderListener.java:80)
<2>    ... 21 more
<2>Caused by: org.quartz.SchedulerException: Unable to register scheduler with MBeanServer. [See nested exception: javax.management.InstanceAlreadyExistsException: quartz:type=QuartzScheduler,name=DefaultQuartzScheduler-harvest-wfs,instance=NON_CLUSTERED]
<2>    at org.quartz.core.QuartzScheduler.initialize(QuartzScheduler.java:245)
<2>    at org.quartz.impl.StdSchedulerFactory.instantiate(StdSchedulerFactory.java:1372)
<2>    at org.quartz.impl.StdSchedulerFactory.getScheduler(StdSchedulerFactory.java:1579)
<2>    at org.apache.camel.component.quartz2.QuartzComponent.createScheduler(QuartzComponent.java:339)
<2>    at org.apache.camel.component.quartz2.QuartzComponent.createAndInitScheduler(QuartzComponent.java:321)
<2>    at org.apache.camel.component.quartz2.QuartzComponent.doStart(QuartzComponent.java:315)
<2>    at org.apache.camel.support.ServiceSupport.start(ServiceSupport.java:72)
<2>    at org.fao.geonet.camelPeriodicProducer.MessageProducerFactory.init(MessageProducerFactory.java:47)
<2>    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
<2>    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
<2>    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
<2>    at java.lang.reflect.Method.invoke(Method.java:498)
<2>    at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor$LifecycleElement.invoke(InitDestroyAnnotationBeanPostProcessor.java:389)
<2>    at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor$LifecycleMetadata.invokeInitMethods(InitDestroyAnnotationBeanPostProcessor.java:333)
<2>    at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor.postProcessBeforeInitialization(InitDestroyAnnotationBeanPostProcessor.java:157)
<2>    ... 33 more
<2>Caused by: javax.management.InstanceAlreadyExistsException: quartz:type=QuartzScheduler,name=DefaultQuartzScheduler-harvest-wfs,instance=NON_CLUSTERED
<2>    at com.sun.jmx.mbeanserver.Repository.addMBean(Repository.java:437)
<2>    at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.registerWithRepository(DefaultMBeanServerInterceptor.java:1898)
<2>    at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.registerDynamicMBean(DefaultMBeanServerInterceptor.java:966)
<2>    at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.registerObject(DefaultMBeanServerInterceptor.java:900)
<2>    at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.registerMBean(DefaultMBeanServerInterceptor.java:324)
<2>    at com.sun.jmx.mbeanserver.JmxMBeanServer.registerMBean(JmxMBeanServer.java:522)
<2>    at org.quartz.core.QuartzScheduler.registerJMX(QuartzScheduler.java:343)
<2>    at org.quartz.core.QuartzScheduler.initialize(QuartzScheduler.java:243)
<2>    ... 47 more
<2>
<2>Un ou plusieurs écouteurs n'ont pas pu démarrer, les détails sont dans le fichier de log du conteneur
<2>Erreur de démarrage du contexte [/geonetwork] suite aux erreurs précédentes
```

so a tomcat restart is required each time one wants to update/reload the webapp, quite the big hammer.

**Comment by landryb** [comment]
dunno if related to this upgrade or me testing mapstore2 update, but loading layers in ms2 from gn4 (eg  what was done in georchestra/geonetwork#184 ) doesnt seem to work anymore.

**Comment by landryb** [comment]
from all the requests done when loading ms2 and sending it the layer `PARCELLE` from workspace `psc`:
-`/geoserver/psc/ows?service=WMS&version=1.3.0&request=GetCapabilities&SERVICE=WMS&REQUEST=GetCapabilities` gets a 200
- `/geoserver/psc/ows?service=WMS&version=1.1.1&request=DescribeLayer&layers=PARCELLE` gets a 200
- `/geoserver/psc/gwc/service/wmts?service=WMTS&REQUEST=DescribeDomains&version=1.0.0&layer=PARCELLE&tileMatrixSet=EPSG:4326&expandLimit=10` gets a 400 code as i dont have gwc (and it shouldnt be a requirement)
the last request has this output:
```
400: Thread 750 Unknown layer psc:PARCELLE. Check the logfiles, it may not have loaded properly.
```

**Comment by landryb** [comment]
Fwiw i see zero reason to stick to 4.0.5, only less testing has been done on 4.0.6 but i haven't seen regressions from my previous 4.0.5 testing.

**Comment by landryb** [comment]
i dont think it's a big surprise (nor if we care about it, and probably not a regression from 4.0.5), but it seems CSW searches from mfapp are broken:
- for this payload
```
<?xml version="1.0" encoding="UTF-8"?><csw:GetRecords xmlns:csw="http://www.opengis.net/cat/csw/2.0.2" service="CSW" version="2.0.2" resultType="results" startPosition="1" maxRecords="20" xmlns:gmd="http://www.isotc211.org/2005/gmd"><csw:Query typeNames="csw:Record"><csw:ElementSetName>full</csw:ElementSetName><csw:Constraint version="1.1.0"><ogc:Filter xmlns:ogc="http://www.opengis.net/ogc"><ogc:And><ogc:Or><ogc:PropertyIsEqualTo matchCase="true"><ogc:PropertyName>Type</ogc:PropertyName><ogc:Literal>data</ogc:Literal></ogc:PropertyIsEqualTo><ogc:PropertyIsEqualTo matchCase="true"><ogc:PropertyName>Type</ogc:PropertyName><ogc:Literal>dataset</ogc:Literal></ogc:PropertyIsEqualTo><ogc:PropertyIsEqualTo matchCase="true"><ogc:PropertyName>Type</ogc:PropertyName><ogc:Literal>datasetcollection</ogc:Literal></ogc:PropertyIsEqualTo><ogc:PropertyIsEqualTo matchCase="true"><ogc:PropertyName>Type</ogc:PropertyName><ogc:Literal>series</ogc:Literal></ogc:PropertyIsEqualTo></ogc:Or><ogc:BBOX><gml:Envelope xmlns:gml="http://www.opengis.net/gml"><gml:lowerCorner>-180 -90</gml:lowerCorner><gml:upperCorner>180 90</gml:upperCorner></gml:Envelope></ogc:BBOX><ogc:Or><ogc:Or><ogc:PropertyIsEqualTo matchCase="true"><ogc:PropertyName>Title</ogc:PropertyName><ogc:Literal>avis</ogc:Literal></ogc:PropertyIsEqualTo><ogc:PropertyIsEqualTo matchCase="true"><ogc:PropertyName>AlternateTitle</ogc:PropertyName><ogc:Literal>avis</ogc:Literal></ogc:PropertyIsEqualTo><ogc:PropertyIsEqualTo matchCase="true"><ogc:PropertyName>Identifier</ogc:PropertyName><ogc:Literal>avis</ogc:Literal></ogc:PropertyIsEqualTo><ogc:PropertyIsEqualTo matchCase="true"><ogc:PropertyName>ResourceIdentifier</ogc:PropertyName><ogc:Literal>avis</ogc:Literal></ogc:PropertyIsEqualTo></ogc:Or><ogc:Or><ogc:PropertyIsLike matchCase="false" wildCard="*" singleChar="." escapeChar="!"><ogc:PropertyName>Title</ogc:PropertyName><ogc:Literal>avis*</ogc:Literal></ogc:PropertyIsLike><ogc:PropertyIsLike matchCase="false" wildCard="*" singleChar="." escapeChar="!"><ogc:PropertyName>AlternateTitle</ogc:PropertyName><ogc:Literal>avis*</ogc:Literal></ogc:PropertyIsLike><ogc:PropertyIsLike matchCase="false" wildCard="*" singleChar="." escapeChar="!"><ogc:PropertyName>Abstract</ogc:PropertyName><ogc:Literal>avis*</ogc:Literal></ogc:PropertyIsLike><ogc:PropertyIsLike matchCase="false" wildCard="*" singleChar="." escapeChar="!"><ogc:PropertyName>Subject</ogc:PropertyName><ogc:Literal>avis*</ogc:Literal></ogc:PropertyIsLike><ogc:PropertyIsLike matchCase="false" wildCard="*" singleChar="." escapeChar="!"><ogc:PropertyName>OrganisationName</ogc:PropertyName><ogc:Literal>avis*</ogc:Literal></ogc:PropertyIsLike></ogc:Or></ogc:Or></ogc:And></ogc:Filter></csw:Constraint><ogc:SortBy xmlns:ogc="http://www.opengis.net/ogc"><ogc:SortProperty><ogc:PropertyName>Relevance</ogc:PropertyName><ogc:SortOrder>DESC</ogc:SortOrder></ogc:SortProperty></ogc:SortBy></csw:Query></csw:GetRecords>
```
- we get
```
<?xml version="1.0" encoding="UTF-8"?>
<ows:ExceptionReport xmlns:ows="http://www.opengis.net/ows" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" version="1.2.0" xsi:schemaLocation="http://www.opengis.net/ows http://schemas.opengis.net/ows/1.0.0/owsExceptionReport.xsd">
  <ows:Exception exceptionCode="NoApplicableCode">
    <ows:ExceptionText>java.lang.RuntimeException: com.fasterxml.jackson.core.JsonParseException: Invalid numeric value: Leading zeroes not allowed
 at [Source: (String)"{ "bool": {
            "must": [
              {"bool": {
            "should": [
              {"bool": {
            "should": [
             {
    "wildcard": {
      "OrgForResource": {
        "value": "avis*"
      }
    }
},{
    "wildcard": {
      "tag": {
        "value": "avis*"
      }
    }
},{
    "wildcard": {
      "resourceAbstractObject.default": {
        "value": "avis*"
      }
    }
},{
    "wildcard": {
      "resourceAltTitle": {
        "value": "avis*"
      }
    }
},"[truncated 1442 chars]; line: 64, column: 54]</ows:ExceptionText>
  </ows:Exception>
</ows:ExceptionReport>
```

**Comment by pmauduit** [comment]
Since branching in git is quite free, I allowed myself to create a `georchestra-gn4-4.0.6` branch into `georchestra/geonetwork` (https://github.com/georchestra/geonetwork/tree/georchestra-gn4-4.0.6). this allows us to keep the history from the former branch.

If nobody complains, I'd suggest to update the submodule so that it points to this branch.

**Comment by pmauduit** [comment]
> If nobody complains, I'd suggest to update the submodule so that it points to this branch.

done with 1f1670e4a9f4c61a2bfddb00f40e38cc7f8c6a6b btw ;-)

**Comment by landryb** [comment]
in master \o/
