### ISSUE TITLE
[datafeeder] fails to publish MD against GN 4.0.6

### ISSUE THREAD

**Issue by landryb** [georchestra/georchestra#3630]
Testing datafeeder against GN 4.0.6, fails at the step where the MD should be pushed to GN (the layer has been correctly pushed to geoserver)

```
==> /srv/log/datafeeder.log <==
2022-02-10 10:39:47.985  INFO 1573390 --- [         task-4] o.g.d.s.g.DefaultGeoNetworkClient        : Publishing record ffa2cc2a-dc00-42c9-a296-06766166df84 to GeoNetwork
2022-02-10 10:39:48.011  WARN 1573390 --- [         task-4] o.g.jersey.client.JerseyInvocation       : Entity must not be null for http method PUT.
2022-02-10 10:39:48.071 ERROR 1573390 --- [         task-4] o.g.d.s.g.DefaultGeoNetworkClient        : Error inserting metadata record

org.fao.geonet.client.ApiException: <?xml version="1.0" encoding="UTF-8" standalone="yes"?><apiError><code>runtime_exception</code><message>NullPointerException</message></apiError>
        at org.fao.geonet.client.ApiClient.invokeAPI(ApiClient.java:719) ~[classes!/:na]
        at org.fao.geonet.client.RecordsApi.publishWithHttpInfo(RecordsApi.java:3818) ~[classes!/:na]
        at org.fao.geonet.client.RecordsApi.publish(RecordsApi.java:3776) ~[classes!/:na]
        at org.georchestra.datafeeder.service.geonetwork.DefaultGeoNetworkClient.putXmlRecord(DefaultGeoNetworkClient.java:135) ~[classes!/:na]
        at org.georchestra.datafeeder.service.geonetwork.GeoNetworkRemoteService.publish(GeoNetworkRemoteService.java:120) ~[classes!/:na]
        at org.georchestra.datafeeder.service.publish.impl.GeorchestraMetadataPublicationService.publish(GeorchestraMetadataPublicationService.java:91) ~[classes!/:na]
        at org.georchestra.datafeeder.batch.service.PublishingBatchService.lambda$step3_publishDatasetsMetadataToGeoNetwork$4(PublishingBatchService.java:190) ~[classes!/:na]
        at org.georchestra.datafeeder.batch.service.PublishingBatchService.doOnEachRunningDataset(PublishingBatchService.java:218) ~[classes!/:na]
        at org.georchestra.datafeeder.batch.service.PublishingBatchService.step3_publishDatasetsMetadataToGeoNetwork(PublishingBatchService.java:186) ~[classes!/:na]
        at org.georchestra.datafeeder.batch.service.PublishingBatchService$$FastClassBySpringCGLIB$$23b074cb.invoke(<generated>) ~[classes!/:na]
```

the layer is a simple shp-in-zip and i've specified that the projection was EPSG:2154.

**Comment by pmauduit** [comment]
Testing the DF into a brand new vagrant did not show any error, the only manual step that I made was to load a GEMET thesaurus into the GN admin ui.

**Comment by landryb** [comment]
[ortho_cantal_2020_2154.zip](https://github.com/georchestra/georchestra/files/8078379/ortho_cantal_2020_2154.zip)

i can reproduce the issue with this dataset, but i guess there's something fishy about the whole thing and it has nothing to do with the dataset.. theres' no traceback in the geonetwork log, only in the datafeeder log so its seems the NPE is client-side ?

accesslog on the sec-proxy:
```
10.10.10.10, 10.0.7.1 - - [16/Feb/2022:10:05:10 +0100] POST /datafeeder/upload HTTP/1.1 202 213
10.10.10.10, 10.0.7.1 - - [16/Feb/2022:10:05:11 +0100] GET /datafeeder/upload/0cd0ad59-d06e-443e-94f8-c2ec34eccb83 HTTP/1.1 200 213
10.10.10.10, 10.0.7.1 - - [16/Feb/2022:10:05:11 +0100] GET /datafeeder/upload/0cd0ad59-d06e-443e-94f8-c2ec34eccb83 HTTP/1.1 200 213
10.10.10.10, 10.0.7.1 - - [16/Feb/2022:10:05:12 +0100] GET /datafeeder/upload/0cd0ad59-d06e-443e-94f8-c2ec34eccb83 HTTP/1.1 200 268
10.10.10.10, 10.0.7.1 - - [16/Feb/2022:10:05:12 +0100] GET /datafeeder/upload/0cd0ad59-d06e-443e-94f8-c2ec34eccb83 HTTP/1.1 200 268
10.10.10.10, 10.0.7.1 - - [16/Feb/2022:10:05:12 +0100] GET /datafeeder/upload/0cd0ad59-d06e-443e-94f8-c2ec34eccb83 HTTP/1.1 200 268
10.10.10.10, 10.0.7.1 - - [16/Feb/2022:10:05:13 +0100] GET /datafeeder/upload/0cd0ad59-d06e-443e-94f8-c2ec34eccb83 HTTP/1.1 200 1293
10.10.10.10, 10.0.7.1 - - [16/Feb/2022:10:05:13 +0100] GET /datafeeder/upload/0cd0ad59-d06e-443e-94f8-c2ec34eccb83/publish HTTP/1.1 200 336
10.10.10.10, 10.0.7.1 - - [16/Feb/2022:10:05:13 +0100] GET /datafeeder/upload/0cd0ad59-d06e-443e-94f8-c2ec34eccb83/ortho_cantal_2020_2154/bounds?srs=EPSG%3A3857&srsOverride=EPSG%3A2154 HTTP/1.1 200 957
10.10.10.10, 10.0.7.1 - - [16/Feb/2022:10:05:14 +0100] GET /datafeeder/upload/0cd0ad59-d06e-443e-94f8-c2ec34eccb83/ortho_cantal_2020_2154/sampleFeature?featureIndex=0&encoding=ISO-8859-1&srs=EPSG%3A3857&srsOverride=EPSG%3A2154 HTTP/1.1 200 492
10.10.10.10, 10.0.7.1 - - [16/Feb/2022:10:05:14 +0100] GET /datafeeder/upload/0cd0ad59-d06e-443e-94f8-c2ec34eccb83/ortho_cantal_2020_2154/sampleFeature?featureIndex=0&encoding=UTF-8&srs=EPSG%3A3857&srsOverride=EPSG%3A2154 HTTP/1.1 200 492
10.10.10.10, 10.0.7.1 - - [16/Feb/2022:10:05:23 +0100] GET /datafeeder/upload/0cd0ad59-d06e-443e-94f8-c2ec34eccb83/publish HTTP/1.1 200 336
10.10.10.10, 10.0.7.1 - - [16/Feb/2022:10:05:23 +0100] GET /import/dataFeeder.a94e1a73c38e9ef23ef3.woff HTTP/1.1 200 4312
10.10.10.10, 10.0.7.1 - - [16/Feb/2022:10:05:23 +0100] GET /import/dataFeeder.a94e1a73c38e9ef23ef3.woff HTTP/1.1 200 4312
10.10.10.10, 10.0.7.1 - - [16/Feb/2022:10:05:36 +0100] GET /datafeeder/upload/0cd0ad59-d06e-443e-94f8-c2ec34eccb83/publish HTTP/1.1 200 336
10.10.10.10, 10.0.7.1 - - [16/Feb/2022:10:05:39 +0100] GET /geonetwork/srv/api/registries/vocabularies/search?type=CONTAINS&thesaurus=external.theme.inspire-theme&rows=200&q=*&uri=**&lang=fre HTTP/1.1 200 25558
10.10.10.10, 10.0.7.1 - - [16/Feb/2022:10:05:51 +0100] GET /datafeeder/upload/0cd0ad59-d06e-443e-94f8-c2ec34eccb83/publish HTTP/1.1 200 336
10.10.10.10, 10.0.7.1 - - [16/Feb/2022:10:05:53 +0100] GET /datafeeder/upload/0cd0ad59-d06e-443e-94f8-c2ec34eccb83/publish HTTP/1.1 200 336
10.10.10.10, 10.0.7.1 - - [16/Feb/2022:10:05:59 +0100] GET /datafeeder/upload/0cd0ad59-d06e-443e-94f8-c2ec34eccb83/publish HTTP/1.1 200 336
10.10.10.10, 10.0.7.1 - - [16/Feb/2022:10:06:05 +0100] POST /datafeeder/upload/0cd0ad59-d06e-443e-94f8-c2ec34eccb83/publish HTTP/1.1 202 415
10.10.10.10, 10.0.7.1 - - [16/Feb/2022:10:06:05 +0100] GET /datafeeder/upload/0cd0ad59-d06e-443e-94f8-c2ec34eccb83/publish HTTP/1.1 200 417
10.10.10.10, 10.0.7.1 - - [16/Feb/2022:10:06:05 +0100] GET /datafeeder/upload/0cd0ad59-d06e-443e-94f8-c2ec34eccb83/publish HTTP/1.1 200 458
10.10.10.10, 10.0.7.1 - - [16/Feb/2022:10:06:06 +0100] GET /datafeeder/upload/0cd0ad59-d06e-443e-94f8-c2ec34eccb83/publish HTTP/1.1 200 458
10.10.10.10, 10.0.7.1 - - [16/Feb/2022:10:06:06 +0100] GET /datafeeder/upload/0cd0ad59-d06e-443e-94f8-c2ec34eccb83/publish HTTP/1.1 200 457
10.10.10.10, 10.0.7.1 - - [16/Feb/2022:10:06:07 +0100] GET /datafeeder/upload/0cd0ad59-d06e-443e-94f8-c2ec34eccb83/publish HTTP/1.1 200 460
10.10.10.10, 10.0.7.1 - - [16/Feb/2022:10:06:07 +0100] GET /datafeeder/upload/0cd0ad59-d06e-443e-94f8-c2ec34eccb83/publish HTTP/1.1 200 460
10.10.10.10, 10.0.7.1 - - [16/Feb/2022:10:06:08 +0100] GET /datafeeder/upload/0cd0ad59-d06e-443e-94f8-c2ec34eccb83/publish HTTP/1.1 200 492
10.10.10.10, 10.0.7.1 - - [16/Feb/2022:10:06:08 +0100] GET /datafeeder/upload/0cd0ad59-d06e-443e-94f8-c2ec34eccb83/publish HTTP/1.1 200 492
10.10.10.10, 10.0.7.1 - - [16/Feb/2022:10:06:09 +0100] GET /datafeeder/upload/0cd0ad59-d06e-443e-94f8-c2ec34eccb83/publish HTTP/1.1 200 492
10.10.10.10, 10.0.7.1 - - [16/Feb/2022:10:06:09 +0100] GET /datafeeder/upload/0cd0ad59-d06e-443e-94f8-c2ec34eccb83/publish HTTP/1.1 200 492
10.10.10.10, 10.0.7.1 - - [16/Feb/2022:10:06:10 +0100] GET /datafeeder/upload/0cd0ad59-d06e-443e-94f8-c2ec34eccb83/publish HTTP/1.1 200 492
10.10.10.10, 10.0.7.1 - - [16/Feb/2022:10:06:10 +0100] GET /datafeeder/upload/0cd0ad59-d06e-443e-94f8-c2ec34eccb83/publish HTTP/1.1 200 492
10.10.10.10, 10.0.7.1 - - [16/Feb/2022:10:06:11 +0100] GET /datafeeder/upload/0cd0ad59-d06e-443e-94f8-c2ec34eccb83/publish HTTP/1.1 200 838
10.10.10.10, 10.0.7.1 - - [16/Feb/2022:10:06:11 +0100] GET /datafeeder/upload/0cd0ad59-d06e-443e-94f8-c2ec34eccb83/publish HTTP/1.1 200 1202
```

datafeeder job description, with nothing that i could find as "null" for a PUT..
```
2022-02-16 10:06:05.022  INFO 1573390 --- [         task-9] o.s.b.c.l.support.SimpleJobLauncher      : Job: [SimpleJob: [name=publishJob]] launched with the following parameters: [{uploadId=0cd0ad59-d06e-443e-94f8-c2ec34eccb83, user={"user
name":"testadmin","roles":["ADMINISTRATOR","SUPERUSER","GN_ADMIN","USER","MAPSTORE_ADMIN","CAD_CNIL2","DRIVE","DRIVE_2"],"firstName":"Test","lastName":"ADMIN","organization":{"shortName":"psc","name":"Project Steering Committee","linkage":
"https://www.georchestra.org/","postalAddress":"127 rue georchestra, 73590 Chamblille","category":"Association","description":"Association PSC geOrchestra","notes":"Internal notes"},"email":"admin@craig.fr","postalAddress":"Blah","telephon
eNumber":"tel","title":"title","notes":"Internal CRM notes on testadmin"}}]
```

Looking at the logs i dont see any PUT done, and looking at the code it seems to point at https://github.com/landryb/georchestra/blob/master/datafeeder/src/main/java/org/georchestra/datafeeder/service/geonetwork/DefaultGeoNetworkClient.java#L130

**Comment by landryb** [comment]
same error when trying to run the datafeeder service with adoptopenjdk 8.
```
$/usr/lib/jvm/adoptopenjdk-8-hotspot-amd64/bin/java -version
openjdk version "1.8.0_292"
```
datafeeder comes from georchestra-datafeeder debian package `21.0+202202151707` built from current master branch

**Comment by landryb** [comment]
i've enabled debugging in the gn client, and here's the sequence of calls:
```
2022-02-17 14:15:04.204  INFO 376175 --- [         task-4] o.g.d.s.g.DefaultGeoNetworkClient        : Inserting record 4c8f0214-795c-4850-a511-150e002a1d4b to GeoNetwork, under group psc(102)
2022-02-17 14:15:04.223  INFO 376175 --- [         task-4] o.g.jersey.logging.LoggingFeature        : 2 * Sending client request on thread task-4
2 > PUT http://localhost:8280/geonetwork/srv/api/records?metadataType=METADATA&recursiveSearch=false&assignToCatalog=false&uuidProcessing=NOTHING&group=102&rejectIfInvalid=false&publishToAll=true
2 > Accept: application/json
2 > Content-Type: application/xml
2 > Cookie: XSRF-TOKEN=c9f33266-e242-4198-a18c-b01290dce5f1
2 > sec-org: Datafeeder Test
2 > sec-proxy: true
2 > sec-roles: ROLE_ADMINISTRATOR;ROLE_GN_ADMIN
2 > sec-username: testadmin
2 > User-Agent: Swagger-Codegen/1.0.0/java
2 > X-XSRF-TOKEN: c9f33266-e242-4198-a18c-b01290dce5f1
<?xml version="1.0" encoding="UTF-8"?>
theres the metadata data XML
...
2022-02-17 14:15:04.486  INFO 376175 --- [         task-4] o.g.d.s.g.DefaultGeoNetworkClient        : Publishing record 4c8f0214-795c-4850-a511-150e002a1d4b to GeoNetwork
2022-02-17 14:15:04.513  WARN 376175 --- [         task-4] o.g.jersey.client.JerseyInvocation       : Entity must not be null for http method PUT.
2022-02-17 14:15:04.514  INFO 376175 --- [         task-4] o.g.jersey.logging.LoggingFeature        : 1 * Sending client request on thread task-4
1 > PUT http://localhost:8280/geonetwork/srv/api/records/4c8f0214-795c-4850-a511-150e002a1d4b/publish
1 > Accept: */*
1 > Content-Type: application/json
1 > Cookie: XSRF-TOKEN=c9f33266-e242-4198-a18c-b01290dce5f1
1 > sec-org: Datafeeder Test
1 > sec-proxy: true
1 > sec-roles: ROLE_ADMINISTRATOR;ROLE_GN_ADMIN
1 > sec-username: testadmin
1 > User-Agent: Swagger-Codegen/1.0.0/java
1 > X-XSRF-TOKEN: c9f33266-e242-4198-a18c-b01290dce5f1

2022-02-17 14:15:04.559  INFO 376175 --- [         task-4] o.g.jersey.logging.LoggingFeature        : 1 * Client response received on thread task-4
1 < 400
1 < Connection: close
1 < Content-Security-Policy: frame-ancestors 'self'
1 < Content-Type: application/xml
1 < Date: Thu, 17 Feb 2022 13:15:04 GMT
1 < Set-Cookie: sessionExpiry=1645103704530; Path=/,serverTime=1645103704530; Path=/,JSESSIONID=378A583D7FDDA8EA5A02C0F1699153AF; Path=/geonetwork; HttpOnly
1 < Transfer-Encoding: chunked
1 < X-Frame-Options: SAMEORIGIN
<?xml version="1.0" encoding="UTF-8" standalone="yes"?><apiError><code>runtime_exception</code><message>NullPointerException</message></apiError>

2022-02-17 14:15:04.571 ERROR 376175 --- [         task-4] o.g.d.s.g.DefaultGeoNetworkClient        : Error inserting metadata record

org.fao.geonet.client.ApiException: <?xml version="1.0" encoding="UTF-8" standalone="yes"?><apiError><code>runtime_exception</code><message>NullPointerException</message></apiError>
```
so now i know that it's not the client-side which is blowing up, but rather GN4 (or its tomcat ?) returning a 400 code ?

now that i look better, indeed the tomcat hosting GN4 receives the request in its accesslog:
```
- - - [17/Feb/2022:14:15:04 +0100] PUT /geonetwork/srv/api/records/4c8f0214-795c-4850-a511-150e002a1d4b/publish HTTP/1.1 400 156
```
but nothing specific in the GN4 log..

**Comment by landryb** [comment]
looking in the gn4 database, all the XML md records pushed by datafeeder are present in the DB and in the editor admin console, so the md exists, it's just that publishing them automagically from df fails.

**Comment by landryb** [comment]
via the gn4 swagger interface, trying the [​/records​/{metadataUuid}​/publish] API also fails with a 400 return code.
```
{
  "message": "NullPointerException",
  "code": "runtime_exception",
  "description": null
}
```
so... either a gn4 genuine bug (regression from 4.0.5 which iirc worked), or something wrong in my config.

**Comment by landryb** [comment]
can reproduce in gn4 itself, on a metadata, 'gérér la fiche->publier' triggers a 400 code too
```
![image](https://user-images.githubusercontent.com/3421760/154495370-7b12ae14-8648-4c28-bdfd-314ca6c36390.png)
```

**Comment by landryb** [comment]
the `runtime_exception` message is returned by https://github.com/georchestra/geonetwork/blob/georchestra-gn4-4.0.6/services/src/main/java/org/fao/geonet/api/GlobalExceptionController.java#L167 but now to figure out where the failure comes from..

**Comment by landryb** [comment]
seems totally related to geonetwork/core-geonetwork#6141 - testing a backport of geonetwork/core-geonetwork@8de0dafa - and can apparently only be seen if `metadata/workflow/enable` is true in settings table.
