### ISSUE TITLE
extractorapp - issues with javax.activation package after moving to java11

### ISSUE THREAD

**Issue by pmauduit** [georchestra/georchestra#3704]
```
java.lang.NoClassDefFoundError: javax/activation/DataSource
	at org.georchestra.extractorapp.ws.Email.sendMsg(Email.java:87)
	at org.georchestra.extractorapp.ws.EmailFactoryDefault$1.sendDone(EmailFactoryDefault.java:76)
	at org.georchestra.extractorapp.ws.extractor.task.ExtractionTask.run(ExtractionTask.java:184)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.lang.ClassNotFoundException: javax.activation.DataSource
	at java.base/java.net.URLClassLoader.findClass(Unknown Source)
	at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
	at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
	... 8 more
```

Since a `DataSource` class is present in the classpath, I suspect that a wrong version of javax.activation is being used here.

**Comment by pmauduit** [comment]
I'd expect to work normally with tomcat, and should be the exact same issue as this one: https://github.com/georchestra/georchestra/pull/3693/files

One quickfix for jetty9 users: remove the provided mail subdirectory, as done in the previous PR.

**Comment by pmauduit** [comment]
I manually fixed the `georchestra/extractorapp:22.0.0` docker image.
