### ISSUE TITLE
geonetwork - DCAT2 metadata makes the CSW GetRecords fail

### ISSUE THREAD

**Issue by pmauduit** [georchestra/georchestra#3720]
There is an issue with the XSL transformation when doing a GetRecords CSW request and the catalogue needs to return some DCAT2 metadata:

```
Error at xsl:apply-templates on line 35 column 62 of csw-full.xsl:
  XPST0081: XPath syntax error at char 11 on line 35 in {dct:spatial}:
    Undeclared namespace prefix {dct}
Error at xsl:template on line 48 column 49 of csw-full.xsl:
  XPST0081: XSLT Pattern syntax error at char 11 on line 48 in {dct:spatial}:
    Undeclared namespace prefix {dct}
2022-04-11 12:45:53,817 ERROR [jeeves.webapp.csw] - Error occured while transforming metadata with id '207' using 'csw-full.xsl'.
2022-04-11 12:45:53,818 ERROR [jeeves.webapp.csw] -   (C) StackTrace:
javax.xml.transform.TransformerConfigurationException: Failed to compile stylesheet. 2 errors detected.
	at net.sf.saxon.PreparedStylesheet.prepare(PreparedStylesheet.java:176)
	at net.sf.saxon.TransformerFactoryImpl.newTemplates(TransformerFactoryImpl.java:139)
	at de.fzi.dbs.xml.transform.CachingTransformerFactory.newTransformer(CachingTransformerFactory.java:120)
	at de.fzi.dbs.xml.transform.CachingTransformerFactory.newTransformer(CachingTransformerFactory.java:79)
	at org.fao.geonet.utils.Xml.transform(Xml.java:508)
[...]
```

I haven't checked if this has been already encountered / reported upstream.

**Comment by pmauduit** [comment]
dupe of #3841
