### ISSUE TITLE
[geonetwork] ldap<->gn4 sync broken with large directories/many users/orgs using default sync settings

### ISSUE THREAD

**Issue by landryb** [georchestra/georchestra#3779]
trying to upgrade our instance to 22.0, which includes gn4 and the new "integration" mechanism with ldap by @groldan - sadly, it doesn't work at all with large directories (1k orgs, 1.5k users), i guess because it needs some paging mechanism or larger timeouts or something.

once all the db migrations more or less managed to pass, GN4 tries to sync the orgs & users from the console, which apparently takes too much time:
```
2022-07-29 15:51:08,619 INFO  [org.geonetwork.security.external.integration] - No organizations were deleted.
2022-07-29 15:51:08,623 INFO  [org.geonetwork.security.external.integration] - Reconciling existing GN group AFB with canonical group (id: 6a9655b1-94c2-464a-b1c4-d15c6d67b8c2)
...
2022-07-29 15:51:15,651 INFO  [org.geonetwork.security.external.integration] - Reconciling existing GN group COM_ST_JULIEN_MONTDENIS with canonical group (id: 0d50fc31-d6cf-4cdf-9db2-ba55180393df)
2022-07-29 15:51:21,739 WARN  [org.geonetwork.security.external.integration] - Synchronization failed, retrying in 10 SECONDS.
org.springframework.web.client.ResourceAccessException: I/O error on GET request for "http://localhost:9480/console/internal/users": Read timed out; nested exception is java.net.SocketTimeoutException: Read timed out
        at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:748)
        at org.springframework.web.client.RestTemplate.execute(RestTemplate.java:674)
        at org.springframework.web.client.RestTemplate.getForEntity(RestTemplate.java:342)
        at org.georchestra.security.client.console.RestClient.get(RestClient.java:40)
        at org.georchestra.security.client.console.RestClient.getAll(RestClient.java:55)
        at org.georchestra.security.client.console.GeorchestraConsoleUsersApiImpl.findAll(GeorchestraConsoleUsersApiImpl.java:45)
        at org.georchestra.geonetwork.security.integration.GeorchestraAccountsRepository.findAllUsers(GeorchestraAccountsRepository.java:54)
        at org.geonetwork.security.external.integration.UserSynchronizer.findCanonicalUsers(UserSynchronizer.java:78)
```
etc etc. Problem is, since it fails, it apparently tries to restart everything from scratch every 10s, so never finishes the sync, and hammers the console API, and gobbles cpu time, and fills the logs....
```
468M    /srv/log/tomcat/geonetwork.log
```

i'll fiddle with the `geonetwork.scheduled` settings in `geonetwork.properties` but my guess is that the defaults are overly aggressive for large platforms.

manually fetching (well, waiting for the console to generate it) the users json takes 20s here.

```
$curl -o /tmp/users.json http://localhost:9480/console/internal/users
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  632k    0  632k    0     0  33135      0 --:--:--  0:00:19 --:--:--  189k
```

doing the same manual query for orgs is immediate, and from my understanding of looking at the ldap server logs, it's super slow for users because the console code which generates the json hammers the ldap doing membership queries for each users.

@groldan ? @fvanderbiest ?

**Comment by landryb** [comment]
after going through the bazillions of indirections and design patterns in the code, i've found out that the default read timeout was 6s and was hardcoded in https://github.com/georchestra/georchestra/blob/master/security-proxy-spring-integration/src/main/java/org/georchestra/security/client/console/RestClient.java#L28

**Comment by landryb** [comment]
i see two things to fix:
- raise the timeout in the code to 60s (or 120s) like most http clients/reverse proxies use by default (or at least make it configurable)
- change the defaults in the datadir to run the sync every 10mn (i know that i will set it up every hour) - it feels insane to me to hammer the ldap server with thousands of requests every 10s. nextcloud suffers from similar issues, but at least they do some paging....

**Comment by landryb** [comment]
once i've locally bumped the read timeout to 60s in the code, rebuilt with `mvn clean install -f security-proxy-spring-integration/pom.xml` & deployed `security-proxy-spring-integration-22.0.3-SNAPSHOT.jar` locally
the sync blows on duplicated keys in the email table..
```
Caused by: java.sql.BatchUpdateException: Batch entry 0 insert into email (User_id, email) values (9, 'xxx@xxx.xx') was aborted: ERROR: duplicate key value violates unique constraint "email_pkey"
  Détail : Key (user_id)=(9) already exists.  Call getNextException to see other errors in the batch.
```
after having dropped some bogus entries from the email table, the initial user sync actually runs in 75s here.

i'd have another suggestion: moving the 'Reconciliing existing' msgs for users & orgs to DEBUG level, since they're pretty verbose especially if shown at each sync - and for the next syncs one might want to only see the other msgs (adding users, new orgs, setting profiles...)

**Comment by landryb** [comment]
subsequent noop syncs (eg nothing changed) takes 6s for ~1000 orgs & 20s for ~1500 orgs, most of this time being spent by the console hammering the ldap server.

**Comment by landryb** [comment]
#3780 has been merged (thanks @fvanderbiest !), but ideally that timeout definitely has to be configurable without modifying the code...
