### ISSUE TITLE
[geonetwork] ldap<->gn4 sync broken: fails to update a user that couldnt be removed ?

### ISSUE THREAD

**Issue by landryb** [georchestra/georchestra#3831]
some field isnt wide enough ? spotted when a user was supposed to be deleted but couldnt. Anonymised the names but kept the string lenght.

```
2022-10-14 14:33:00,177 WARN  [org.geonetwork.security.external.integration] - Cannot delete user 'xxxxxxxx' who is owner of 2 metadata record(s).

...
2022-10-14 14:33:00,343 ERROR [org.geonetwork.security.external.integration] - Error synchronizing users
org.springframework.dao.DataIntegrityViolationException: could not execute batch; SQL [update Users set isenabled=?, kind=?, lastLoginDate=?, name=?, organisation=?, profile=?, authtype=?, nodeId=?, password=?, security=?, surname=?, username=? where id=?]; nested exception is org.hibernate.exception.DataException: could not execute batch
        at org.springframework.orm.jpa.vendor.HibernateJpaDialect.convertHibernateAccessException(HibernateJpaDialect.java:302)
        at org.springframework.orm.jpa.vendor.HibernateJpaDialect.translateExceptionIfPossible(HibernateJpaDialect.java:255)
        at org.springframework.orm.jpa.AbstractEntityManagerFactoryBean.translateExceptionIfPossible(AbstractEntityManagerFactoryBean.java:528)

...
Caused by: java.sql.BatchUpdateException: Batch entry 0 update Users set isenabled='y', kind='Chargée du référ', lastLoginDate='2022-05-04T14:41:05', name='deleted_5bb06470-fa56-48c8-8d47-e5f66a20a4b1', organisation='GRENOBLE_ALPES_METRO', profile=3, authtype=NULL, nodeId='srv', password='', security='', surname='xxxx xxxxxx xxxxxx', username='xxxxxxxx.xxxx-xxxxxx-xxxxxx' where id=185363066 was aborted: ERROR: value too long for type character varying(32)  Call getNextException to see other errors in the batch.
...

Caused by: org.postgresql.util.PSQLException: ERROR: value too long for type character varying(32)
```

@fvanderbiest @groldan ?

my take is on the `name` field which is 32 chars, while the code tries to set it to `deleted_5bb06470-fa56-48c8-8d47-e5f66a20a4b1` which is 45 chars.

**Comment by landryb** [comment]
the end result is that the sync blows now at each iteration. pretty bad..

**Comment by landryb** [comment]
the offending code is in https://github.com/georchestra/geonetwork/blob/georchestra-gn4-4.0.6/georchestra-integration/externalized-accounts/src/main/java/org/geonetwork/security/external/integration/UserSynchronizer.java#L230

**Comment by landryb** [comment]
on my instance where the database has been created ages ages ago, name is varchar 32:
```
                                 Table "public.users"
    Column     |          Type          | Collation | Nullable |        Default
---------------+------------------------+-----------+----------+-----------------------
 id            | integer                |           | not null |
 username      | character varying(256) |           | not null |
 password      | character varying(120) |           | not null |
 surname       | character varying(32)  |           |          |
 name          | character varying(32)  |           |          |
 profile       | integer                |           | not null |
 organisation  | character varying(128) |           |          |
 kind          | character varying(16)  |           |          |
 security      | character varying(128) |           |          | ''::character varying
 authtype      | character varying(32)  |           |          |
 lastlogindate | character varying(255) |           |          |
 nodeid        | character varying(255) |           |          |
 isenabled     | character(1)           |           | not null | 'y'::bpchar
```
i havent found in the new code what sets the field width, but it's definitely not 255.

Anyway, i ended up manually removing the 2 metadatas from the database (removing them from the UI didnt remove them from the DB) so that the "offending" user could be removed by GN4, and then the reconciliation went ahead.

Still a pretty bad issue.

**Comment by landryb** [comment]
on another GN instance that was iirc initially created with geonetwork 3.8 i have this for the users table:
```
                          Table "geonetwork.users"
    Column     |          Type          | Collation | Nullable |   Default   
---------------+------------------------+-----------+----------+-------------
 id            | integer                |           | not null | 
 isenabled     | character(1)           |           | not null | 'y'::bpchar
 kind          | character varying(16)  |           |          | 
 lastlogindate | character varying(255) |           |          | 
 name          | character varying(255) |           |          | 
 organisation  | character varying(255) |           |          | 
 profile       | integer                |           | not null | 
 authtype      | character varying(32)  |           |          | 
 nodeid        | character varying(255) |           |          | 
 password      | character varying(120) |           | not null | 
 security      | character varying(128) |           |          | 
 surname       | character varying(255) |           |          | 
 username      | character varying(255) |           | not null | 
```

again, it shows that geonetwork upgrades are ... still a mess :)

**Comment by landryb** [comment]
i'll close that one, put it on the general "geonetwork upgrades are somewhat suboptimal" issue bucket...
