### ISSUE TITLE
cas - upgrade version to 6.6

### ISSUE THREAD

**Issue by pmauduit** [georchestra/georchestra#3838]
At the time of the migration to CAS 6, the most recent version was 6.3.7. As this one is no longer supported, we could now migrate to CAS 6.6.

**Comment by pmauduit** [comment]
buildbot is broken because it still relies on Java11 instead of 17.

**Comment by pmauduit** [comment]
> buildbot is broken because it still relies on Java11 instead of 17.

fixed



> There is also a missing configuration in the ansible playbook to reflect changes related to the version bump.

currently trying in the vagrant generated from the ansible playbook.

**Comment by pmauduit** [comment]
ansible playbook is running fine / no error, but CAS refuses to bootstrap itself into the proxycas tomcat instance:

```
<2>Error deploying web application archive [/srv/tomcat/proxycas/webapps/cas.war]
<2>java.lang.IllegalStateException: Error starting child
<2>    at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:602)
<2>    at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:571)
[...]
<2>Caused by: org.apache.catalina.LifecycleException: Failed to start component [StandardEngine[Catalina].StandardHost[localhost].StandardContext[/cas]]
<2>    at org.apache.catalina.util.LifecycleBase.handleSubClassException(LifecycleBase.java:419)
<2>    at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:186)
<2>    at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:599)
<2>    ... 37 more
<2>Caused by: java.lang.NoSuchMethodError: 'java.lang.ClassLoader[] org.apache.logging.log4j.util.LoaderUtil.getClassLoaders()'
```

It looks like there are several log4j versions provided in the webapp:

```
root@bookworm:/srv/tomcat/proxycas/webapps/cas/WEB-INF/lib# ls *log4j*
log4j-api-2.17.0.jar  log4j-core-2.17.0.jar  log4j-jcl-2.18.0.jar  log4j-layout-template-json-2.18.0.jar  log4j-web-2.18.0.jar	    spring-boot-starter-log4j2-2.7.3.jar
log4j-api-2.18.0.jar  log4j-core-2.18.0.jar  log4j-jul-2.18.0.jar  log4j-slf4j-impl-2.18.0.jar		  sentry-log4j2-6.10.0.jar
```

removing the 2.17.0 version allows to get further. CAS complains about not being able to write into /var/log/, but it looks like we could just adapt the log4j2.xml's basedir: https://github.com/georchestra/datadir/blob/master/cas/config/log4j2.xml#L5

**Comment by pmauduit** [comment]
Checking dependencies, it looks like the log4j in v2.17.0 is a dependency from sentry-log4j2. We could upgrade to a newer version of sentry-log4j2, but there are no version making use of exactly log4j 2.18.0, v6.18.0 depends on log4j 2.20.0, former one still on 2.17.0.

It should be safe to exclude the dependency to log4j2, at least to be able to run CAS, and hope v2.18.0 is compatible with sentry-log4j2.

**Comment by pmauduit** [comment]
Upgraded CAS should now work in both docker & ansible, closing.
