### ISSUE TITLE
gs - following security updates (geor < 20.1.8 / < 22.0.6), DBCP-based JNDI resources can make GS fail to function

### ISSUE THREAD

**Issue by pmauduit** [georchestra/georchestra#3905]
If you are using apache DBCP to define JNDI resources, as the following `jetty-env.xml` example:

```

<?xml version="1.0"?>
<!DOCTYPE Configure PUBLIC "-//Jetty//Configure//EN" "http://www.eclipse.org/jetty/configure.dtd">
<Configure class="org.eclipse.jetty.webapp.WebAppContext">

   <New id="cadastre" class="org.eclipse.jetty.plus.jndi.Resource">
     <Arg>jdbc/resource</Arg>
     <Arg>
       <New class="org.apache.commons.dbcp.BasicDataSource">
         <Set name="driverClassName">org.postgresql.Driver</Set>
         <Set name="username">user</Set>
         <Set name="password">password</Set>
         <Set name="url">jdbc:postgres://host/db</Set>
         <Set name="validationQuery">SELECT 1</Set>
         <Set name="maxWait">10000</Set>
         <Set name="maxActive">20</Set>
         <Set name="maxIdle">2</Set>
       </New>
     </Arg>
   </New>
</Configure>
```

you can end up with the following errors in geoserver logs, during webapp bootstrap:

```
Caused by: java.lang.RuntimeException: Could not unwrap connection. Is the DBCP pool configured to allow access to underlying connections?
    at org.geotools.data.jdbc.datasource.DBCPUnWrapper.unwrap(DBCPUnWrapper.java:41)
    at org.geotools.jdbc.SQLDialect.unwrapConnection(SQLDialect.java:1427)
    at org.geotools.data.postgis.PostGISDialect.checkStandardConformingStrings(PostGISDialect.java:1514)

```
Then when requesting a GetCapabilities:

```
java.io.IOException
    at org.geoserver.catalog.ResourcePool.getDataStore(ResourcePool.java:665)
    at org.geoserver.catalog.ResourcePool.getCacheableFeatureType(ResourcePool.java:952)
    at org.geoserver.catalog.ResourcePool.tryGetFeatureType(ResourcePool.java:937)
    at org.geoserver.catalog.ResourcePool.getFeatureType(ResourcePool.java:929)
    at org.geoserver.catalog.ResourcePool.getFeatureType(ResourcePool.java:914)
    at org.geoserver.catalog.ResourcePool.loadAttributes(ResourcePool.java:800)
    at org.geoserver.catalog.ResourcePool.getAttributes(ResourcePool.java:775)
    at org.geoserver.catalog.impl.FeatureTypeInfoImpl.attributes(FeatureTypeInfoImpl.java:119)
    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.base/java.lang.reflect.Method.invoke(Unknown Source)
    at org.geoserver.catalog.impl.ModificationProxy.invoke(ModificationProxy.java:127)
    at com.sun.proxy.$Proxy41.attributes(Unknown Source)
[...]
 Caused by: java.lang.RuntimeException: Unable to obtain connection: Cannot get a connection, pool error Timeout waiting for idle object
    at org.geotools.jdbc.JDBCDataStore.createConnection(JDBCDataStore.java:2143)
    at org.geotools.jdbc.JDBCDataStore.getConnection(JDBCDataStore.java:2085)
    at org.geotools.data.postgis.PostgisNGDataStoreFactory.createDataStoreInternal(PostgisNGDataStoreFactory.java:261)
    at org.geotools.jdbc.JDBCJNDIDataStoreFactory.createDataStoreInternal(JDBCJNDIDataStoreFactory.java:167)
    at org.geotools.jdbc.JDBCDataStoreFactory.createDataStore(JDBCDataStoreFactory.java:388)
    at org.geotools.jdbc.JDBCDataStoreFactory.createDataStore(JDBCDataStoreFactory.java:48)
    at org.vfny.geoserver.util.DataStoreUtils.getDataAccess(DataStoreUtils.java:65)
    at org.geoserver.catalog.ResourcePool.getDataStore(ResourcePool.java:624)
    ... 163 more
Caused by: org.apache.commons.dbcp.SQLNestedException: Cannot get a connection, pool error Timeout waiting for idle object
    at org.apache.commons.dbcp.PoolingDataSource.getConnection(PoolingDataSource.java:114)
    at org.apache.commons.dbcp.BasicDataSource.getConnection(BasicDataSource.java:1044)
    at org.geotools.jdbc.JDBCDataStore.createConnection(JDBCDataStore.java:2127)
    ... 170 more
Caused by: java.util.NoSuchElementException: Timeout waiting for idle object
    at org.apache.commons.pool.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:1134)
    at org.apache.commons.dbcp.PoolingDataSource.getConnection(PoolingDataSource.java:106)
    ... 172 more
```

One workaround is to rewrite your JNDI definitions to avoid using DBCP ; the postgresql JDBC driver provides a SimpleDataSource which could be used instead:

```
<?xml version="1.0"?>
<!DOCTYPE Configure PUBLIC "-//Jetty//Configure//EN" "http://www.eclipse.org/jetty/configure.dtd">
<Configure class="org.eclipse.jetty.webapp.WebAppContext">
   <New id="ds_geoserver" class="org.eclipse.jetty.plus.jndi.Resource">
     <Arg>jdbc/datafeeder</Arg>
     <Arg>
         <New class="org.postgresql.ds.PGSimpleDataSource">
             <Set name="serverName">hostname</Set>
            <Set name="databaseName">dbname</Set>
            <Set name="user">user</Set>
            <Set name="password">password</Set>
        </New>
     </Arg>
   </New>
</Configure> 
```

**Comment by pmauduit** [comment]
should be fixed by https://github.com/georchestra/georchestra/commit/2c88b42b7f18444ee0745bee7c230baffbb6b698

**Comment by fvanderbiest** [comment]
What do GeoServer developers say about this issue ? 
How can we keep connection pools defined at the app server level ?

**Comment by pmauduit** [comment]
Also encountered with a compilation from the 20.1.x branch, the fact that the georchestra root pom is still linked to a spring boot module as parent will transitively give bad versions, and this can lead to bootstrap issues with geoserver. observed with sqlite-jdbc (3.15.1 vs 3.34.0).

If you get this kind of stacktrace:

```
        Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'rawCatalog' defined in URL [jar:file:/var/lib/tomcat9-instance1/webapps/geoserver/WEB-INF/lib/gs-main-2.18.7-georchestra.jar!/applicationContext.xml]: Initialization of bean failed; nested exception is java.lang.NoSuchMethodError: org.sqlite.Function.create(Ljava/sql/Connection;Ljava/lang/String;Lorg/sqlite/Function;II)V
                at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:602)
                at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:516)
                at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:324)
                at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234)
                at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:322)
                at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:202)
                at org.springframework.beans.factory.support.BeanDefinitionValueResolver.resolveReference(BeanDefinitionValueResolver.java:330)
                ... 95 more
        Caused by: java.lang.NoSuchMethodError: org.sqlite.Function.create(Ljava/sql/Connection;Ljava/lang/String;Lorg/sqlite/Function;II)V
```

Then you might need to update the sqlite-jdbc jar in the classpath. This is pretty specific to the geOrchestra integration, and should not appear in most recent branches (22.0.x, master) because the geoserver/pom.xml is no more a child from the georchestra root pom, to avoid this specific issue.

**Comment by pmauduit** [comment]
> One workaround is to rewrite your JNDI definitions to avoid using DBCP

Another one, if one want to keep with DBCP, is to also set the following parameter:

```
accessToUnderlyingConnectionAllowed = true
```
e.g.:

```
<?xml version="1.0"?>
<!DOCTYPE Configure PUBLIC "-//Jetty//Configure//EN" "http://www.eclipse.org/jetty/configure.dtd">
<Configure class="org.eclipse.jetty.webapp.WebAppContext">

   <New id="cadastre" class="org.eclipse.jetty.plus.jndi.Resource">
     <Arg>jdbc/resource</Arg>
     <Arg>
       <New class="org.apache.commons.dbcp.BasicDataSource">
         <Set name="driverClassName">org.postgresql.Driver</Set>
         <Set name="username">user</Set>
         <Set name="password">password</Set>
         <Set name="url">jdbc:postgres://host/db</Set>
         <Set name="validationQuery">SELECT 1</Set>
         <Set name="maxWait">10000</Set>
         <Set name="maxActive">20</Set>
         <Set name="maxIdle">2</Set>
         <Set name="accessToUnderlyingConnectionAllowed">true</Set>
       </New>
     </Arg>
   </New>
</Configure>
```

See https://commons.apache.org/proper/commons-dbcp/configuration.html

**Comment by pmauduit** [comment]
We have some workarounds, closing.
