### ISSUE TITLE
[ CONSOLE ] RGPD en erreur ( cas d'installation particulier )

### ISSUE THREAD

**Issue by pierrejego** [georchestra/georchestra#4168]
Si la base de données geonetwork n'est pas un schéma dans la base de données georchestra nous avons une erreur lorsque l'on souhaite télécharger les données : 

java.util.concurrent.CompletionException: java.lang.IllegalStateException: org.georchestra.ds.DataServiceException: org.postgresql.util.PSQLException: ERREUR: la relation « geonetwork.metadata » n'existe pas
  Position: 75
	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:314)
	at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:319)
	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1739)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.lang.IllegalStateException: org.georchestra.ds.DataServiceException: org.postgresql.util.PSQLException: ERREUR: la relation « geonetwork.metadata » n'existe pas
  Position: 75
	at org.georchestra.console.ds.AccountGDPRDaoImpl.visitMetadataRecords(AccountGDPRDaoImpl.java:178)
	at org.georchestra.console.ws.backoffice.users.GDPRAccountWorker.lambda$buildUserDataBundle$0(GDPRAccountWorker.java:207)
	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1736)
	... 1 more
Caused by: org.georchestra.ds.DataServiceException: org.postgresql.util.PSQLException: ERREUR: la relation « geonetwork.metadata » n'existe pas
  Position: 75
	at org.georchestra.console.ds.AccountGDPRDaoImpl.visitRecords(AccountGDPRDaoImpl.java:206)
	at org.georchestra.console.ds.AccountGDPRDaoImpl.visitMetadataRecords(AccountGDPRDaoImpl.java:174)
	... 3 more
Caused by: org.postgresql.util.PSQLException: ERREUR: la relation « geonetwork.metadata » n'existe pas
  Position: 75
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2676)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2366)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:356)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:496)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:413)
	at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:190)
	at org.postgresql.jdbc.PgPreparedStatement.executeQuery(PgPreparedStatement.java:134)
	at com.mchange.v2.c3p0.impl.NewProxyPreparedStatement.executeQuery(NewProxyPreparedStatement.java:1471)
	at org.georchestra.console.ds.AccountGDPRDaoImpl.visitRecords(AccountGDPRDaoImpl.java:195)
	... 4 more

Pour moi, cela vient du fait que le schéma est mis en dur dans le code et qu'il considère que la base de données est la même 
 
https://github.com/georchestra/georchestra/blob/5e9f83f444386b3f3766358910943a4d6d17e139/console/src/main/java/org/georchestra/console/ds/AccountGDPRDaoImpl.java#L72C67-L72C77

Mais je me trompe peut être.

Quel serait la solution quand la base de données georchestra et geonetwork ne sont pas les mêmes ?  Y a t'il un alternative sans modification du code ?

**Comment by fphg** [comment]
effectivement, il n'y a pas de raison fondamentale à ce que la base geonetwork est à un endroit particulier ; ce peut être au contraire une bonne pratique de la stocker à part.

**Comment by fvanderbiest** [comment]
En effet, le code considère que GeoNetwork est dans un schéma de la base geOrchestra.
PR welcome :-)
