### ISSUE TITLE
console - Organization a mandatory field ?

### ISSUE THREAD

**Issue by fvanderbiest** [georchestra/georchestra#4174]
Even though https://github.com/georchestra/datadir/blob/37e0bcb0be2b9b3b8d372f2939e010b393f20f99/console/console.properties#L142-L145 says that org & orgType are mandatory by default, the console does not require an Org to be filled in forms, eg 
![image](https://github.com/georchestra/georchestra/assets/265319/b2a2de26-a9dc-4bd0-aa52-3d841b30d668)

We should assess the possibility to make the organization a truely optional field or not.
If it's not possible, then it should be clear it's not possible to have users without organizations.

Side note: it has been witnessed that accounts without orgs do not pass the gateway (with error messages like these:
```
2024-01-24 10:45:57.558 ERROR 1 --- [     parallel-1] a.w.r.e.AbstractErrorWebExceptionHandler : [fd495102-89360]  500 Server Error for HTTP GET "/geoserver/rest"

java.lang.NullPointerException: null
	at java.base/java.util.concurrent.ConcurrentHashMap.putVal(Unknown Source) ~[na:na]
	Suppressed: reactor.core.publisher.FluxOnAssembly$OnAssemblyException: 
Error has been observed at the following site(s):
	*__checkpoint ? org.springframework.security.web.server.authentication.AuthenticationWebFilter [DefaultWebFilterChain]
	*__checkpoint ? org.springframework.cloud.gateway.filter.WeightCalculatorWebFilter [DefaultWebFilterChain]
	*__checkpoint ? org.georchestra.gateway.security.preauth.PreauthGatewaySecurityCustomizer$RemovePreauthHeadersWebFilter [DefaultWebFilterChain]
	*__checkpoint ? org.springframework.security.web.server.authorization.AuthorizationWebFilter [DefaultWebFilterChain]
	*__checkpoint ? org.springframework.security.web.server.authorization.ExceptionTranslationWebFilter [DefaultWebFilterChain]
	*__checkpoint ? org.springframework.security.web.server.authentication.logout.LogoutWebFilter [DefaultWebFilterChain]
	*__checkpoint ? org.springframework.security.web.server.savedrequest.ServerRequestCacheWebFilter [DefaultWebFilterChain]
	*__checkpoint ? org.springframework.security.web.server.context.SecurityContextServerWebExchangeWebFilter [DefaultWebFilterChain]
	*__checkpoint ? org.springframework.security.web.server.authentication.AuthenticationWebFilter [DefaultWebFilterChain]
	*__checkpoint ? org.springframework.security.web.server.authentication.AuthenticationWebFilter [DefaultWebFilterChain]
	*__checkpoint ? org.springframework.security.web.server.context.ReactorContextWebFilter [DefaultWebFilterChain]
	*__checkpoint ? org.springframework.security.web.server.header.HttpHeaderWriterWebFilter [DefaultWebFilterChain]
	*__checkpoint ? org.springframework.security.web.server.authentication.AuthenticationWebFilter [DefaultWebFilterChain]
	*__checkpoint ? org.springframework.security.config.web.server.ServerHttpSecurity$ServerWebExchangeReactorContextWebFilter [DefaultWebFilterChain]
	*__checkpoint ? org.springframework.security.web.server.WebFilterChainProxy [DefaultWebFilterChain]
	*__checkpoint ? org.springframework.boot.actuate.metrics.web.reactive.server.MetricsWebFilter [DefaultWebFilterChain]
	*__checkpoint ? HTTP GET "/geoserver/rest" [ExceptionHandlingWebHandler]
Original Stack Trace:
		at java.base/java.util.concurrent.ConcurrentHashMap.putVal(Unknown Source) ~[na:na]
		at java.base/java.util.concurrent.ConcurrentHashMap.put(Unknown Source) ~[na:na]
		at org.georchestra.gateway.model.GeorchestraOrganizations.store(GeorchestraOrganizations.java:36) ~[classes/:23.1-SNAPSHOT]
		at org.georchestra.gateway.security.ResolveGeorchestraUserGlobalFilter.lambda$filter$1(ResolveGeorchestraUserGlobalFilter.java:87) ~[classes/:23.1-SNAPSHOT]
		at reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.onNext(FluxMapFuseable.java:113) ~[reactor-core-3.4.29.jar:3.4.29]
```

**Comment by fvanderbiest** [comment]
When using the datafeeder with its default parameters, users MUST have a valid organization.
The organization info is indeed used to create the db schema + geoserver workspace.
