### ISSUE TITLE
geowebcache (integrated): failing to seed some raster data

### ISSUE THREAD

**Issue by jeanpommier** [georchestra/georchestra#4195]
Hi,
When trying to seed a raster dataset in web mercator grid, the GWC integrated in GeoServer fails with the following logs:
```
georchestra-geoserver 21 Feb 09:03:04 INFO   [geoserver.flow] - releasing flow controllers for [WMS 1.1.1 GetMap]
georchestra-geoserver 21 Feb 09:03:04 INFO   [geoserver.flow] - Request completed, running requests: 1, blocked requests: 0 
georchestra-geoserver 21 Feb 09:03:04 ERROR  [seed.MTSeeder] - Problem communicating with GeoServer
georchestra-geoserver org.geowebcache.GeoWebCacheException: Problem communicating with GeoServer
georchestra-geoserver     at org.geoserver.gwc.layer.GeoServerTileLayer.getMetatilingReponse(GeoServerTileLayer.java:621)
georchestra-geoserver     at org.geoserver.gwc.layer.GeoServerTileLayer.seedTile(GeoServerTileLayer.java:865)
georchestra-geoserver     at org.geowebcache.seed.SeedTask.doActionInternal(SeedTask.java:141)  
georchestra-geoserver     at org.geowebcache.seed.GWCTask.doAction(GWCTask.java:78)             
georchestra-geoserver     at org.geowebcache.seed.MTSeeder.call(MTSeeder.java:34)               
georchestra-geoserver     at org.geowebcache.seed.MTSeeder.call(MTSeeder.java:23)               
georchestra-geoserver     at org.geoserver.gwc.seed.SeederThreadLocalTransferExecutor.lambda$submit$1(SeederThreadLocalTransferExecutor.java:53)
georchestra-geoserver     at java.base/java.util.concurrent.FutureTask.run(Unknown Source)      
georchestra-geoserver     at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
georchestra-geoserver     at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
georchestra-geoserver     at java.base/java.lang.Thread.run(Unknown Source)    
georchestra-geoserver Caused by: java.lang.IllegalStateException: Expected: RenderedImageMap, got null
georchestra-geoserver     at org.geoserver.gwc.layer.GeoServerTileLayer.dispatchGetMap(GeoServerTileLayer.java:696)
georchestra-geoserver     at org.geoserver.gwc.layer.GeoServerTileLayer.getMetatilingReponse(GeoServerTileLayer.java:613)
georchestra-geoserver     ... 10 more
```

Does it ring a bell for someone ?

I had it happen on 2 rster datasets, one was an image pyramid, the other one a cascaded WMS

I was trying to seed a EPSG:900913 grid (BTW, is it still the propser name/definition ? Will it be used ?)

On a geOrchestra 23.0.6, geoserver 2.22.2

**Comment by fvanderbiest** [comment]
Does the raster layer work as expected when a client requests it with EPSG:900913 WMS?

**Comment by fvanderbiest** [comment]
> I was trying to seed a EPSG:900913 grid (BTW, is it still the propser name/definition ? Will it be used ?)

See also the https://github.com/GeoWebCache/geowebcache/issues/103 thread ...

**Comment by jeanpommier** [comment]
Thanks. I'll investigate more, i'm assigning this to me
