### ISSUE TITLE
geonetwork - multiple versions of javax/jakarta.activation in the classpath

### ISSUE THREAD

**Issue by pmauduit** [georchestra/georchestra#4233]
Encountered with a geonetwork 23.0.6 docker image:

```
jetty@georchestra-geonetwork-58b8886bf5-jzcsd:~/webapps/geonetwork/WEB-INF/lib$ for i in *activation*jar ; do echo $i && unzip -t $i | grep /DataSource.class ; done
activation-1.1.jar
    testing: javax/activation/DataSource.class   OK
jakarta.activation-1.2.2.jar
    testing: javax/activation/DataSource.class   OK
jakarta.activation-api-1.2.1.jar
    testing: javax/activation/DataSource.class   OK
javax.activation-api-1.2.0.jar
    testing: javax/activation/DataSource.class   OK
```

Leading to the following error when GN tries to send a mail:

```
georchestra-geonetwork Caused by: java.lang.NoClassDefFoundError: javax/activation/DataSource
georchestra-geonetwork     at org.apache.commons.mail.HtmlEmail.build(HtmlEmail.java:580) ~[commons-email-1.5.jar:1.5]
georchestra-geonetwork     at org.apache.commons.mail.HtmlEmail.buildMimeMessage(HtmlEmail.java:509) ~[commons-email-1.5.jar:1.5]
georchestra-geonetwork     at org.apache.commons.mail.Email.send(Email.java:1495) ~[commons-email-1.5.jar:1.5]
georchestra-geonetwork     at org.fao.geonet.util.MailUtil.testSendMail(MailUtil.java:488) ~[gn-core-4.2.2-georchestra.jar:?]
georchestra-geonetwork     at org.fao.geonet.util.MailUtil.testSendMail(MailUtil.java:459) ~[gn-core-4.2.2-georchestra.jar:?]
georchestra-geonetwork     at org.fao.geonet.api.tools.mail.MailApi.testMailConfiguration(MailApi.java:109) ~[gn-services-4.2.2-georchestra.jar:?]
georchestra-geonetwork     at org.fao.geonet.api.tools.mail.MailApi$$FastClassBySpringCGLIB$$beada2b1.invoke(<generated>) ~[gn-services-4.2.2-georchestra.jar:?]
georchestra-geonetwork     at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218) ~[spring-core-5.2.20.RELEASE.jar:5.2.20.RELEASE]
georchestra-geonetwork     at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:783) ~[spring-aop-5.2.20.RELEASE.jar:5.2.20.RELEASE]
georchestra-geonetwork     at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163) ~[spring-aop-5.2.20.RELEASE.jar:5.2.20.RELEASE]
georchestra-geonetwork     at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:753) ~[spring-aop-5.2.20.RELEASE.jar:5.2.20.RELEASE]
georchestra-geonetwork     at org.springframework.security.access.intercept.aopalliance.MethodSecurityInterceptor.invoke(MethodSecurityInterceptor.java:61) ~[spring-security-core-5.7.3.jar:5.7.3]
georchestra-geonetwork     at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186) ~[spring-aop-5.2.20.RELEASE.jar:5.2.20.RELEASE]
georchestra-geonetwork     at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:753) ~[spring-aop-5.2.20.RELEASE.jar:5.2.20.RELEASE]
georchestra-geonetwork     at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:698) ~[spring-aop-5.2.20.RELEASE.jar:5.2.20.RELEASE]
georchestra-geonetwork     at org.fao.geonet.api.tools.mail.MailApi$$EnhancerBySpringCGLIB$$5f5762c8.testMailConfiguration(<generated>) ~[gn-services-4.2.2-georchestra.jar:?]
```

Might relate to:
* https://github.com/georchestra/georchestra/issues/3704
* https://github.com/georchestra/georchestra/issues/2953
* https://github.com/georchestra/georchestra/pull/3693/files

**Comment by pmauduit** [comment]
Actually all 4 versions  of the DataSource definition are the same in previously mentioned jar. The issue could also come from using Jetty as base docker image, which provides its own javax.mail version under `/usr/local/jetty/lib/mail`.

**Comment by pmauduit** [comment]
wondering if it'd be worth porting it back to 23.x
