### ISSUE TITLE
[datafeeder] import  page doesnt load

### ISSUE THREAD

**Issue by landryb** [georchestra/georchestra#4284]
witnessed on https://demo.georchestra.org/import/, there's a white page, and this error in the datafeeder backend log:

```
Caused by: com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException: Unrecognized field "isExternalAuth" (class org.georchestra.security.model.GeorchestraUser), not marked as ignorable (16 known properties: "lastName", "lastUpdated", "ldapRemainingDays", "postalAddress", "oauth2Provider", "telephoneNumber", "organization", "oauth2Uid", "username", "title", "id", "email", "roles", "notes", "ldapWarn", "firstName"])
 at [Source: (String)"{"username":"testadmin","roles":["ADMINISTRATOR","SUPERUSER","GN_ADMIN","MAPSTORE_ADMIN"],"organization":"PSC","id":"048b2f38-6ee7-4eec-9bed-349cc6eb13c4","lastUpdated":"ad771e09da8b49da4cd599bcb5c5cc1fb7c01a92624ec094ea8ffa0adde88cd0","firstName":"Test","lastName":"ADMIN","email":"psc+testadmin@georchestra.org","notes":"Internal CRM notes on testuser","isExternalAuth":false}"; line: 1, column: 378] (through reference chain: org.georchestra.security.model.GeorchestraUser["isExternalAuth"])
        at com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException.from(UnrecognizedPropertyException.java:61) ~[jackson-databind-2.11.2.jar!/:2.11.2]
        at com.fasterxml.jackson.databind.DeserializationContext.handleUnknownProperty(DeserializationContext.java:855) ~[jackson-databind-2.11.2.jar!/:2.11.2]
        at com.fasterxml.jackson.databind.deser.std.StdDeserializer.handleUnknownProperty(StdDeserializer.java:1212) ~[jackson-databind-2.11.2.jar!/:2.11.2]
        at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.handleUnknownProperty(BeanDeserializerBase.java:1604) ~[jackson-databind-2.11.2.jar!/:2.11.2]
        at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.handleUnknownVanilla(BeanDeserializerBase.java:1582) ~[jackson-databind-2.11.2.jar!/:2.11.2]
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:299) ~[jackson-databind-2.11.2.jar!/:2.11.2]
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:156) ~[jackson-databind-2.11.2.jar!/:2.11.2]
        at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4524) ~[jackson-databind-2.11.2.jar!/:2.11.2]
        at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3466) ~[jackson-databind-2.11.2.jar!/:2.11.2]
        at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3434) ~[jackson-databind-2.11.2.jar!/:2.11.2]
        at org.georchestra.config.security.GeorchestraUserDetails.decodeUserFromJSON(GeorchestraUserDetails.java:237) ~[security-proxy-spring-integration-23.1-SNAPSHOT.jar!/:na]
        ... 44 common frames omitted
```

that's with the security-proxy and packages from master.

first occurence of the error in the log is from march.

**Comment by landryb** [comment]
the same error now happens when connected on https://demo.georchestra.org/geonetwork/srv/eng/catalog.search

```
Message com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException: Unrecognized field "isExternalAuth" (class org.georchestra.security.model.GeorchestraUser), not marked as ignorable (16 known properties: "lastName", "lastUpdated", "ldapRemainingDays", "postalAddress", "oauth2Provider", "telephoneNumber", "organization", "oauth2Uid", "username", "title", "id", "email", "roles", "notes", "ldapWarn", "firstName"]
```

**Comment by landryb** [comment]
`isExternalAuth` comes from 07d3facfb0 ? and it's missing from the list of fields to parse in https://github.com/georchestra/georchestra/blob/master/security-proxy-spring-integration/src/main/java/org/georchestra/config/security/GeorchestraUserDetails.java#L60 ?

(note: i have no idea what im talking about, just doing some random suppositions)

**Comment by landryb** [comment]
the issue seems to be for the two applications using `send-json-sec-user` per https://github.com/georchestra/datadir/blob/master/security-proxy/headers-mapping.properties#L77

**Comment by landryb** [comment]
regression from [#4183](https://github.com/georchestra/georchestra/pull/4183)) ? if so it might affect 24.0 and pretty badly.

**Comment by landryb** [comment]
maybe 'just' a missing `@JsonProperty(UserSchema.ISEXTERNALAUTH_KEY)` in https://github.com/georchestra/georchestra/blob/master/ldap-account-management/src/main/java/org/georchestra/ds/users/AccountImpl.java#L169 plus addition of the key in https://github.com/georchestra/georchestra/blob/master/ldap-account-management/src/main/java/org/georchestra/ds/users/UserSchema.java#L65 ?

@pmauduit ? sorry but i dont grasp all those java indirections ...

**Comment by landryb** [comment]
i cant reproduce on another test instance...

**Comment by pmauduit** [comment]
For me it sounds as a desynchronization between the import app and the SP / GW, like if both had different versions of the [security-proxy-spring-integration](https://github.com/georchestra/georchestra/blob/master/security-proxy-spring-integration/src/main/java/org/georchestra/config/security/GeorchestraSecurityProxyAuthenticationFilter.java) & ldap-account-management module.

> (note: i have no idea what im talking about, just doing some random suppositions)

That is also my understanding of the issue, currently

**Comment by landryb** [comment]
looking with tcpdump on what headers are sent to GN on a working master instance, i see that the json for `sec-user` contains the `isExternalAuth` boolean, and GN doesn't complain. It is strange, because the war/package comes from the same source (the debian packages from the bot) as the one on the public demo..

comparing the jars, i think i got it, because the demo has :
```
-rw-r----- 1 tomcat tomcat 20977 Jul 11 13:24 /srv/tomcat/georchestra/webapps/geonetwork/WEB-INF/lib/georchestra-commons-23.1-SNAPSHOT.jar
```
while my working instance has:
```
-rw-r----- 1 tomcat tomcat 23384 Jul 12 18:36 /srv/tomcat/georchestra/webapps/geonetwork/WEB-INF/lib/georchestra-commons-24.1-SNAPSHOT.jar
```
how this (probably wrong?) jar ends up in the war is beyond my understanding.

and for datafeeder, this one doesnt work for some reason (`NullInjectorError: NullInjectorError: No provider for i!` in the js console, but doesnt blow a traceback:
```
root@bookworm:~# unzip -l /usr/share/lib/georchestra-datafeeder/datafeeder-bin.jar|grep georchestra-commons
    23384  2024-07-12 18:36   BOOT-INF/lib/georchestra-commons-24.1-SNAPSHOT.jar
```
while the demo has .. the same jar:
```
root@demo:/etc/georchestra# unzip -l /usr/share/lib/georchestra-datafeeder/datafeeder-bin.jar|grep georchestra-commons
    23384  2024-07-11 13:33   BOOT-INF/lib/georchestra-commons-24.1-SNAPSHOT.jar
```

**Comment by landryb** [comment]
summarizing our findings:
- for datafeeder, the problem has been fixed at some point when updating, but right now datafeeder is broken because of an angular injection issue:`NullInjectorError: NullInjectorError: No provider for i!`
- for GN, what is shipped in master is okay since https://github.com/georchestra/geonetwork/commit/fe463d8ae3927038588ef8d1e15f10152074fab4, but 24.0 is broken because the war contains the wrong version of the integration jars:
```
root@buildbot:/var/lib/buildbot/masters/georchestra# unzip -l public_html/wars/24.0.x/geonetwork.war |grep 23.1-
    20977  2024-07-11 13:24   WEB-INF/lib/georchestra-commons-23.1-SNAPSHOT.jar
    20405  2024-06-27 13:13   WEB-INF/lib/security-proxy-spring-integration-23.1-SNAPSHOT.jar
```

what needs to be done for GN in 24.0:
- branch `georchestra-gn4.2.x-24.0` in the georchestra/geonetwork repo, set `georchestra.version` to `24.0` (like it was done in https://github.com/georchestra/geonetwork/commit/fe463d8ae3927038588ef8d1e15f10152074fab4 but with a different version)
- in the 24.0 branch, point at that branch/commit in the submodule

**Comment by landryb** [comment]
for the datafeeder issue, @f-necas has pushed https://github.com/georchestra/geonetwork-ui/commit/6044c7513f7008748da8869c6db2ee36f3e7f847 (is it the right commit for the `NullInjector` fix ?) which from my understanding should be backported to the master branch too

**Comment by f-necas** [comment]
> for the datafeeder issue, @f-necas has pushed [georchestra/geonetwork-ui@6044c75](https://github.com/georchestra/geonetwork-ui/commit/6044c7513f7008748da8869c6db2ee36f3e7f847) (is it the right commit for the `NullInjector` fix ?) which from my understanding should be backported to the master branch too

Done for master too

**Comment by landryb** [comment]
> > for the datafeeder issue, @f-necas has pushed [georchestra/geonetwork-ui@6044c75](https://github.com/georchestra/geonetwork-ui/commit/6044c7513f7008748da8869c6db2ee36f3e7f847) (is it the right commit for the `NullInjector` fix ?) which from my understanding should be backported to the master branch too
> 
> Done for master too

awesome, thanks - triggering a manual run of the buildbot

**Comment by landryb** [comment]
https://demo.georchestra.org/import/ works again ! thanks @f-necas !
