### ISSUE TITLE
geoserver rest xml resources NOK

### ISSUE THREAD

**Issue by fvanderbiest** [georchestra/georchestra#616]
The http://sdi.georchestra.org/geoserver/rest/layers.xml service displays `Layer layers not found`. Since this service is used by geofence, geofence does not work as expected.

In the logs:

```
2014-03-15 18:03:22,557 ERROR [geoserver.rest] - Layer layers not found
2014-03-15 18:03:22,558 ERROR [geoserver.rest] -
org.geoserver.rest.RestletException
        at org.geoserver.geosearch.rest.GeoSearchLayerFinder.findTarget(GeoSearchLayerFinder.java:62)
        at org.restlet.Finder.handle(Finder.java:268)
        at org.geoserver.rest.BeanDelegatingRestlet.handle(BeanDelegatingRestlet.java:37)
        at org.restlet.Filter.doHandle(Filter.java:105)
        at org.restlet.Filter.handle(Filter.java:134)
        at org.restlet.Router.handle(Router.java:444)
        at org.geoserver.rest.RESTDispatcher$1.handle(RESTDispatcher.java:204)
        at com.noelios.restlet.ext.servlet.ServletConverter.service(ServletConverter.java:129)
        at org.geoserver.rest.RESTDispatcher.handleRequestInternal(RESTDispatcher.java:86)
        at org.springframework.web.servlet.mvc.AbstractController.handleRequest(AbstractController.java:153)
        at org.springframework.web.servlet.mvc.SimpleControllerHandlerAdapter.handle(SimpleControllerHandlerAdapter.java:48)
        at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:923)
        at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:852)
        at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:882)
        at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:778)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:617)
```

... makes me think of a bad interaction with the http://geoserver.org/display/GEOS/GeoSearch+Module

Let's try to compile GeoServer without GeoSearch

**Comment by landryb** [comment]
Fwiw, i'm hitting that issue on master with wars produced by georchestra-template-geofence jenkins job.. which enables the geosearch extension :)

**Comment by landryb** [comment]
And i can confirm that rebuilding geoserver-geofence, (removing the geosearch extension from the build), fixes /rest/layers.xml call on geoserver, and geofence can enumerate the workspaces/layers in the remote geoserver.

Should a bug be filed against geosearch extension, or maven prevent users from building geofence & geosearch at the same time ?

**Comment by fvanderbiest** [comment]
> Fwiw, i'm hitting that issue on master with wars produced by georchestra-template-geofence jenkins job.. which enables the geosearch extension :)

OK, the next geofence/geoserver build will not have geosearch enabled.
https://sdi.georchestra.org/ci/job/georchestra-template-geofence/3/

> Should a bug be filed against geosearch extension

Yes, I think so.

**Comment by landryb** [comment]
http://jira.codehaus.org/browse/GEOS-6835

**Comment by landryb** [comment]
Was probably a duplicate of http://jira.codehaus.org/browse/GEOS-5671
