### ISSUE TITLE
geofence - nested layer groups break the capabilities

### ISSUE THREAD

**Issue by fvanderbiest** [georchestra/georchestra#746]
2014-08-27 12:24:42,788 ERROR [geoserver.ows] - 
org.geoserver.platform.ServiceException: javax.xml.transform.TransformerException: java.lang.NullPointerException
    at org.geoserver.wms.capabilities.Capabilities_1_3_0_Response.write(Capabilities_1_3_0_Response.java:49)
    at org.geoserver.ows.Dispatcher.response(Dispatcher.java:919)
    at org.geoserver.ows.Dispatcher.handleRequestInternal(Dispatcher.java:276)
    at org.springframework.web.servlet.mvc.AbstractController.handleRequest(AbstractController.java:153)
    at org.springframework.web.servlet.mvc.SimpleControllerHandlerAdapter.handle(SimpleControllerHandlerAdapter.java:48)
    at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:923)
    at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:852)
    at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:882)
    at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:778)
[....]
Caused by: java.lang.NullPointerException
    at org.geoserver.security.SecureCatalogImpl.buildWrapperPolicy(SecureCatalogImpl.java:730)
    at org.geoserver.security.SecureCatalogImpl$2.evaluate(SecureCatalogImpl.java:1592)
    at org.geoserver.security.SecureCatalogImpl$2.evaluate(SecureCatalogImpl.java:1586)
    at org.geotools.filter.FilterAbstract.eval(FilterAbstract.java:129)
    at org.geotools.filter.MultiCompareFilterImpl.evaluate(MultiCompareFilterImpl.java:67)
    at org.geotools.filter.AndImpl.evaluate(AndImpl.java:57)
    at org.geoserver.catalog.impl.DefaultCatalogFacade$1.apply(DefaultCatalogFacade.java:1182)
    at org.geoserver.catalog.impl.DefaultCatalogFacade$1.apply(DefaultCatalogFacade.java:1178)

**Comment by f-necas** [comment]
geofence isn't used and maintained actively
