### ISSUE TITLE
geoserver - layergroups cannot have no cached layer

### ISSUE THREAD

**Issue by fvanderbiest** [georchestra/georchestra#884]
Using the docker setup, in the geofence branch, when creating a layergroup **with no caching**, there's a NPE:
```
geoserver_1    | 16 Jan 08:45:40 WARN [geoserver.web] - Error adding/modifying layer group.
geoserver_1    | java.lang.NullPointerException
geoserver_1    |        at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:213)
geoserver_1    |        at org.geoserver.gwc.layer.CatalogConfiguration.removeLayer(CatalogConfiguration.java:536)
geoserver_1    |        at org.geowebcache.layer.TileLayerDispatcher.removeLayer(TileLayerDispatcher.java:237)
geoserver_1    |        at org.geoserver.gwc.GWC.removeTileLayers(GWC.java:1738)
geoserver_1    |        at org.geoserver.gwc.web.layer.GeoServerTileLayerEditor.save(GeoServerTileLayerEditor.java:297)
geoserver_1    |        at org.geoserver.gwc.web.layer.LayerGroupCacheOptionsPanel.save(LayerGroupCacheOptionsPanel.java:73)
geoserver_1    |        at org.geoserver.web.data.layergroup.AbstractLayerGroupPage$7.component(AbstractLayerGroupPage.java:269)
geoserver_1    |        at org.geoserver.web.data.layergroup.AbstractLayerGroupPage$7.component(AbstractLayerGroupPage.java:266)
geoserver_1    |        at org.apache.wicket.MarkupContainer.visitChildren(MarkupContainer.java:899)
geoserver_1    |        at org.apache.wicket.MarkupContainer.visitChildren(MarkupContainer.java:914)
geoserver_1    |        at org.geoserver.web.data.layergroup.AbstractLayerGroupPage.save(AbstractLayerGroupPage.java:265)
geoserver_1    |        at org.geoserver.web.data.layergroup.AbstractLayerGroupPage.access$500(AbstractLayerGroupPage.java:53)
geoserver_1    |        at org.geoserver.web.data.layergroup.AbstractLayerGroupPage$6.onSubmit(AbstractLayerGroupPage.java:252)
```

The layergroup is created, but the "Create a cached layer for this layergroup" checkbox is activated when I display it again.

**Comment by pmauduit** [comment]
tested onto sdi.g.o, able to activate / deactivate layer caching on a layergroup.
