### ISSUE TITLE
geoserver: rest call results filtered to non-admin users

### ISSUE THREAD

**Issue by landryb** [georchestra/georchestra#887]
Background: i'm trying to configure geoserver rest to allow non-admin users (ie, say, ROLE_SV_EDITOR) to POST styles into a workspace. This works fine in geoserver 2.3.2 (the upstream version im running now)

In current master (so geoserver 2.5.4-georchestra + geofence), i first saw that listing workspaces was not working for non-admin users. The returned workspace list is empty. The behaviour is the same if i bypass the sec-proxy, directly talking to geoserver, or if i send http auth headers via sec-proxy

```
# direct call to geoserver
#curl -H'sec-roles:ROLE_SV_EDITOR' -H'sec-username:dalulz'   http://10.0.1.19:8280/geoserver/rest/workspaces.xml
<workspaces/>

# via sec-proxy
#curl -u testeditor:testeditor http://10.0.1.19:8180/geoserver/rest/workspaces.xml
<workspaces/>
```
as testadmin, it works fine:
```
#curl -u testadmin:testadmin http://10.0.1.19:8180/geoserver/rest/workspaces.xml
<workspaces>
  <workspace>
    <name>geor_loc</name>
  </workspace>
  <workspace>
    <name>wmsproxy</name>
  </workspace>
<workspaces/>
```

According to @fvanderbiest the issue is also present in 14.06.

geoserver is configured with the default rest.properties/layers.properties, i only added write/admin rights to SV_EDITOR ie
```
# security.properties
/**;GET=ROLE_SV_USER,ROLE_SV_REVIEWER,ROLE_SV_EDITOR,ROLE_SV_ADMIN,ROLE_ADMINISTRATOR
/rest/**/styles/**;POST,DELETE,PUT=ROLE_SV_EDITOR
/**;POST,DELETE,PUT=ROLE_ADMINISTRATOR
# layers.properties
*.*.r=*
*.*.a=ROLE_SV_EDITOR
mode=MIXED
```
REST config doesnt seem at fault since if i enable more debugging, i see the path rules correctly applied
```
log4j.category.org.geoserver.rest=DEBUG
log4j.category.org.geoserver.security=DEBUG
#
2015-01-16 13:45:59,785 DEBUG [geoserver.security] - for principal testeditor found roles ROLE_SV_EDITOR in header sec-roles
2015-01-16 13:45:59,786 DEBUG [security.RESTfulPathBasedFilterInvocationDefinitionMap] - Converted URL to lowercase, from: '/rest/workspaces.xml'; to: '/rest/workspaces.xml'  and httpMethod= GET
2015-01-16 13:45:59,786 DEBUG [security.RESTfulPathBasedFilterInvocationDefinitionMap] - ~~~~~~~~~~ antPath= /** methodList= [GET]
2015-01-16 13:45:59,786 DEBUG [security.RESTfulPathBasedFilterInvocationDefinitionMap] - Candidate is: '/rest/workspaces.xml'; antPath is /**; matchedPath=true; matchedMethods=true
2015-01-16 13:45:59,786 DEBUG [security.RESTfulPathBasedFilterInvocationDefinitionMap] - returning ROLE_SV_USER,ROLE_SV_REVIEWER,ROLE_SV_EDITOR,ROLE_SV_ADMIN,ROLE_ADMINISTRATOR
2015-01-16 13:45:59,799 DEBUG [filter.GeoServerSecurityContextPersistenceFilter$1] - SecurityContextHolder now cleared, as request processing completed
2015-01-16 13:46:45,296 DEBUG [geoserver.security] - preAuthenticatedPrincipal = testadmin, trying to authenticate
2015-01-16 13:46:45,297 DEBUG [geoserver.security] - for principal testadmin found roles ROLE_MOD_LDAPADMIN,ROLE_SV_ADMIN,ROLE_ADMINISTRATOR,ROLE_MOD_ANALYTICS,ROLE_MOD_EXTRACTORAPP in header sec-roles
2015-01-16 13:46:45,297 DEBUG [security.RESTfulPathBasedFilterInvocationDefinitionMap] - Converted URL to lowercase, from: '/rest/workspaces.xml'; to: '/rest/workspaces.xml'  and httpMethod= GET
2015-01-16 13:46:45,297 DEBUG [security.RESTfulPathBasedFilterInvocationDefinitionMap] - ~~~~~~~~~~ antPath= /** methodList= [GET]
2015-01-16 13:46:45,297 DEBUG [security.RESTfulPathBasedFilterInvocationDefinitionMap] - Candidate is: '/rest/workspaces.xml'; antPath is /**; matchedPath=true; matchedMethods=true
2015-01-16 13:46:45,297 DEBUG [security.RESTfulPathBasedFilterInvocationDefinitionMap] - returning ROLE_SV_USER,ROLE_SV_REVIEWER,ROLE_SV_EDITOR,ROLE_SV_ADMIN,ROLE_ADMINISTRATOR

```
When a rest call is done by a non-admin user on a specific workspace, the following traceback is shown in geoserver:

```
2015-01-16 11:53:23,039 DEBUG [geoserver.security] - preAuthenticatedPrincipal = dalulz, trying to authenticate
2015-01-16 11:53:23,039 DEBUG [geoserver.security] - for principal dalulz found roles ROLE_SV_EDITOR in header sec-roles
2015-01-16 11:53:23,039 DEBUG [security.RESTfulPathBasedFilterInvocationDefinitionMap] - Converted URL to lowercase, from: '/rest/namespaces/geor_loc'; to: '/rest/namespaces/geor_loc'  and httpMethod= GET
2015-01-16 11:53:23,039 DEBUG [security.RESTfulPathBasedFilterInvocationDefinitionMap] - ~~~~~~~~~~ antPath= /** methodList= [GET]
2015-01-16 11:53:23,039 DEBUG [security.RESTfulPathBasedFilterInvocationDefinitionMap] - Candidate is: '/rest/namespaces/geor_loc'; antPath is /**; matchedPath=true; matchedMethods=true
2015-01-16 11:53:23,039 DEBUG [security.RESTfulPathBasedFilterInvocationDefinitionMap] - returning ROLE_SV_USER,ROLE_SV_REVIEWER,ROLE_SV_EDITOR,ROLE_SV_ADMIN,ROLE_ADMINISTRATOR
2015-01-16 11:53:23,041 ERROR [geoserver.rest] - No such namespace: geor_loc
2015-01-16 11:53:23,041 ERROR [geoserver.rest] - 
org.geoserver.rest.RestletException
        at org.geoserver.catalog.rest.NamespaceFinder.findTarget(NamespaceFinder.java:33)
        at org.restlet.Finder.handle(Finder.java:268)
        at org.geoserver.rest.BeanDelegatingRestlet.handle(BeanDelegatingRestlet.java:38)
        at org.restlet.Filter.doHandle(Filter.java:105)
        at org.restlet.Filter.handle(Filter.java:134)
        at org.restlet.Router.handle(Router.java:444)
        at org.geoserver.rest.RESTDispatcher$1.handle(RESTDispatcher.java:205)
        at com.noelios.restlet.ext.servlet.ServletConverter.service(ServletConverter.java:129)
        at org.geoserver.rest.RESTDispatcher.handleRequestInternal(RESTDispatcher.java:87)
        at org.springframework.web.servlet.mvc.AbstractController.handleRequest(AbstractController.java:153)
        at org.springframework.web.servlet.mvc.SimpleControllerHandlerAdapter.handle(SimpleControllerHandlerAdapter.java:48)
        at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:923)
        at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:852)
        at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:882)
        at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:778)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:617)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:717)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:290)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
        at org.geoserver.filters.ThreadLocalsCleanupFilter.doFilter(ThreadLocalsCleanupFilter.java:28)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:235)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
        at org.geoserver.filters.SpringDelegatingFilter$Chain.doFilter(SpringDelegatingFilter.java:75)
        at org.geoserver.wms.animate.AnimatorFilter.doFilter(AnimatorFilter.java:71)
        at org.geoserver.filters.SpringDelegatingFilter$Chain.doFilter(SpringDelegatingFilter.java:71)
        at org.geoserver.flow.controller.IpBlacklistFilter.doFilter(IpBlacklistFilter.java:93)
        at org.geoserver.filters.SpringDelegatingFilter$Chain.doFilter(SpringDelegatingFilter.java:71)
        at org.geoserver.filters.SpringDelegatingFilter.doFilter(SpringDelegatingFilter.java:46)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:235)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
        at org.geoserver.platform.AdvancedDispatchFilter.doFilter(AdvancedDispatchFilter.java:50)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:235)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
        at org.vfny.geoserver.filters.SetCharacterEncodingFilter.doFilter(SetCharacterEncodingFilter.java:109)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:235)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:311)
        at org.geoserver.security.filter.GeoServerCompositeFilter$NestedFilterChain.doFilter(GeoServerCompositeFilter.java:69)
        at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.invoke(FilterSecurityInterceptor.java:116)
        at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.doFilter(FilterSecurityInterceptor.java:83)
        at org.geoserver.security.filter.GeoServerCompositeFilter$NestedFilterChain.doFilter(GeoServerCompositeFilter.java:73)
        at org.geoserver.security.filter.GeoServerCompositeFilter.doFilter(GeoServerCompositeFilter.java:92)

```

As if something was filtering the output or the access to workspaces to non-admin users.

Same thing if listing layers/namespaces. So in the end, in the usecase i target, POST'ing as testeditor to /rest/workspaces/geor_loc/styles results in a 404, since it can't see/access the geor_loc workspace.

I'll make some tests with a pristine geoserver, then geoserver-georchestra without geofence, but i doubt geofence is at fault here, since nothing is logged in geofence when an access is made via REST.

**Comment by landryb** [comment]
'disabling' geofence auth (ie reverting the ```security/auth/default/config.xml``` change from ```it.geosolutions.geoserver.authentication.auth.GeofenceAuthenticationProvider``` back to ```org.geoserver.security.auth.UsernamePasswordAuthenticationProvider``` doesnt change the behaviour.

**Comment by landryb** [comment]
Fwiw, testing with a plain geoserver 2.5.4 from upstream, it seems the issue is present there too.
In the default config provided with the war, only changing rest.properties for
```
/**;GET=IS_AUTHENTICATED_ANONYMOUSLY
/**;POST,DELETE,PUT=ADMIN
```
Without sending credentials, the list of workspaces is empty:
```
$curl http://localhost:8080/geoserver/rest/workspaces.xml         
<workspaces/>
```
Same thing with geoserver-2.5.4-georchestra + geofence

**Comment by landryb** [comment]
Related to http://jira.codehaus.org/browse/GEOS-5069 ?

**Comment by landryb** [comment]
Fwiw, on plain 2.5.4, setting catalog mode to CHALLENGE correctly lists all the workspaces as unauthenticated user. If using MIXED (the setting advertised by georchestra), i get this error:
```
19 Jan 14:46:25 ERROR [geoserver.rest] - :Cannot access cite with the current privileges
19 Jan 14:46:25 ERROR [geoserver.rest] - 
org.geoserver.rest.RestletException: org.springframework.security.access.AccessDeniedException: Cannot access cite with the current privile
ges
        at org.geoserver.rest.ReflectiveResource.handleException(ReflectiveResource.java:326)
        at org.geoserver.rest.ReflectiveResource.handleGet(ReflectiveResource.java:92)
        at org.restlet.Finder.handle(Finder.java:292)
        at org.geoserver.rest.BeanDelegatingRestlet.handle(BeanDelegatingRestlet.java:38)
        at org.restlet.Filter.doHandle(Filter.java:105)
        at org.restlet.Filter.handle(Filter.java:134)
        at org.restlet.Router.handle(Router.java:444)

```

So it seems this is related to catalog mode.

**Comment by fvanderbiest** [comment]
In Challenge mode, layer metadata are made public => this seems logic.

But in Mixed mode, you should at least see public layers.

**Comment by landryb** [comment]
In a default geoserver setup, all layers should be public, layers.properties contains:
```
*.*.r=*
*.*.w=*
mode=MIXED
```

**Comment by landryb** [comment]
I can reproduce the issue with http://build.geo-solutions.it/geofence/nightly/latest/geofence.war and http://build.geo-solutions.it/geofence/nightly/latest/2.5.x/geoserver.war, so i've started a thread on geoserver-users@... but i dont have much hope on this. Note that in that version of geoserver/geofence, there's been some improvements to geofence (filter on src ip) and there's a web page configuration for geofence directly inside geoserver.

**Comment by landryb** [comment]
Replying to myself in the previous-previous comment.. to get access to layers via REST in mode=MIXED, one needs *admin* access via layers.properties (still with upstream geoserver 2.5.4)
```
*.*.r=*
topp.*.a=ROLE_AUTHENTICATED
*.*.w=*
mode=MIXED
```
curl -utiger:tiger http://localhost:8080/geoserver/rest/layers/ lists only the layers present in topp workspace.
curl -utiger:tiger http://localhost:8080/geoserver/rest/workspaces/topp.xml shows the details for topp workspace, but curl -utiger:tiger http://localhost:8080/geoserver/rest/workspaces/ fails as it tries to access all workspaces, and the user doesnt have enough rights for that. Still, since geofence seems to enforce mode=HIDDEN...

**Comment by landryb** [comment]
And interestingly, in HIDDEN mode, calling /rest/workspaces only shows the workspace on which the user has admin rights. No error shown. Now, to see what happens when geofence enters the party..

**Comment by landryb** [comment]
And when geofence is enabled everything is hidden, even with topp.*.a=ROLE_AUTHENTICATED. layers.properties is bypassed. Listing layers, workspaces, or even trying to directly access a layer/workspace on which you should have sufficient rights, all fail.

**Comment by landryb** [comment]
After adding some debug code to src/main/src/main/java/org/geoserver/security/SecureCatalogImpl.java, i can see that checkAccess() in filterWorkspaces() is the call denying access to workspaces to non-admin users... maybe related to the fix @pmauduit is working on for layergroup issues ? ie subclasses inheritance/loading issues ?

**Comment by landryb** [comment]
a non-geofence enabled geoserver from https://sdi.georchestra.org/ci/job/georchestra-template/lastSuccessfulBuild works fine with mode=HIDDEN + *.*.a = ROLE_AUTHENTICATED gives access to non-privileged users to all layers/workspaces via REST
